// Turns each scope's build/<scope>.delta.json into the publishable package:
// one ambient .d.ts per spec (grouped using @webref/idl to find which spec
// defines each construct), plus an aggregate entry point that references them.
// Window files are `<spec>.d.ts` / `index.d.ts`; Worker files carry a
// `.worker` suffix so both scopes coexist in one package.
import fs from "node:fs";
import path from "node:path";
import { parseAll } from "@webref/idl";
import { buildDir, pkgDir, augmentScopes, type Scope } from "./util.ts";

// Map every named IDL construct (and every interface/mixin/namespace member)
// to the spec shortname that defines it. Partial definitions contribute
// member mappings but never override the owner of the top-level name.
const nameToSpec = new Map<string, string>();
const memberToSpec = new Map<string, string>();
const specs = await parseAll();
for (const [shortname, defs] of Object.entries(specs)) {
  for (const def of defs as any[]) {
    if (def.name) {
      if (!def.partial && !nameToSpec.has(def.name)) {
        nameToSpec.set(def.name, shortname);
      }
      for (const member of def.members ?? []) {
        const key = `${def.name}.${member.name}`;
        if (member.name && !memberToSpec.has(key)) {
          memberToSpec.set(key, shortname);
        }
      }
    }
  }
}

const MISC = "misc";

// The global interfaces a scope's free functions/vars hang off of, used to
// find the owning spec of a global declared as a partial-interface member.
const scopeGlobals: Record<string, string[]> = {
  dom: ["Window"],
  webworker: [
    "WorkerGlobalScope",
    "DedicatedWorkerGlobalScope",
    "ServiceWorkerGlobalScope",
    "SharedWorkerGlobalScope",
  ],
};

function specForName(name: string): string | undefined {
  if (nameToSpec.has(name)) return nameToSpec.get(name);
  // Generator-synthesized companions: FooEventMap follows Foo.
  const base = name.replace(/EventMap$/, "");
  if (base !== name && nameToSpec.has(base)) return nameToSpec.get(base);
  // Dictionaries like FooOptions/FooInit usually live with Foo.
  const stripped = name.replace(/(Options|Init|Info)$/, "");
  if (stripped !== name && nameToSpec.has(stripped)) {
    return nameToSpec.get(stripped);
  }
  return undefined;
}

function emitScope(scope: Scope): number {
  const augment = scope.augment!;
  const deltaPath = path.join(buildDir, augment.delta);
  if (!fs.existsSync(deltaPath)) return 0;
  const delta = JSON.parse(fs.readFileSync(deltaPath, "utf8"));
  const globals = scopeGlobals[scope.name];

  const specForItem = (item: { kind: string; name: string }): string => {
    if (item.kind === "function") {
      for (const g of globals) {
        const spec = memberToSpec.get(`${g}.${item.name}`);
        if (spec) return spec;
      }
      return MISC;
    }
    return specForName(item.name) ?? MISC;
  };
  const specForAugment = (a: { parent: string; memberName: string }): string =>
    memberToSpec.get(`${a.parent}.${a.memberName}`) ??
    specForName(a.parent) ??
    MISC;

  // Group everything by spec, preserving the emitter's original ordering.
  type Chunk = { pos: number; text: string };
  const files = new Map<string, Chunk[]>();
  const add = (spec: string, chunk: Chunk) => {
    const list = files.get(spec) ?? [];
    list.push(chunk);
    files.set(spec, list);
  };

  for (const item of delta.items) {
    add(specForItem(item), { pos: item.pos, text: item.text });
  }

  // Members augmenting the same interface within a spec merge into one block.
  const augmentGroups = new Map<string, { pos: number; members: string[] }>();
  for (const a of delta.augments) {
    const key = `${specForAugment(a)} ${a.parent}`;
    const group = augmentGroups.get(key) ?? { pos: a.pos, members: [] };
    group.members.push(a.text);
    augmentGroups.set(key, group);
  }
  for (const [key, group] of augmentGroups) {
    const [spec, parent] = key.split(" ");
    add(spec, {
      pos: group.pos,
      text: `interface ${parent} {\n${group.members.join("\n")}\n}`,
    });
  }

  for (const ns of delta.namespaceAugments) {
    const body = ns.statements.join("\n").replace(/^/gm, "    ");
    add(specForName(ns.parent) ?? MISC, {
      pos: ns.pos,
      text: `declare namespace ${ns.parent} {\n${body}\n}`,
    });
  }

  const header = (spec: string) =>
    `// Generated by modern-web-types from TypeScript-DOM-lib-generator\n` +
    `// (upstream ${delta.meta.upstreamSha.slice(0, 12)}) — do not edit.\n` +
    `// Scope: ${scope.name}. Spec: ${spec}\n\n`;

  const shortnames = [...files.keys()].sort();
  for (const spec of shortnames) {
    const chunks = files.get(spec)!;
    chunks.sort((a, b) => a.pos - b.pos);
    const body = chunks.map((c) => c.text).join("\n\n") + "\n";
    fs.writeFileSync(
      path.join(pkgDir, `${spec}${augment.suffix}.d.ts`),
      header(spec) + body,
    );
  }

  const index =
    `// Generated by modern-web-types — do not edit.\n` +
    `// References every ${scope.name}-scope spec file; import a single\n` +
    `// entry point (e.g. "modern-web-types/${shortnames[0]}${augment.suffix}") for granular opt-in.\n\n` +
    shortnames
      .map((s) => `/// <reference path="./${s}${augment.suffix}.d.ts" />`)
      .join("\n") +
    "\n";
  fs.writeFileSync(path.join(pkgDir, augment.index), index);

  console.log(
    `[${scope.name}] wrote ${shortnames.length} spec files + ${augment.index}` +
      (files.get(MISC) ? ` (${files.get(MISC)!.length} in ${MISC})` : ""),
  );
  return shortnames.length;
}

// Clear stale augment files (the replace libs, lib.*.d.ts, are owned by
// emit-lib), then emit every augment scope into pkg/.
fs.mkdirSync(pkgDir, { recursive: true });
for (const f of fs.readdirSync(pkgDir)) {
  if (f.endsWith(".d.ts") && !f.startsWith("lib.")) {
    fs.unlinkSync(path.join(pkgDir, f));
  }
}
for (const scope of augmentScopes) emitScope(scope);
