// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: dom. Spec: anchors

/**
 * The **`XRAnchor`** interface creates anchors which keep track of the pose that is fixed relative to the real world. With anchors, you can specify poses in the world that need to be updated to correctly reflect the evolving understanding of the world, such that the poses remain aligned with the same place in the physical world. That helps to build an illusion that the placed objects are really present in the user's environment.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRAnchor)
 */
interface XRAnchor {
    /**
     * The read-only **`anchorSpace`** property of the XRAnchor interface returns an XRSpace object to locate the anchor relative to other XRSpace objects. It can be passed to XRFrame.getPose() subsequently.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRAnchor/anchorSpace)
     */
    readonly anchorSpace: XRSpace;
    /**
     * The **`delete()`** method of the XRAnchor interface removes an anchor. This can be useful when an application is no longer interested in receiving updates to an anchor.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRAnchor/delete)
     */
    delete(): void;
}

declare var XRAnchor: {
    prototype: XRAnchor;
    new(): XRAnchor;
};

/**
 * The **`XRAnchorSet`** interface exposes a collection of anchors. Its instances are returned by XRFrame.trackedAnchors and are Set-like objects.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRAnchorSet)
 */
interface XRAnchorSet {
    forEach(callbackfn: (value: XRAnchor, key: XRAnchor, parent: XRAnchorSet) => void, thisArg?: any): void;
}

interface XRAnchorSet extends ReadonlySet<XRAnchor> {
}

declare var XRAnchorSet: {
    prototype: XRAnchorSet;
    new(): XRAnchorSet;
};
