// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: dom. Spec: audio-session

/**
 * The **`AudioSession`** interface of the Audio Session API allows developers to specify how audio from a web application interacts with other audio playing on a device.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/AudioSession)
 */
interface AudioSession extends EventTarget {
    /**
     * The **`type`** property of the AudioSession interface returns or sets the type of the audio session.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/AudioSession/type)
     */
    type: AudioSessionType;
}

declare var AudioSession: {
    prototype: AudioSession;
    new(): AudioSession;
};

interface Navigator {
    /**
     * The **`audioSession`** read-only property of the Navigator interface returns the AudioSession object for the current document.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Navigator/audioSession)
     */
    readonly audioSession: AudioSession;
}

type AudioSessionType = "ambient" | "auto" | "play-and-record" | "playback" | "transient" | "transient-solo";
