// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: window. Spec: autoplay-detection

interface Navigator {
    /**
     * The **`getAutoplayPolicy()`** method of the Autoplay Policy Detection API provides information about whether autoplay of media elements and audio contexts is allowed, disallowed, or only allowed if the audio is muted.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Navigator/getAutoplayPolicy)
     */
    getAutoplayPolicy(type: AutoplayPolicyMediaType): AutoplayPolicy;
    getAutoplayPolicy(element: HTMLMediaElement): AutoplayPolicy;
    getAutoplayPolicy(context: AudioContext): AutoplayPolicy;
}

type AutoplayPolicy = "allowed" | "allowed-muted" | "disallowed";

type AutoplayPolicyMediaType = "audiocontext" | "mediaelement";
