// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: webworker. Spec: background-sync

interface SyncEventInit extends ExtendableEventInit {
    lastChance?: boolean;
    tag: string;
}

interface ServiceWorkerGlobalScope {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/ServiceWorkerGlobalScope/sync_event) */
    onsync: ((this: ServiceWorkerGlobalScope, ev: SyncEvent) => any) | null;
}

interface ServiceWorkerRegistration {
    /**
     * The **`sync`** read-only property of the ServiceWorkerRegistration interface returns a reference to the SyncManager interface, which manages background synchronization processes.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ServiceWorkerRegistration/sync)
     */
    readonly sync: SyncManager;
}

/**
 * The **`SyncEvent`** interface of the Background Synchronization API represents a sync action that is dispatched on the ServiceWorkerGlobalScope of a ServiceWorker.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SyncEvent)
 */
interface SyncEvent extends ExtendableEvent {
    /**
     * The **`lastChance`** read-only property of the SyncEvent interface returns true if the user agent will not make further synchronization attempts after the current attempt. This is the value passed in the lastChance parameter of the SyncEvent() constructor.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SyncEvent/lastChance)
     */
    readonly lastChance: boolean;
    /**
     * The **`tag`** read-only property of the SyncEvent interface returns the developer-defined identifier for this SyncEvent. This is the value passed in the tag parameter of the SyncEvent() constructor.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SyncEvent/tag)
     */
    readonly tag: string;
}

declare var SyncEvent: {
    prototype: SyncEvent;
    new(type: string, init: SyncEventInit): SyncEvent;
};

/**
 * The **`SyncManager`** interface of the Background Synchronization API provides an interface for registering and listing sync registrations.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SyncManager)
 */
interface SyncManager {
    /**
     * The **`getTags()`** method of the SyncManager interface returns a list of developer-defined identifiers for SyncManager registrations.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SyncManager/getTags)
     */
    getTags(): Promise<string[]>;
    /**
     * The **`register()`** method of the SyncManager interface registers a synchronization event, triggering a sync event inside the associated service worker as soon as network connectivity is available.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SyncManager/register)
     */
    register(tag: string): Promise<void>;
}

declare var SyncManager: {
    prototype: SyncManager;
    new(): SyncManager;
};
