// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Spec: background-sync

interface ServiceWorkerRegistration {
    /**
     * The **`sync`** read-only property of the ServiceWorkerRegistration interface returns a reference to the SyncManager interface, which manages background synchronization processes.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ServiceWorkerRegistration/sync)
     */
    readonly sync: SyncManager;
}

/**
 * The **`SyncManager`** interface of the Background Synchronization API provides an interface for registering and listing sync registrations.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SyncManager)
 */
interface SyncManager {
    /**
     * The **`getTags()`** method of the SyncManager interface returns a list of developer-defined identifiers for SyncManager registrations.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SyncManager/getTags)
     */
    getTags(): Promise<string[]>;
    /**
     * The **`register()`** method of the SyncManager interface registers a synchronization event, triggering a sync event inside the associated service worker as soon as network connectivity is available.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SyncManager/register)
     */
    register(tag: string): Promise<void>;
}

declare var SyncManager: {
    prototype: SyncManager;
    new(): SyncManager;
};
