// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: window. Spec: background-fetch

interface BackgroundFetchOptions extends BackgroundFetchUIOptions {
    downloadTotal?: number;
}

interface BackgroundFetchUIOptions {
    icons?: ImageResource[];
    title?: string;
}

/**
 * The **`BackgroundFetchManager`** interface of the Background Fetch API is a map where the keys are background fetch IDs and the values are BackgroundFetchRegistration objects.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BackgroundFetchManager)
 */
interface BackgroundFetchManager {
    /**
     * The **`fetch()`** method of the BackgroundFetchManager interface initiates a background fetch operation, given one or more URLs or Request objects.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BackgroundFetchManager/fetch)
     */
    fetch(id: string, requests: RequestInfo | RequestInfo[], options?: BackgroundFetchOptions): Promise<BackgroundFetchRegistration>;
    /**
     * The **`get()`** method of the BackgroundFetchManager interface returns a Promise that resolves with the BackgroundFetchRegistration associated with the provided id or undefined if the id is not found.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BackgroundFetchManager/get)
     */
    get(id: string): Promise<BackgroundFetchRegistration | null>;
    /**
     * The **`getIds()`** method of the BackgroundFetchManager interface returns the IDs of all registered background fetches.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BackgroundFetchManager/getIds)
     */
    getIds(): Promise<string[]>;
}

interface BackgroundFetchManager {
    /**
     * The **`fetch()`** method of the BackgroundFetchManager interface initiates a background fetch operation, given one or more URLs or Request objects.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BackgroundFetchManager/fetch)
     */
    fetch(id: string, requests: RequestInfo | Iterable<RequestInfo>, options?: BackgroundFetchOptions): Promise<BackgroundFetchRegistration>;
}

declare var BackgroundFetchManager: {
    prototype: BackgroundFetchManager;
    new(): BackgroundFetchManager;
};

/**
 * The **`BackgroundFetchRecord`** interface of the Background Fetch API represents an individual request and response.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BackgroundFetchRecord)
 */
interface BackgroundFetchRecord {
    /**
     * The **`request`** read-only property of the BackgroundFetchRecord interface returns the details of the resource to be fetched.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BackgroundFetchRecord/request)
     */
    readonly request: Request;
    /**
     * The **`responseReady`** read-only property of the BackgroundFetchRecord interface returns a Promise that resolves with a Response.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BackgroundFetchRecord/responseReady)
     */
    readonly responseReady: Promise<Response>;
}

declare var BackgroundFetchRecord: {
    prototype: BackgroundFetchRecord;
    new(): BackgroundFetchRecord;
};

interface BackgroundFetchRegistrationEventMap {
    "progress": Event;
}

/**
 * The **`BackgroundFetchRegistration`** interface of the Background Fetch API represents an individual background fetch.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BackgroundFetchRegistration)
 */
interface BackgroundFetchRegistration extends EventTarget {
    /**
     * The **`downloadTotal`** read-only property of the BackgroundFetchRegistration interface returns the total size in bytes of this download. This is set when the background fetch was registered, or 0 if not set.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BackgroundFetchRegistration/downloadTotal)
     */
    readonly downloadTotal: number;
    /**
     * The **`downloaded`** read-only property of the BackgroundFetchRegistration interface returns the size in bytes that has been downloaded, initially 0.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BackgroundFetchRegistration/downloaded)
     */
    readonly downloaded: number;
    /**
     * The **`failureReason`** read-only property of the BackgroundFetchRegistration interface returns a string with a value that indicates a reason for a background fetch failure.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BackgroundFetchRegistration/failureReason)
     */
    readonly failureReason: BackgroundFetchFailureReason;
    /**
     * The **`id`** read-only property of the BackgroundFetchRegistration interface returns a copy of the background fetch's ID.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BackgroundFetchRegistration/id)
     */
    readonly id: string;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/BackgroundFetchRegistration/progress_event) */
    onprogress: ((this: BackgroundFetchRegistration, ev: Event) => any) | null;
    /**
     * The **`recordsAvailable`** read-only property of the BackgroundFetchRegistration interface returns true if there are requests and responses to be accessed. If this returns false, then match() and matchAll() can't be used.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BackgroundFetchRegistration/recordsAvailable)
     */
    readonly recordsAvailable: boolean;
    /**
     * The **`result`** read-only property of the BackgroundFetchRegistration interface returns a string indicating whether the background fetch was successful or failed.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BackgroundFetchRegistration/result)
     */
    readonly result: BackgroundFetchResult;
    /**
     * The **`uploadTotal`** read-only property of the BackgroundFetchRegistration interface returns the total number of bytes to be sent to the server.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BackgroundFetchRegistration/uploadTotal)
     */
    readonly uploadTotal: number;
    /**
     * The **`uploaded`** read-only property of the BackgroundFetchRegistration interface returns the size in bytes successfully sent, initially 0.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BackgroundFetchRegistration/uploaded)
     */
    readonly uploaded: number;
    /**
     * The **`abort()`** method of the BackgroundFetchRegistration interface aborts an active background fetch.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BackgroundFetchRegistration/abort)
     */
    abort(): Promise<boolean>;
    /**
     * The **`match()`** method of the BackgroundFetchRegistration interface returns the first matching BackgroundFetchRecord.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BackgroundFetchRegistration/match)
     */
    match(request: RequestInfo | URL, options?: CacheQueryOptions): Promise<BackgroundFetchRecord>;
    /**
     * The **`matchAll()`** method of the BackgroundFetchRegistration interface returns an array of matching BackgroundFetchRecord objects.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BackgroundFetchRegistration/matchAll)
     */
    matchAll(request?: RequestInfo | URL, options?: CacheQueryOptions): Promise<BackgroundFetchRecord[]>;
    addEventListener<K extends keyof BackgroundFetchRegistrationEventMap>(type: K, listener: (this: BackgroundFetchRegistration, ev: BackgroundFetchRegistrationEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof BackgroundFetchRegistrationEventMap>(type: K, listener: (this: BackgroundFetchRegistration, ev: BackgroundFetchRegistrationEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var BackgroundFetchRegistration: {
    prototype: BackgroundFetchRegistration;
    new(): BackgroundFetchRegistration;
};

interface ServiceWorkerRegistration {
    /**
     * The **`backgroundFetch`** read-only property of the ServiceWorkerRegistration interface returns a reference to a BackgroundFetchManager object, which can be used to initiate background fetch operations.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ServiceWorkerRegistration/backgroundFetch)
     */
    readonly backgroundFetch: BackgroundFetchManager;
}

type BackgroundFetchFailureReason = "" | "aborted" | "bad-status" | "download-total-exceeded" | "fetch-error" | "quota-exceeded";

type BackgroundFetchResult = "" | "failure" | "success";
