// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: window. Spec: battery-status

interface BatteryManagerEventMap {
    "chargingchange": Event;
    "chargingtimechange": Event;
    "dischargingtimechange": Event;
    "levelchange": Event;
}

/**
 * The **`BatteryManager`** interface of the Battery Status API provides information about the system's battery charge level. The navigator.getBattery() method returns a promise that resolves with a BatteryManager interface.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BatteryManager)
 */
interface BatteryManager extends EventTarget {
    /**
     * The **`charging`** read-only property of the BatteryManager interface is a Boolean value indicating whether or not the device's battery is currently being charged. When its value changes, the chargingchange event is fired.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BatteryManager/charging)
     */
    readonly charging: boolean;
    /**
     * The **`chargingTime`** read-only property of the BatteryManager interface indicates the amount of time, in seconds, that remain until the battery is fully charged, or 0 if the battery is already fully charged or the user agent is unable to report the battery status information. If the battery is currently discharging, its value is Infinity. When its value changes, the chargingtimechange event is fired.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BatteryManager/chargingTime)
     */
    readonly chargingTime: number;
    /**
     * The **`dischargingTime`** read-only property of the BatteryManager interface indicates the amount of time, in seconds, that remains until the battery is fully discharged, or Infinity if the battery is currently charging rather than discharging or the user agent is unable to report the battery status information. When its value changes, the dischargingtimechange event is fired.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BatteryManager/dischargingTime)
     */
    readonly dischargingTime: number;
    /**
     * The **`level`** read-only property of the BatteryManager interface indicates the current battery charge level as a value between 0.0 and 1.0. A value of 0.0 means the battery is empty and the system is about to be suspended. A value of 1.0 means the battery is full or the user agent is unable to report the battery status information. When its value changes, the levelchange event is fired.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BatteryManager/level)
     */
    readonly level: number;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/BatteryManager/chargingchange_event) */
    onchargingchange: ((this: BatteryManager, ev: Event) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/BatteryManager/chargingtimechange_event) */
    onchargingtimechange: ((this: BatteryManager, ev: Event) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/BatteryManager/dischargingtimechange_event) */
    ondischargingtimechange: ((this: BatteryManager, ev: Event) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/BatteryManager/levelchange_event) */
    onlevelchange: ((this: BatteryManager, ev: Event) => any) | null;
    addEventListener<K extends keyof BatteryManagerEventMap>(type: K, listener: (this: BatteryManager, ev: BatteryManagerEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof BatteryManagerEventMap>(type: K, listener: (this: BatteryManager, ev: BatteryManagerEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var BatteryManager: {
    prototype: BatteryManager;
    new(): BatteryManager;
};

interface Navigator {
    /**
     * The **`getBattery()`** method provides information about the system's battery. It returns a battery promise, which resolves with a BatteryManager object providing some properties to get the battery status also some events you can handle to monitor the battery status. This implements the Battery Status API; see that documentation for additional details, a guide to using the API, and sample code.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Navigator/getBattery)
     */
    getBattery(): Promise<BatteryManager>;
}
