// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: dom. Spec: capture-handle-identity

interface CaptureHandle {
    handle?: string;
    origin?: string;
}

interface CaptureHandleConfig {
    exposeOrigin?: boolean;
    handle?: string;
    permittedOrigins?: string[];
}

interface MediaDevices {
    setCaptureHandleConfig(config?: CaptureHandleConfig): void;
}

interface MediaStreamTrack {
    oncapturehandlechange: ((this: MediaStreamTrack, ev: Event) => any) | null;
    getCaptureHandle(): CaptureHandle | null;
}
