// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: dom. Spec: clipboard-apis

interface ClipboardChangeEventInit extends EventInit {
    changeId?: bigint;
    types?: string[];
}

/**
 * The **`ClipboardChangeEvent`** interface of the Clipboard API represents events fired whenever the contents of the system clipboard are changed.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ClipboardChangeEvent)
 */
interface ClipboardChangeEvent extends Event {
    /**
     * The **`changeId`** read-only property of the ClipboardChangeEvent interface returns an integer representing a unique identifier for this specific clipboard change operation.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ClipboardChangeEvent/changeId)
     */
    readonly changeId: bigint;
    /**
     * The **`types`** read-only property of the ClipboardChangeEvent interface returns an array of strings representing the mandatory MIME types available on the system clipboard when the ClipboardChangeEvent event was fired. Optional types and custom formats are not included to limit fingerprinting.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ClipboardChangeEvent/types)
     */
    readonly types: ReadonlyArray<string>;
}

declare var ClipboardChangeEvent: {
    prototype: ClipboardChangeEvent;
    new(type: string, eventInitDict?: ClipboardChangeEventInit): ClipboardChangeEvent;
};
