// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: webworker. Spec: compute-pressure

interface PressureObserverOptions {
    sampleInterval?: number;
}

/**
 * The **`PressureObserver`** interface is part of the Compute Pressure API and is used to observe the pressure changes of system resources such as the CPU.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PressureObserver)
 */
interface PressureObserver {
    /**
     * The **`disconnect()`** method of the PressureObserver interface stops the pressure observer callback from receiving pressure records from all sources.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PressureObserver/disconnect)
     */
    disconnect(): void;
    /**
     * The **`observe()`** method of the PressureObserver interface tells the pressure observer to start observing pressure changes. After this method is called, the observer will call its callback function when a pressure record for the specified source is observed.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PressureObserver/observe)
     */
    observe(source: PressureSource, options?: PressureObserverOptions): Promise<void>;
    /**
     * The **`takeRecords()`** method of the PressureObserver interface returns the current list of pressure records stored in the pressure observer, emptying it out.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PressureObserver/takeRecords)
     */
    takeRecords(): PressureRecord[];
    /**
     * The **`unobserve()`** method of the PressureObserver interface stops the pressure observer callback from receiving pressure records from the specified source.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PressureObserver/unobserve)
     */
    unobserve(source: PressureSource): void;
}

declare var PressureObserver: {
    prototype: PressureObserver;
    new(callback: PressureUpdateCallback): PressureObserver;
    /**
     * The static **`knownSources`** read-only property of the PressureObserver interface returns an array of the source values supported by the user agent in alphabetical order.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PressureObserver/knownSources_static)
     */
    readonly knownSources: ReadonlyArray<PressureSource>;
};

/**
 * The **`PressureRecord`** interface is part of the Compute Pressure API and describes the pressure trend of a source at a specific moment of transition.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PressureRecord)
 */
interface PressureRecord {
    /**
     * The read-only **`source`** property is a string indicating the origin source from which the record is coming.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PressureRecord/source)
     */
    readonly source: PressureSource;
    /**
     * The read-only **`state`** property is a string indicating the pressure state recorded.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PressureRecord/state)
     */
    readonly state: PressureState;
    /**
     * The read-only **`time`** property returns the timestamp recorded for a PressureRecord. It corresponds to the time the data was obtained from the system relative to the time origin of the global object in which the PressureObserver generated the notification.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PressureRecord/time)
     */
    readonly time: DOMHighResTimeStamp;
    /**
     * The **`toJSON()`** method is a serializer; it returns a JSON representation of the PressureRecord object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PressureRecord/toJSON)
     */
    toJSON(): any;
}

declare var PressureRecord: {
    prototype: PressureRecord;
    new(): PressureRecord;
};

interface PressureUpdateCallback {
    (changes: PressureRecord[], observer: PressureObserver): void;
}

type PressureSource = "cpu";

type PressureState = "critical" | "fair" | "nominal" | "serious";
