// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: webworker. Spec: content-index

interface ContentDescription {
    category?: ContentCategory;
    description: string;
    icons?: ImageResource[];
    id: string;
    title: string;
    url: string;
}

interface ContentIndexEventInit extends ExtendableEventInit {
    id: string;
}

/**
 * The **`ContentIndex`** interface of the Content Index API allows developers to register their offline enabled content with the browser.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ContentIndex)
 */
interface ContentIndex {
    /**
     * The **`add()`** method of the ContentIndex interface registers an item with the content index.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ContentIndex/add)
     */
    add(description: ContentDescription): Promise<void>;
    /**
     * The **`delete()`** method of the ContentIndex interface unregisters an item from the currently indexed content.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ContentIndex/delete)
     */
    delete(id: string): Promise<void>;
    /**
     * The **`getAll()`** method of the ContentIndex interface returns a Promise that resolves with an iterable list of content index entries.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ContentIndex/getAll)
     */
    getAll(): Promise<ContentDescription[]>;
}

declare var ContentIndex: {
    prototype: ContentIndex;
    new(): ContentIndex;
};

/**
 * The **`ContentIndexEvent`** interface of the content index defines the object used to represent the contentdelete event.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ContentIndexEvent)
 */
interface ContentIndexEvent extends ExtendableEvent {
    /**
     * The **`id`** read-only property of the ContentIndexEvent interface is a String which identifies the deleted content index via its id.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ContentIndexEvent/id)
     */
    readonly id: string;
}

declare var ContentIndexEvent: {
    prototype: ContentIndexEvent;
    new(type: string, init: ContentIndexEventInit): ContentIndexEvent;
};

interface ServiceWorkerGlobalScope {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/ServiceWorkerGlobalScope/contentdelete_event) */
    oncontentdelete: ((this: ServiceWorkerGlobalScope, ev: ContentIndexEvent) => any) | null;
}

interface ServiceWorkerRegistration {
    /**
     * The **`index`** read-only property of the ServiceWorkerRegistration interface returns a reference to the ContentIndex interface, which allows for indexing of offline content.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ServiceWorkerRegistration/index)
     */
    readonly index: ContentIndex;
}

type ContentCategory = "" | "article" | "audio" | "homepage" | "video";
