// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: dom. Spec: contact-picker

interface ContactInfo {
    address?: any[];
    email?: string[];
    icon?: Blob[];
    name?: string[];
    tel?: string[];
}

interface ContactsSelectOptions {
    multiple?: boolean;
}

/**
 * The **`ContactsManager`** interface of the Contact Picker API allows users to select entries from their contact list and share limited details of the selected entries with a website or application.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ContactsManager)
 */
interface ContactsManager {
    /**
     * The **`getProperties()`** method of the ContactsManager interface returns a Promise which resolves with an Array of strings indicating which contact properties are available.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ContactsManager/getProperties)
     */
    getProperties(): Promise<ContactProperty[]>;
    /**
     * The **`select()`** method of the ContactsManager interface returns a Promise which, when resolved, presents the user with a contact picker which allows them to select contact(s) they wish to share. This method requires a user gesture for the Promise to resolve.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ContactsManager/select)
     */
    select(properties: ContactProperty[], options?: ContactsSelectOptions): Promise<ContactInfo[]>;
}

interface ContactsManager {
    /**
     * The **`select()`** method of the ContactsManager interface returns a Promise which, when resolved, presents the user with a contact picker which allows them to select contact(s) they wish to share. This method requires a user gesture for the Promise to resolve.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ContactsManager/select)
     */
    select(properties: Iterable<ContactProperty>, options?: ContactsSelectOptions): Promise<ContactInfo[]>;
}

declare var ContactsManager: {
    prototype: ContactsManager;
    new(): ContactsManager;
};

interface Navigator {
    /**
     * The **`contacts`** read-only property of the Navigator interface returns a ContactsManager interface which allows users to select entries from their contact list and share limited details of the selected entries with a website or application.
     * Available only in secure contexts.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Navigator/contacts)
     */
    readonly contacts: ContactsManager;
}

type ContactProperty = "address" | "email" | "icon" | "name" | "tel";
