// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: dom. Spec: content-index

interface ContentDescription {
    category?: ContentCategory;
    description: string;
    icons?: ImageResource[];
    id: string;
    title: string;
    url: string;
}

/**
 * The **`ContentIndex`** interface of the Content Index API allows developers to register their offline enabled content with the browser.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ContentIndex)
 */
interface ContentIndex {
    /**
     * The **`add()`** method of the ContentIndex interface registers an item with the content index.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ContentIndex/add)
     */
    add(description: ContentDescription): Promise<void>;
    /**
     * The **`delete()`** method of the ContentIndex interface unregisters an item from the currently indexed content.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ContentIndex/delete)
     */
    delete(id: string): Promise<void>;
    /**
     * The **`getAll()`** method of the ContentIndex interface returns a Promise that resolves with an iterable list of content index entries.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ContentIndex/getAll)
     */
    getAll(): Promise<ContentDescription[]>;
}

declare var ContentIndex: {
    prototype: ContentIndex;
    new(): ContentIndex;
};

interface ServiceWorkerRegistration {
    /**
     * The **`index`** read-only property of the ServiceWorkerRegistration interface returns a reference to the ContentIndex interface, which allows for indexing of offline content.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ServiceWorkerRegistration/index)
     */
    readonly index: ContentIndex;
}

type ContentCategory = "" | "article" | "audio" | "homepage" | "video";
