// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: dom. Spec: crash-reporting

/**
 * The **`CrashReportContext`** interface of the Reporting API provides methods enabling arbitrary data to be recorded for the current top-level browsing context, which is then added to a CrashReport and sent to a reporting endpoint when a browser crash occurs.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CrashReportContext)
 */
interface CrashReportContext {
    /**
     * The **`delete()`** method of the CrashReportContext interface deletes a previously-stored key-value pair.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CrashReportContext/delete)
     */
    delete(key: string): void;
    /**
     * The **`initialize()`** method of the CrashReportContext interface initializes a portion of memory to be used for storing crash report data specified by set(). This must be called before any other method is invoked on the object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CrashReportContext/initialize)
     */
    initialize(length: number): Promise<void>;
    /**
     * The **`set()`** method of the CrashReportContext interface stores a key-value pair in the memory initialized by initialize().
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CrashReportContext/set)
     */
    set(key: string, value: string): void;
}

declare var CrashReportContext: {
    prototype: CrashReportContext;
    new(): CrashReportContext;
};

interface Window {
    /**
     * The **`crashReport`** read-only property of the Window interface returns a CrashReportContext object that enables arbitrary data to be recorded for the current top-level browsing context. The data is then included in CrashReport objects that are sent to a reporting endpoint when a browser crash occurs.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Window/crashReport)
     */
    readonly crashReport: CrashReportContext;
}
