// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Spec: csp-embedded-enforcement

interface HTMLIFrameElement {
    /**
     * The **`csp`** property of the HTMLIFrameElement interface specifies the Content Security Policy that an embedded document must agree to enforce upon itself.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLIFrameElement/csp)
     */
    csp: string;
}
