// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Spec: css-transitions-2

interface TransitionEvent {
    readonly animation: CSSTransition | null;
}
