// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: dom. Spec: css-transitions-2

interface TransitionEvent {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/TransitionEvent/animation) */
    readonly animation: CSSTransition | null;
}
