// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Spec: css-conditional-5

interface CSSContainerCondition {
    name: string;
    query: string;
}

interface CSSContainerRule {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSSContainerRule/conditions) */
    readonly conditions: ReadonlyArray<CSSContainerCondition>;
}
