// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: dom. Spec: css-fonts

interface CSSFontFeatureValuesMap extends Map<string, Iterable<number>> {
        forEach(callbackfn: (value: number[], key: string, parent: CSSFontFeatureValuesMap) => void, thisArg?: any): void;
}

declare var CSSFontFeatureValuesMap: {
    prototype: CSSFontFeatureValuesMap;
    new(): CSSFontFeatureValuesMap;
};

interface CSSFontFeatureValuesRule {
    /**
     * The read-only **`annotation`** property of the CSSFontFeatureValuesRule interface contains a CSSFontFeatureValuesMap object representing the user-defined-ident and feature index for a variable font which supports annotation().
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSSFontFeatureValuesRule/annotation)
     */
    readonly annotation: CSSFontFeatureValuesMap;
    /**
     * The read-only **`characterVariant`** property of the CSSFontFeatureValuesRule interface contains a CSSFontFeatureValuesMap object representing the user-defined-ident and feature index for a variable font which supports character-variant().
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSSFontFeatureValuesRule/characterVariant)
     */
    readonly characterVariant: CSSFontFeatureValuesMap;
    /**
     * The read-only **`ornaments`** property of the CSSFontFeatureValuesRule interface contains a CSSFontFeatureValuesMap object representing the user-defined-ident and feature index for a variable font which supports ornaments().
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSSFontFeatureValuesRule/ornaments)
     */
    readonly ornaments: CSSFontFeatureValuesMap;
    /**
     * The read-only **`styleset`** property of the CSSFontFeatureValuesRule interface contains a CSSFontFeatureValuesMap object representing the user-defined-ident and feature index for a variable font which supports styleset().
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSSFontFeatureValuesRule/styleset)
     */
    readonly styleset: CSSFontFeatureValuesMap;
    /**
     * The read-only **`stylistic`** property of the CSSFontFeatureValuesRule interface contains a CSSFontFeatureValuesMap object representing the user-defined-ident and feature index for a variable font which supports stylistic().
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSSFontFeatureValuesRule/stylistic)
     */
    readonly stylistic: CSSFontFeatureValuesMap;
    /**
     * The read-only **`swash`** property of the CSSFontFeatureValuesRule interface contains a CSSFontFeatureValuesMap object representing the developer-provided name and feature index for a variable font which supports swash().
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSSFontFeatureValuesRule/swash)
     */
    readonly swash: CSSFontFeatureValuesMap;
}
