// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: dom. Spec: css-animations-2

interface AnimationEvent {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/AnimationEvent/animation) */
    readonly animation: CSSAnimation | null;
}
