// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: dom. Spec: css-pseudo

/**
 * The **`CSSPseudoElement`** interface represents a pseudo-element that may be the target of an event or animated using the Web Animations API. Instances of this interface may be obtained by calling Element.pseudo().
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSSPseudoElement)
 */
interface CSSPseudoElement {
    /**
     * The **`element`** read-only property of the CSSPseudoElement interface returns a reference to the originating element of the pseudo-element, in other words its parent element.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSSPseudoElement/element)
     */
    readonly element: Element;
    readonly parent: Element | CSSPseudoElement;
    /**
     * The **`type`** read-only property of the CSSPseudoElement interface returns the type of the pseudo-element as a string, represented in the form of a CSS selector.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSSPseudoElement/type)
     */
    readonly type: string;
    pseudo(type: string): CSSPseudoElement | null;
}

declare var CSSPseudoElement: {
    prototype: CSSPseudoElement;
    new(): CSSPseudoElement;
};

interface Element {
    pseudo(type: string): CSSPseudoElement | null;
}
