// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: window. Spec: css-viewport

/**
 * The **`Viewport`** interface of the Viewport Segments API represents the device's viewport.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Viewport)
 */
interface Viewport {
    /**
     * The **`segments`** read-only property of the Viewport interface returns an array of DOMRect objects representing the position and dimensions of each viewport segment within the overall display.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Viewport/segments)
     */
    readonly segments: ReadonlyArray<DOMRect> | null;
}

declare var Viewport: {
    prototype: Viewport;
    new(): Viewport;
};

interface Window {
    /**
     * The **`viewport`** read-only property of the Window interface returns a Viewport object instance, which provides information about the current state of the device's viewport.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Window/viewport)
     */
    readonly viewport: Viewport;
}
