// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: dom. Spec: device-memory

/** Available only in secure contexts. */
interface NavigatorDeviceMemory {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/Navigator/deviceMemory) */
    readonly deviceMemory: number;
}
