// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Spec: device-memory

/** Available only in secure contexts. */
interface NavigatorDeviceMemory {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/Navigator/deviceMemory) */
    readonly deviceMemory: number;
}
