// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: dom. Spec: device-posture

interface DevicePostureEventMap {
    "change": Event;
}

/**
 * The **`DevicePosture`** interface of the Device Posture API represents the device's posture, that is, whether the viewport is in a flat or folded state.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/DevicePosture)
 */
interface DevicePosture extends EventTarget {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/DevicePosture/change_event) */
    onchange: ((this: DevicePosture, ev: Event) => any) | null;
    /**
     * The **`type`** read-only property of the DevicePosture interface returns the device's current posture.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/DevicePosture/type)
     */
    readonly type: DevicePostureType;
    addEventListener<K extends keyof DevicePostureEventMap>(type: K, listener: (this: DevicePosture, ev: DevicePostureEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof DevicePostureEventMap>(type: K, listener: (this: DevicePosture, ev: DevicePostureEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var DevicePosture: {
    prototype: DevicePosture;
    new(): DevicePosture;
};

interface Navigator {
    /**
     * The **`Navigator.devicePosture`** read-only property returns the browser's DevicePosture object, which allows developers to query the device's current posture (that is, whether the viewport is in a flat or folded state) and run code in response to posture changes.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Navigator/devicePosture)
     */
    readonly devicePosture: DevicePosture;
}

type DevicePostureType = "continuous" | "folded";
