// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: window. Spec: digital-goods

interface Window {
    /** Available only in secure contexts. */
    getDigitalGoodsService(serviceProvider: string): Promise<any>;
}

/** Available only in secure contexts. */
declare function getDigitalGoodsService(serviceProvider: string): Promise<any>;
