// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: dom. Spec: dom

interface DocumentEventMap {
    "freeze": Event;
    "prerenderingchange": Event;
    "resume": Event;
}

interface Document {
    createEvent(eventInterface: "BeforeInstallPromptEvent"): BeforeInstallPromptEvent;
    createEvent(eventInterface: "BufferedChangeEvent"): BufferedChangeEvent;
    createEvent(eventInterface: "CharacterBoundsUpdateEvent"): CharacterBoundsUpdateEvent;
    createEvent(eventInterface: "ClipboardChangeEvent"): ClipboardChangeEvent;
    createEvent(eventInterface: "HIDConnectionEvent"): HIDConnectionEvent;
    createEvent(eventInterface: "HIDInputReportEvent"): HIDInputReportEvent;
    createEvent(eventInterface: "NDEFReadingEvent"): NDEFReadingEvent;
    createEvent(eventInterface: "PresentationConnectionAvailableEvent"): PresentationConnectionAvailableEvent;
    createEvent(eventInterface: "PresentationConnectionCloseEvent"): PresentationConnectionCloseEvent;
    createEvent(eventInterface: "SensorErrorEvent"): SensorErrorEvent;
    createEvent(eventInterface: "SnapEvent"): SnapEvent;
    createEvent(eventInterface: "TextFormatUpdateEvent"): TextFormatUpdateEvent;
    createEvent(eventInterface: "TextUpdateEvent"): TextUpdateEvent;
    createEvent(eventInterface: "TimeEvent"): TimeEvent;
    createEvent(eventInterface: "USBConnectionEvent"): USBConnectionEvent;
    createEvent(eventInterface: "WindowControlsOverlayGeometryChangeEvent"): WindowControlsOverlayGeometryChangeEvent;
    createEvent(eventInterface: "XRInputSourceEvent"): XRInputSourceEvent;
    createEvent(eventInterface: "XRInputSourcesChangeEvent"): XRInputSourcesChangeEvent;
    createEvent(eventInterface: "XRLayerEvent"): XRLayerEvent;
    createEvent(eventInterface: "XRReferenceSpaceEvent"): XRReferenceSpaceEvent;
    createEvent(eventInterface: "XRSessionEvent"): XRSessionEvent;
    createEvent(eventInterface: "XRVisibilityMaskChangeEvent"): XRVisibilityMaskChangeEvent;
}
