// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: dom. Spec: edit-context

interface CharacterBoundsUpdateEventInit extends EventInit {
    rangeEnd?: number;
    rangeStart?: number;
}

interface EditContextInit {
    selectionEnd?: number;
    selectionStart?: number;
    text?: string;
}

interface TextFormatInit {
    rangeEnd?: number;
    rangeStart?: number;
    underlineStyle?: UnderlineStyle;
    underlineThickness?: UnderlineThickness;
}

interface TextFormatUpdateEventInit extends EventInit {
    textFormats?: TextFormat[];
}

interface TextUpdateEventInit extends EventInit {
    selectionEnd?: number;
    selectionStart?: number;
    text?: string;
    updateRangeEnd?: number;
    updateRangeStart?: number;
}

/**
 * The **`CharacterBoundsUpdateEvent`** interface is a DOM event that represents a request from the operating system to know the bounds of certain characters within an editable region that's attached to an EditContext instance.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CharacterBoundsUpdateEvent)
 */
interface CharacterBoundsUpdateEvent extends Event {
    /**
     * The **`CharacterBoundsUpdateEvent.rangeEnd`** read-only property represents the offset of the last character within the editable text region for which the operating system needs the bounds.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CharacterBoundsUpdateEvent/rangeEnd)
     */
    readonly rangeEnd: number;
    /**
     * The **`CharacterBoundsUpdateEvent.rangeStart`** read-only property represents the offset of the first character within the editable text region for which the operating system needs the bounds.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CharacterBoundsUpdateEvent/rangeStart)
     */
    readonly rangeStart: number;
}

declare var CharacterBoundsUpdateEvent: {
    prototype: CharacterBoundsUpdateEvent;
    new(type: string, options?: CharacterBoundsUpdateEventInit): CharacterBoundsUpdateEvent;
};

interface EditContextEventMap {
    "characterboundsupdate": CharacterBoundsUpdateEvent;
    "compositionend": CompositionEvent;
    "compositionstart": CompositionEvent;
    "textformatupdate": TextFormatUpdateEvent;
    "textupdate": TextUpdateEvent;
}

/**
 * The **`EditContext`** interface represents the text edit context of an element that was made editable by using the EditContext API.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/EditContext)
 */
interface EditContext extends EventTarget {
    /**
     * The **`characterBoundsRangeStart`** read-only property of the EditContext interface indicates the index of the character, within the editable text content, that corresponds to the first item in the characterBounds array.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/EditContext/characterBoundsRangeStart)
     */
    readonly characterBoundsRangeStart: number;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/EditContext/characterboundsupdate_event) */
    oncharacterboundsupdate: ((this: EditContext, ev: CharacterBoundsUpdateEvent) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/EditContext/compositionend_event) */
    oncompositionend: ((this: EditContext, ev: CompositionEvent) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/EditContext/compositionstart_event) */
    oncompositionstart: ((this: EditContext, ev: CompositionEvent) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/EditContext/textformatupdate_event) */
    ontextformatupdate: ((this: EditContext, ev: TextFormatUpdateEvent) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/EditContext/textupdate_event) */
    ontextupdate: ((this: EditContext, ev: TextUpdateEvent) => any) | null;
    /**
     * The **`selectionEnd`** read-only property of the EditContext refers to the offset, within the editable text content, of the end of the current selection.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/EditContext/selectionEnd)
     */
    readonly selectionEnd: number;
    /**
     * The **`selectionStart`** read-only property of the EditContext refers to the offset, within the editable text content, of the start of the current selection.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/EditContext/selectionStart)
     */
    readonly selectionStart: number;
    /**
     * The **`text`** read-only property of the EditContext interface represents the editable content of the element.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/EditContext/text)
     */
    readonly text: string;
    /**
     * The **`attachedElements()`** method of the EditContext interface returns an Array that contains only one item. This item is the element that's associated with the EditContext object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/EditContext/attachedElements)
     */
    attachedElements(): HTMLElement[];
    /**
     * The **`characterBounds()`** method of the EditContext interface returns an Array containing the list of bounding rectangles for the characters in the EditContext object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/EditContext/characterBounds)
     */
    characterBounds(): DOMRect[];
    /**
     * The **`EditContext.updateCharacterBounds()`** method of the EditContext interface should be called as response to a characterboundsupdate event to inform the operating system about the position and size of the characters in the EditContext object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/EditContext/updateCharacterBounds)
     */
    updateCharacterBounds(rangeStart: number, characterBounds: DOMRect[]): void;
    /**
     * The **`EditContext.updateControlBounds()`** method of the EditContext interface is used to inform the operating system about the position and size of the editable text region of the EditContext object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/EditContext/updateControlBounds)
     */
    updateControlBounds(controlBounds: DOMRect): void;
    /**
     * The **`updateSelection()`** method of the EditContext interface updates the internal state of the selection within the editable text context. This method is used to update the selection state when the user interacts with the text rendering in the EditContext's associated element, such as by clicking or dragging the mouse, or by using the keyboard.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/EditContext/updateSelection)
     */
    updateSelection(start: number, end: number): void;
    /**
     * The **`EditContext.updateSelectionBounds()`** method of the EditContext interface is used to inform the operating system about the bounds of the text selection within the editable region that's associated with the EditContext object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/EditContext/updateSelectionBounds)
     */
    updateSelectionBounds(selectionBounds: DOMRect): void;
    /**
     * The **`updateText()`** method of the EditContext interface updates the internal text content of an EditContext object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/EditContext/updateText)
     */
    updateText(rangeStart: number, rangeEnd: number, text: string): void;
    addEventListener<K extends keyof EditContextEventMap>(type: K, listener: (this: EditContext, ev: EditContextEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof EditContextEventMap>(type: K, listener: (this: EditContext, ev: EditContextEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

interface EditContext {
    /**
     * The **`EditContext.updateCharacterBounds()`** method of the EditContext interface should be called as response to a characterboundsupdate event to inform the operating system about the position and size of the characters in the EditContext object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/EditContext/updateCharacterBounds)
     */
    updateCharacterBounds(rangeStart: number, characterBounds: Iterable<DOMRect>): void;
}

declare var EditContext: {
    prototype: EditContext;
    new(options?: EditContextInit): EditContext;
};

interface HTMLElement {
    /**
     * The **`editContext`** property of the HTMLElement interface gets and sets an element's associated EditContext object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLElement/editContext)
     */
    editContext: EditContext | null;
}

/**
 * The **`TextFormat`** interface represents specific formatting that should be applied to a range of text in an editable text region that's attached to an EditContext instance. The text formatting is requested by the Input Method Editor (IME) window that the user is composing text with.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/TextFormat)
 */
interface TextFormat {
    /**
     * The **`rangeEnd`** property of the TextFormat interface indicates the end position of the text range that needs to be formatted with the given text format.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/TextFormat/rangeEnd)
     */
    readonly rangeEnd: number;
    /**
     * The **`rangeStart`** property of the TextFormat interface indicates the start position of the text range that needs to be formatted with the given text format.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/TextFormat/rangeStart)
     */
    readonly rangeStart: number;
    /**
     * The **`underlineStyle`** property of the TextFormat interface indicates the style of the underline that needs to be applied to the text range that is being formatted.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/TextFormat/underlineStyle)
     */
    readonly underlineStyle: UnderlineStyle;
    /**
     * The **`underlineThickness`** property of the TextFormat interface indicates the thickness of the underline that needs to be applied to the text range that is being formatted.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/TextFormat/underlineThickness)
     */
    readonly underlineThickness: UnderlineThickness;
}

declare var TextFormat: {
    prototype: TextFormat;
    new(options?: TextFormatInit): TextFormat;
};

/**
 * The **`TextFormatUpdateEvent`** interface is a DOM event that represents a list of text formats that an Input Method Editor (IME) window wants to apply to the text being composed in an editable region that's attached to an EditContext instance.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/TextFormatUpdateEvent)
 */
interface TextFormatUpdateEvent extends Event {
    /**
     * The **`getTextFormats()`** method of the TextFormatUpdateEvent interface returns an Array of TextFormat objects that represent the formats that an Input Method Editor (IME) window wants to apply to the text being composed.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/TextFormatUpdateEvent/getTextFormats)
     */
    getTextFormats(): TextFormat[];
}

declare var TextFormatUpdateEvent: {
    prototype: TextFormatUpdateEvent;
    new(type: string, options?: TextFormatUpdateEventInit): TextFormatUpdateEvent;
};

/**
 * The **`TextUpdateEvent`** interface is a DOM event that represents a text or selection update in an editable text region that's attached to an EditContext instance.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/TextUpdateEvent)
 */
interface TextUpdateEvent extends Event {
    /**
     * The **`TextUpdateEvent.selectionEnd`** read-only property indicates the position of the end of the selection (or caret) within the text content of the editable region attached to the EditContext object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/TextUpdateEvent/selectionEnd)
     */
    readonly selectionEnd: number;
    /**
     * The **`TextUpdateEvent.selectionStart`** read-only property indicates the position of the start of the selection (or caret) within the text content of the editable region attached to the EditContext object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/TextUpdateEvent/selectionStart)
     */
    readonly selectionStart: number;
    /**
     * The **`TextUpdateEvent.text`** read-only property contains the text that was inserted within the updated range of an EditContext's textupdate event.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/TextUpdateEvent/text)
     */
    readonly text: string;
    /**
     * The **`TextUpdateEvent.updateRangeEnd`** read-only property indicates the end position of the text range that is being replaced in the EditContext object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/TextUpdateEvent/updateRangeEnd)
     */
    readonly updateRangeEnd: number;
    /**
     * The **`TextUpdateEvent.updateRangeStart`** read-only property indicates the start position of the text range that is being replaced in the EditContext object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/TextUpdateEvent/updateRangeStart)
     */
    readonly updateRangeStart: number;
}

declare var TextUpdateEvent: {
    prototype: TextUpdateEvent;
    new(type: string, options?: TextUpdateEventInit): TextUpdateEvent;
};

type UnderlineStyle = "dashed" | "dotted" | "none" | "solid" | "wavy";

type UnderlineThickness = "none" | "thick" | "thin";
