// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: dom. Spec: element-timing

/// <reference path="./performance-timeline.d.ts" />

interface Element {
    /**
     * The **`elementTiming`** property of the Element interface identifies elements for observation in the PerformanceElementTiming API. The elementTiming property reflects the value of the elementtiming attribute.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/elementTiming)
     */
    elementTiming: string;
}

/**
 * The **`PerformanceElementTiming`** interface contains render timing information for image and text node elements the developer annotated with an elementtiming attribute for observation.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PerformanceElementTiming)
 */
interface PerformanceElementTiming extends PerformanceEntry, PaintTimingMixin {
    /**
     * The **`element`** read-only property of the PerformanceElementTiming interface returns an Element which is a pointer to the observed element.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PerformanceElementTiming/element)
     */
    readonly element: Element | null;
    /**
     * The **`id`** read-only property of the PerformanceElementTiming interface returns the id of the associated element.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PerformanceElementTiming/id)
     */
    readonly id: string;
    /**
     * The **`identifier`** read-only property of the PerformanceElementTiming interface returns the value of the elementtiming attribute on the element.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PerformanceElementTiming/identifier)
     */
    readonly identifier: string;
    /**
     * The **`intersectionRect`** read-only property of the PerformanceElementTiming interface returns the rectangle of the element within the viewport.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PerformanceElementTiming/intersectionRect)
     */
    readonly intersectionRect: DOMRectReadOnly;
    /**
     * The **`loadTime`** read-only property of the PerformanceElementTiming interface always returns 0 for text. For images it returns the time which is the latest between the time the image resource is loaded and the time it is attached to the element.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PerformanceElementTiming/loadTime)
     */
    readonly loadTime: DOMHighResTimeStamp;
    /**
     * The **`naturalHeight`** read-only property of the PerformanceElementTiming interface returns the intrinsic height of the image element.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PerformanceElementTiming/naturalHeight)
     */
    readonly naturalHeight: number;
    /**
     * The **`naturalWidth`** read-only property of the PerformanceElementTiming interface returns the intrinsic width of the image element.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PerformanceElementTiming/naturalWidth)
     */
    readonly naturalWidth: number;
    /**
     * The **`renderTime`** read-only property of the PerformanceElementTiming interface returns the render time of the associated element.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PerformanceElementTiming/renderTime)
     */
    readonly renderTime: DOMHighResTimeStamp;
    /**
     * The **`url`** read-only property of the PerformanceElementTiming interface returns the initial URL of the resource request when the element is an image.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PerformanceElementTiming/url)
     */
    readonly url: string;
    /**
     * The **`toJSON()`** method of the PerformanceElementTiming interface is a serializer; it returns a JSON representation of the PerformanceElementTiming object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PerformanceElementTiming/toJSON)
     */
    toJSON(): any;
}

declare var PerformanceElementTiming: {
    prototype: PerformanceElementTiming;
    new(): PerformanceElementTiming;
};

interface PerformanceEntryTypeMap {
    "element": PerformanceElementTiming;
}
