// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: window. Spec: EXT_disjoint_timer_query

/**
 * The **`EXT_disjoint_timer_query`** extension is part of the WebGL API and provides a way to measure the duration of a set of GL commands, without stalling the rendering pipeline.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/EXT_disjoint_timer_query)
 */
interface EXT_disjoint_timer_query {
    /**
     * The **`EXT_disjoint_timer_query.beginQueryEXT()`** method of the WebGL API starts a timer query.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/EXT_disjoint_timer_query/beginQueryEXT)
     */
    beginQueryEXT(target: GLenum, query: WebGLTimerQueryEXT): void;
    /**
     * The **`EXT_disjoint_timer_query.createQueryEXT()`** method of the WebGL API creates and initializes WebGLQuery objects, which track the time needed to fully complete a set of GL commands.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/EXT_disjoint_timer_query/createQueryEXT)
     */
    createQueryEXT(): WebGLTimerQueryEXT;
    /**
     * The **`EXT_disjoint_timer_query.deleteQueryEXT()`** method of the WebGL API deletes a given WebGLQuery object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/EXT_disjoint_timer_query/deleteQueryEXT)
     */
    deleteQueryEXT(query: WebGLTimerQueryEXT | null): void;
    /**
     * The **`EXT_disjoint_timer_query.endQueryEXT()`** method of the WebGL API ends a timer query.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/EXT_disjoint_timer_query/endQueryEXT)
     */
    endQueryEXT(target: GLenum): void;
    /**
     * The **`EXT_disjoint_timer_query.getQueryEXT()`** method of the WebGL API returns information about a query target.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/EXT_disjoint_timer_query/getQueryEXT)
     */
    getQueryEXT(target: GLenum, pname: GLenum): any;
    /**
     * The **`EXT_disjoint_timer_query.getQueryObjectEXT()`** method of the WebGL API returns the state of a query object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/EXT_disjoint_timer_query/getQueryObjectEXT)
     */
    getQueryObjectEXT(query: WebGLTimerQueryEXT, pname: GLenum): any;
    /**
     * The **`EXT_disjoint_timer_query.isQueryEXT()`** method of the WebGL API returns true if the passed object is a WebGLQuery object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/EXT_disjoint_timer_query/isQueryEXT)
     */
    isQueryEXT(query: WebGLTimerQueryEXT | null): boolean;
    /**
     * The **`EXT_disjoint_timer_query.queryCounterEXT()`** method of the WebGL API records the current time into the corresponding query object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/EXT_disjoint_timer_query/queryCounterEXT)
     */
    queryCounterEXT(query: WebGLTimerQueryEXT, target: GLenum): void;
    readonly QUERY_COUNTER_BITS_EXT: 0x8864;
    readonly CURRENT_QUERY_EXT: 0x8865;
    readonly QUERY_RESULT_EXT: 0x8866;
    readonly QUERY_RESULT_AVAILABLE_EXT: 0x8867;
    readonly TIME_ELAPSED_EXT: 0x88BF;
    readonly TIMESTAMP_EXT: 0x8E28;
    readonly GPU_DISJOINT_EXT: 0x8FBB;
}

interface WebGLTimerQueryEXT extends WebGLObject {
}
