// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: dom. Spec: fedcm

interface IdentityCredentialDisconnectOptions extends IdentityProviderConfig {
    accountHint: string;
}

interface IdentityCredentialErrorInit {
    error?: string;
    url?: string;
}

interface IdentityProviderConfig {
    clientId: string;
    configURL: string;
}

interface IdentityResolveOptions {
    accountId?: string;
}

interface IdentityUserInfo {
    email?: string;
    givenName?: string;
    name?: string;
    picture?: string;
}

/**
 * The **`IdentityCredential`** interface of the Federated Credential Management API (FedCM) represents a user identity credential arising from a successful federated sign-in.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/IdentityCredential)
 */
interface IdentityCredential extends Credential {
    /**
     * The **`configURL`** read-only property of the IdentityCredential interface returns a string specifying the config file URL of the identity provider (IdP) used for sign-in.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/IdentityCredential/configURL)
     */
    readonly configURL: string;
    /**
     * The **`isAutoSelected`** read-only property of the IdentityCredential interface indicates whether the federated sign-in flow was carried out using auto-reauthentication (i.e., without user mediation) or not.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/IdentityCredential/isAutoSelected)
     */
    readonly isAutoSelected: boolean;
    /**
     * The **`token`** read-only property of the IdentityCredential interface returns the token used to validate the associated sign-in.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/IdentityCredential/token)
     */
    readonly token: any;
}

declare var IdentityCredential: {
    prototype: IdentityCredential;
    new(): IdentityCredential;
    /**
     * The **`disconnect()`** static method of the IdentityCredential interface disconnects a specified federated sign-in account from the IdP used to obtain the credential.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/IdentityCredential/disconnect_static)
     */
    disconnect(options: IdentityCredentialDisconnectOptions): Promise<void>;
};

/**
 * The **`IdentityCredentialError`** interface of the FedCM API describes an authentication error indicating that the user agent did not receive an identity assertion after the user has requested to use a federated account. This can happen if the client is unauthorized or if the server is temporarily unavailable, for example.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/IdentityCredentialError)
 */
interface IdentityCredentialError extends DOMException {
    /**
     * The **`error`** read-only property of the IdentityCredentialError interface is either one of the values listed in the OAuth 2.0 specified error list or an arbitrary string giving more information about the error.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/IdentityCredentialError/error)
     */
    readonly error: string;
    /**
     * The **`url`** read-only property of the IdentityCredentialError interface is the URL pointing to human-readable information about the error to display to users, such as how to fix the error or contact customer service.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/IdentityCredentialError/url)
     */
    readonly url: string;
}

declare var IdentityCredentialError: {
    prototype: IdentityCredentialError;
    new(message?: string, options?: IdentityCredentialErrorInit): IdentityCredentialError;
};

/**
 * The **`IdentityProvider`** interface of the Federated Credential Management (FedCM) API represents an IdP and provides access to related information and functionality.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/IdentityProvider)
 */
interface IdentityProvider {
}

declare var IdentityProvider: {
    prototype: IdentityProvider;
    new(): IdentityProvider;
    /**
     * The **`close()`** static method of the IdentityProvider interface provides a manual signal to the browser that an IdP sign-in flow is finished.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/IdentityProvider/close_static)
     */
    close(): void;
    /**
     * The **`getUserInfo()`** static method of the IdentityProvider interface returns information about a user that has signed in, which can be used to provide a personalized welcome message and sign-in button. This method has to be called from within an IdP origin <iframe> so that relying party (RP) scripts cannot access the data. This must occur after a user has been signed in to a RP site.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/IdentityProvider/getUserInfo_static)
     */
    getUserInfo(config: IdentityProviderConfig): Promise<IdentityUserInfo[]>;
    resolve(token: any, options?: IdentityResolveOptions): Promise<void>;
};
