// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Spec: fetch

interface DeferredRequestInit extends RequestInit {
    activateAfter?: DOMHighResTimeStamp;
}

/**
 * The **`FetchLaterResult`** interface of the Fetch API is returned by the Window.fetchLater() method after a deferred fetch has been created.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/FetchLaterResult)
 */
interface FetchLaterResult {
    /**
     * The **`activated`** read-only property of the FetchLaterResult interface returns a boolean specifying whether the deferred fetch has been sent.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/FetchLaterResult/activated)
     */
    readonly activated: boolean;
}

declare var FetchLaterResult: {
    prototype: FetchLaterResult;
    new(): FetchLaterResult;
};

interface Request {
    /**
     * The **`duplex`** read-only property of the Request interface returns the duplex mode of the request, which determines whether the browser must send the entire request before processing the response.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Request/duplex)
     */
    readonly duplex: RequestDuplex;
    /**
     * The **`isHistoryNavigation`** read-only property of the Request interface is a boolean indicating whether the request is a history navigation.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Request/isHistoryNavigation)
     */
    readonly isHistoryNavigation: boolean;
}

interface Window {
    /**
     * The **`fetchLater()`** method of the Window interface creates a deferred fetch.
     * Available only in secure contexts.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Window/fetchLater)
     */
    fetchLater(input: RequestInfo | URL, init?: DeferredRequestInit): FetchLaterResult;
}

/**
 * The **`fetchLater()`** method of the Window interface creates a deferred fetch.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Window/fetchLater)
 */
declare function fetchLater(input: RequestInfo | URL, init?: DeferredRequestInit): FetchLaterResult;

type RequestDuplex = "half";
