// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: worker. Spec: fetch

interface Request {
    /**
     * The **`duplex`** read-only property of the Request interface returns the duplex mode of the request, which determines whether the browser must send the entire request before processing the response.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Request/duplex)
     */
    readonly duplex: RequestDuplex;
    /**
     * The **`isHistoryNavigation`** read-only property of the Request interface is a boolean indicating whether the request is a history navigation.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Request/isHistoryNavigation)
     */
    readonly isHistoryNavigation: boolean;
}

type RequestDuplex = "half";
