// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: webworker. Spec: file-system-access

interface FileSystemHandlePermissionDescriptor {
    mode?: FileSystemPermissionMode;
}

interface FileSystemHandle {
    /**
     * The **`queryPermission()`** method of the FileSystemHandle interface queries the current permission state of the current handle.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/FileSystemHandle/queryPermission)
     */
    queryPermission(descriptor?: FileSystemHandlePermissionDescriptor): Promise<PermissionState>;
    /**
     * The **`requestPermission()`** method of the FileSystemHandle interface requests read or readwrite permissions for the file handle.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/FileSystemHandle/requestPermission)
     */
    requestPermission(descriptor?: FileSystemHandlePermissionDescriptor): Promise<PermissionState>;
}

type FileSystemPermissionMode = "read" | "readwrite";
