// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: window. Spec: file-system-access

interface DirectoryPickerOptions {
    id?: string;
    mode?: FileSystemPermissionMode;
    startIn?: StartInDirectory;
}

interface FilePickerAcceptType {
    accept?: Record<string, string | string[]>;
    description?: string;
}

interface FilePickerOptions {
    excludeAcceptAllOption?: boolean;
    id?: string;
    startIn?: StartInDirectory;
    types?: FilePickerAcceptType[];
}

interface FileSystemHandlePermissionDescriptor {
    mode?: FileSystemPermissionMode;
}

interface OpenFilePickerOptions extends FilePickerOptions {
    multiple?: boolean;
}

interface SaveFilePickerOptions extends FilePickerOptions {
    suggestedName?: string | null;
}

interface DataTransferItem {
    /**
     * The **`getAsFileSystemHandle()`** method of the DataTransferItem interface returns a Promise that fulfills with a FileSystemFileHandle if the dragged item is a file, or fulfills with a FileSystemDirectoryHandle if the dragged item is a directory.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/DataTransferItem/getAsFileSystemHandle)
     */
    getAsFileSystemHandle(): Promise<FileSystemHandle | null>;
}

interface FileSystemHandle {
    /**
     * The **`queryPermission()`** method of the FileSystemHandle interface queries the current permission state of the current handle.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/FileSystemHandle/queryPermission)
     */
    queryPermission(descriptor?: FileSystemHandlePermissionDescriptor): Promise<PermissionState>;
    /**
     * The **`requestPermission()`** method of the FileSystemHandle interface requests read or readwrite permissions for the file handle.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/FileSystemHandle/requestPermission)
     */
    requestPermission(descriptor?: FileSystemHandlePermissionDescriptor): Promise<PermissionState>;
}

interface Window {
    /**
     * The **`showDirectoryPicker()`** method of the Window interface displays a directory picker which allows the user to select a directory.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Window/showDirectoryPicker)
     */
    showDirectoryPicker(options?: DirectoryPickerOptions): Promise<FileSystemDirectoryHandle>;
    /**
     * The **`showOpenFilePicker()`** method of the Window interface shows a file picker that allows a user to select a file or multiple files and returns a handle for the file(s).
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Window/showOpenFilePicker)
     */
    showOpenFilePicker(options?: OpenFilePickerOptions): Promise<FileSystemFileHandle[]>;
    /**
     * The **`showSaveFilePicker()`** method of the Window interface shows a file picker that allows a user to save a file. Either by selecting an existing file, or entering a name for a new file.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Window/showSaveFilePicker)
     */
    showSaveFilePicker(options?: SaveFilePickerOptions): Promise<FileSystemFileHandle>;
}

/**
 * The **`showDirectoryPicker()`** method of the Window interface displays a directory picker which allows the user to select a directory.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Window/showDirectoryPicker)
 */
declare function showDirectoryPicker(options?: DirectoryPickerOptions): Promise<FileSystemDirectoryHandle>;

/**
 * The **`showOpenFilePicker()`** method of the Window interface shows a file picker that allows a user to select a file or multiple files and returns a handle for the file(s).
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Window/showOpenFilePicker)
 */
declare function showOpenFilePicker(options?: OpenFilePickerOptions): Promise<FileSystemFileHandle[]>;

/**
 * The **`showSaveFilePicker()`** method of the Window interface shows a file picker that allows a user to save a file. Either by selecting an existing file, or entering a name for a new file.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Window/showSaveFilePicker)
 */
declare function showSaveFilePicker(options?: SaveFilePickerOptions): Promise<FileSystemFileHandle>;

type StartInDirectory = WellKnownDirectory | FileSystemHandle;

type FileSystemPermissionMode = "read" | "readwrite";

type WellKnownDirectory = "desktop" | "documents" | "downloads" | "music" | "pictures" | "videos";
