// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: window. Spec: filter-effects

interface SVGFEGaussianBlurElement {
    /**
     * The **`edgeMode`** read-only property of the SVGFEGaussianBlurElement interface determines what color values to use when the blur needs to sample pixels beyond the edge of the input image. It reflects the edgeMode attribute of the given <feGaussianBlur> element.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGFEGaussianBlurElement/edgeMode)
     */
    readonly edgeMode: SVGAnimatedEnumeration;
}

interface SVGFEImageElement {
    readonly crossOrigin: SVGAnimatedString;
}
