// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: dom. Spec: gamepad-extensions

interface Gamepad {
    /**
     * The **`hand`** read-only property of the Gamepad interface returns an enum defining what hand the controller is being held in, or is most likely to be held in.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Gamepad/hand)
     */
    readonly hand: GamepadHand;
    /**
     * The **`hapticActuators`** read-only property of the Gamepad interface returns an array containing GamepadHapticActuator objects, each of which represents haptic feedback hardware available on the controller.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Gamepad/hapticActuators)
     */
    readonly hapticActuators: ReadonlyArray<GamepadHapticActuator>;
    /**
     * The **`pose`** read-only property of the Gamepad interface returns a GamepadPose object representing the pose information associated with a WebVR controller (e.g., its position and orientation in 3D space).
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Gamepad/pose)
     */
    readonly pose: GamepadPose | null;
}

interface GamepadHapticActuator {
    /**
     * The **`pulse()`** method of the GamepadHapticActuator interface makes the hardware pulse at a certain intensity for a specified duration.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/GamepadHapticActuator/pulse)
     */
    pulse(value: number, duration: number): Promise<boolean>;
}

/**
 * The **`GamepadPose`** interface of the Gamepad API represents the pose of a WebVR controller at a given timestamp (which includes orientation, position, velocity, and acceleration information).
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/GamepadPose)
 */
interface GamepadPose {
    /**
     * The **`angularAcceleration`** read-only property of the GamepadPose interface returns an array representing the angular acceleration vector of the Gamepad, in meters per second per second.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/GamepadPose/angularAcceleration)
     */
    readonly angularAcceleration: Float32Array<ArrayBuffer> | null;
    /**
     * The **`angularVelocity`** read-only property of the GamepadPose interface returns an array representing the angular velocity vector of the Gamepad, in radians per second.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/GamepadPose/angularVelocity)
     */
    readonly angularVelocity: Float32Array<ArrayBuffer> | null;
    /**
     * The **`hasOrientation`** read-only property of the GamepadPose interface returns a boolean value stating whether the Gamepad can track and return orientation information.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/GamepadPose/hasOrientation)
     */
    readonly hasOrientation: boolean;
    /**
     * The **`hasPosition`** read-only property of the GamepadPose interface returns a boolean value stating whether the Gamepad can track and return position information.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/GamepadPose/hasPosition)
     */
    readonly hasPosition: boolean;
    /**
     * The **`linearAcceleration`** read-only property of the GamepadPose interface returns an array representing the linear acceleration vector of the Gamepad, in meters per second per second.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/GamepadPose/linearAcceleration)
     */
    readonly linearAcceleration: Float32Array<ArrayBuffer> | null;
    /**
     * The **`linearVelocity`** read-only property of the GamepadPose interface returns an array representing the linear velocity vector of the Gamepad, in meters per second.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/GamepadPose/linearVelocity)
     */
    readonly linearVelocity: Float32Array<ArrayBuffer> | null;
    /**
     * The **`orientation`** read-only property of the GamepadPose interface returns the orientation of the Gamepad, as a quaternion value.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/GamepadPose/orientation)
     */
    readonly orientation: Float32Array<ArrayBuffer> | null;
    /**
     * The **`position`** read-only property of the GamepadPose interface returns the position of the Gamepad as a 3D vector.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/GamepadPose/position)
     */
    readonly position: Float32Array<ArrayBuffer> | null;
}

declare var GamepadPose: {
    prototype: GamepadPose;
    new(): GamepadPose;
};

type GamepadHand = "" | "left" | "right";
