// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: window. Spec: get-installed-related-apps

interface RelatedApplication {
    id?: string;
    platform: string;
    url?: string;
    version?: string;
}

interface Navigator {
    /**
     * The **`getInstalledRelatedApps()`** method returns a promise that resolves with an array of objects representing any related platform-specific apps or Progressive Web Apps that the user has installed. This could be used for content personalization such as removing "install our app" banners from the web app if the platform-specific app and/or PWA is already installed.
     * Available only in secure contexts.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Navigator/getInstalledRelatedApps)
     */
    getInstalledRelatedApps(): Promise<RelatedApplication[]>;
}
