// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: webworker. Spec: gpc

interface GlobalPrivacyControl {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/Navigator/globalPrivacyControl) */
    readonly globalPrivacyControl: boolean;
}
