// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: window. Spec: gyroscope

interface GyroscopeSensorOptions extends SensorOptions {
    referenceFrame?: GyroscopeLocalCoordinateSystem;
}

/**
 * The **`Gyroscope`** interface of the Sensor APIs provides on each reading the angular velocity of the device along all three axes.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Gyroscope)
 */
interface Gyroscope extends Sensor {
    /**
     * The **`x`** read-only property of the Gyroscope interface returns a number specifying the angular velocity of the device along its x-axis.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Gyroscope/x)
     */
    readonly x: number | null;
    /**
     * The **`y`** read-only property of the Gyroscope interface returns a number specifying the angular velocity of the device along its y-axis.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Gyroscope/y)
     */
    readonly y: number | null;
    /**
     * The **`z`** read-only property of the Gyroscope interface returns a number specifying the angular velocity of the device along its z-axis.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Gyroscope/z)
     */
    readonly z: number | null;
    addEventListener<K extends keyof SensorEventMap>(type: K, listener: (this: Gyroscope, ev: SensorEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof SensorEventMap>(type: K, listener: (this: Gyroscope, ev: SensorEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var Gyroscope: {
    prototype: Gyroscope;
    new(sensorOptions?: GyroscopeSensorOptions): Gyroscope;
};

type GyroscopeLocalCoordinateSystem = "device" | "screen";
