// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: webworker. Spec: html

interface ImageData {
    /**
     * The read-only **`ImageData.pixelFormat`** property is a string indicating the pixel format of the image data.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ImageData/pixelFormat)
     */
    readonly pixelFormat: ImageDataPixelFormat;
}
