// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: worker. Spec: idle-detection

interface IdleOptions {
    signal?: AbortSignal;
    threshold?: number;
}

interface IdleDetectorEventMap {
    "change": Event;
}

/**
 * The **`IdleDetector`** interface of the Idle Detection API provides methods and events for detecting user activity on a device or screen.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/IdleDetector)
 */
interface IdleDetector extends EventTarget {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/IdleDetector/change_event) */
    onchange: ((this: IdleDetector, ev: Event) => any) | null;
    /**
     * The **`screenState`** read-only property of the IdleDetector interface returns a string indicating whether the screen is locked, one of "locked" or "unlocked".
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/IdleDetector/screenState)
     */
    readonly screenState: ScreenIdleState | null;
    /**
     * The **`userState`** read-only property of the IdleDetector interface returns a string indicating whether the user has interacted with the device since the call to start().
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/IdleDetector/userState)
     */
    readonly userState: UserIdleState | null;
    /**
     * The **`start()`** method of the IdleDetector interface returns a Promise that resolves when the detector starts listening for changes in the user's idle state. This method takes an optional options object with the threshold in milliseconds where inactivity should be reported and signal for an AbortSignal to abort the idle detector.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/IdleDetector/start)
     */
    start(options?: IdleOptions): Promise<void>;
    addEventListener<K extends keyof IdleDetectorEventMap>(type: K, listener: (this: IdleDetector, ev: IdleDetectorEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof IdleDetectorEventMap>(type: K, listener: (this: IdleDetector, ev: IdleDetectorEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var IdleDetector: {
    prototype: IdleDetector;
    new(): IdleDetector;
};

type ScreenIdleState = "locked" | "unlocked";

type UserIdleState = "active" | "idle";
