// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: webworker. Spec: image-resource

interface ImageResource {
    label?: string;
    sizes?: string;
    src: string;
    type?: string;
}
