// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: webworker. Spec: image-capture

interface Point2D {
    x?: number;
    y?: number;
}
