// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: webworker. Spec: image-capture

interface Point2D {
    x?: number;
    y?: number;
}
