// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: dom. Spec: image-resource

interface ImageResource {
    label?: string;
    sizes?: string;
    src: string;
    type?: string;
}
