// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: webworker. Spec: IndexedDB

interface IDBGetAllOptions {
    count?: number;
    direction?: IDBCursorDirection;
    query?: any;
}

interface IDBIndex {
    /**
     * The **`getAllRecords()`** method of the IDBIndex interface retrieves all records (including index keys, primary keys, and values) from the index.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/IDBIndex/getAllRecords)
     */
    getAllRecords(options?: IDBGetAllOptions): IDBRequest;
}

interface IDBObjectStore {
    /**
     * The **`getAllRecords()`** method of the IDBObjectStore interface retrieves all records (including primary keys and values) from the object store.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/IDBObjectStore/getAllRecords)
     */
    getAllRecords(options?: IDBGetAllOptions): IDBRequest;
}

interface IDBRecord {
    readonly key: any;
    readonly primaryKey: any;
    readonly value: any;
}

declare var IDBRecord: {
    prototype: IDBRecord;
    new(): IDBRecord;
};
