// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Spec: ink-enhancement

interface InkPresenterParam {
    presentationArea?: Element | null;
}

interface InkTrailStyle {
    color: string;
    diameter: number;
}

/**
 * The **`DelegatedInkTrailPresenter`** interface of the Ink API provides the ability to instruct the OS-level compositor to render ink strokes between pointer event dispatches.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/DelegatedInkTrailPresenter)
 */
interface DelegatedInkTrailPresenter {
    /**
     * The **`presentationArea`** read-only property of the DelegatedInkTrailPresenter interface returns the Element inside which rendering of ink strokes is confined.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/DelegatedInkTrailPresenter/presentationArea)
     */
    readonly presentationArea: Element | null;
    /**
     * The **`updateInkTrailStartPoint()`** method of the DelegatedInkTrailPresenter interface indicates which PointerEvent was used as the last rendering point for the current frame, allowing the OS-level compositor to render a delegated ink trail ahead of the next pointer event being dispatched.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/DelegatedInkTrailPresenter/updateInkTrailStartPoint)
     */
    updateInkTrailStartPoint(event: PointerEvent, style: InkTrailStyle): void;
}

declare var DelegatedInkTrailPresenter: {
    prototype: DelegatedInkTrailPresenter;
    new(): DelegatedInkTrailPresenter;
};

/**
 * The **`Ink`** interface of the Ink API provides access to DelegatedInkTrailPresenter objects for the application to use to render ink strokes.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Ink)
 */
interface Ink {
    /**
     * The **`requestPresenter()`** method of the Ink interface returns a Promise that fulfills with a DelegatedInkTrailPresenter object to handle rendering strokes.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Ink/requestPresenter)
     */
    requestPresenter(param?: InkPresenterParam): Promise<DelegatedInkTrailPresenter>;
}

declare var Ink: {
    prototype: Ink;
    new(): Ink;
};

interface Navigator {
    /**
     * The **`ink`** read-only property of the Navigator interface returns an Ink object for the current document, providing access to Ink API functionality.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Navigator/ink)
     */
    readonly ink: Ink;
}
