// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: dom. Spec: input-device-capabilities

interface InputDeviceCapabilitiesInit {
    firesTouchEvents?: boolean;
    pointerMovementScrolls?: boolean;
}

/**
 * The **`InputDeviceCapabilities`** interface of the Input Device Capabilities API provides information about the physical device or a group of related devices responsible for generating input events. Events caused by the same physical input device get the same instance of this object, but the converse isn't true. For example, two mice with the same capabilities in a system may appear as a single InputDeviceCapabilities instance.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/InputDeviceCapabilities)
 */
interface InputDeviceCapabilities {
    /**
     * The **`firesTouchEvents`** read-only property of the InputDeviceCapabilities interface returns a boolean value that indicates whether the device dispatches touch events.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/InputDeviceCapabilities/firesTouchEvents)
     */
    readonly firesTouchEvents: boolean;
}

declare var InputDeviceCapabilities: {
    prototype: InputDeviceCapabilities;
    new(deviceInitDict?: InputDeviceCapabilitiesInit): InputDeviceCapabilities;
};

interface UIEvent {
    /**
     * The **`sourceCapabilities`** read-only property of the UIEvent interface returns an instance of the InputDeviceCapabilities interface which provides information about the physical device responsible for generating a touch event. If no input device was responsible for the event, it returns null.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/UIEvent/sourceCapabilities)
     */
    readonly sourceCapabilities: InputDeviceCapabilities | null;
}
