// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: dom. Spec: intersection-observer

interface IntersectionObserver {
    /**
     * The **`delay`** read-only property of the IntersectionObserver interface indicates the minimum delay between notifications from this observer.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/IntersectionObserver/delay)
     */
    readonly delay: number;
    /**
     * The **`trackVisibility`** read-only property of the IntersectionObserver interface indicates whether the observer is tracking target visibility in addition to element intersections.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/IntersectionObserver/trackVisibility)
     */
    readonly trackVisibility: boolean;
}

interface IntersectionObserverEntry {
    readonly isVisible: boolean;
}
