// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: dom. Spec: keyboard-lock

/**
 * The **`Keyboard`** interface of the Keyboard API provides functions that retrieve keyboard layout maps and toggle capturing of key presses from the physical keyboard.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Keyboard)
 */
interface Keyboard extends EventTarget {
    /**
     * The **`getLayoutMap()`** method of the Keyboard interface returns a Promise that resolves with an instance of KeyboardLayoutMap which is a map-like object with functions for retrieving the strings associated with specific physical keys.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Keyboard/getLayoutMap)
     */
    getLayoutMap(): Promise<KeyboardLayoutMap>;
    /**
     * The **`lock()`** method of the Keyboard interface returns a Promise that resolves after enabling the capture of key presses for any or all of the keys on the physical keyboard. This method can only capture keys that are granted access by the underlying operating system.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Keyboard/lock)
     */
    lock(keyCodes?: string[]): Promise<void>;
    /**
     * The **`unlock()`** method of the Keyboard interface unlocks all keys captured by the Keyboard.lock() method and returns synchronously.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Keyboard/unlock)
     */
    unlock(): void;
}

interface Keyboard {
    /**
     * The **`lock()`** method of the Keyboard interface returns a Promise that resolves after enabling the capture of key presses for any or all of the keys on the physical keyboard. This method can only capture keys that are granted access by the underlying operating system.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Keyboard/lock)
     */
    lock(keyCodes?: Iterable<string>): Promise<void>;
}

declare var Keyboard: {
    prototype: Keyboard;
    new(): Keyboard;
};

interface Navigator {
    /**
     * The **`keyboard`** read-only property of the Navigator interface returns a Keyboard object which provides access to functions that retrieve keyboard layout maps and toggle capturing of key presses from the physical keyboard.
     * Available only in secure contexts.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Navigator/keyboard)
     */
    readonly keyboard: Keyboard;
}
