// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: window. Spec: keyboard-map

/**
 * The **`KeyboardLayoutMap`** interface of the Keyboard API is a read-only object with functions for retrieving the string associated with specific physical keys.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/KeyboardLayoutMap)
 */
interface KeyboardLayoutMap {
    forEach(callbackfn: (value: string, key: string, parent: KeyboardLayoutMap) => void, thisArg?: any): void;
}

interface KeyboardLayoutMap extends ReadonlyMap<string, string> {
}

declare var KeyboardLayoutMap: {
    prototype: KeyboardLayoutMap;
    new(): KeyboardLayoutMap;
};
