// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: dom. Spec: layout-instability

/**
 * The **`LayoutShift`** interface of the Performance API provides insights into the layout stability of web pages based on movements of the elements on the page.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/LayoutShift)
 */
interface LayoutShift extends PerformanceEntry {
    /**
     * The **`hadRecentInput`** read-only property of the LayoutShift interface returns true if lastInputTime is less than 500 milliseconds in the past.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/LayoutShift/hadRecentInput)
     */
    readonly hadRecentInput: boolean;
    /**
     * The **`lastInputTime`** read-only property of the LayoutShift interface returns the time of the most recent excluding input or 0 if no excluding input has occurred.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/LayoutShift/lastInputTime)
     */
    readonly lastInputTime: DOMHighResTimeStamp;
    /**
     * The **`sources`** read-only property of the LayoutShift interface returns an array of LayoutShiftAttribution objects that indicate the DOM elements that moved during the layout shift.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/LayoutShift/sources)
     */
    readonly sources: ReadonlyArray<LayoutShiftAttribution>;
    /**
     * The **`value`** read-only property of the LayoutShift interface returns the layout shift score calculated as the impact fraction (fraction of the viewport that was shifted) multiplied by the distance fraction (distance moved as a fraction of viewport).
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/LayoutShift/value)
     */
    readonly value: number;
    /**
     * The **`toJSON()`** method of the LayoutShift interface is a serializer; it returns a JSON representation of the LayoutShift object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/LayoutShift/toJSON)
     */
    toJSON(): any;
}

declare var LayoutShift: {
    prototype: LayoutShift;
    new(): LayoutShift;
};

/**
 * The **`LayoutShiftAttribution`** interface provides debugging information about elements which have shifted.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/LayoutShiftAttribution)
 */
interface LayoutShiftAttribution {
    /**
     * The **`currentRect`** read-only property of the LayoutShiftAttribution interface returns a DOMRectReadOnly object representing the position of the element after the shift.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/LayoutShiftAttribution/currentRect)
     */
    readonly currentRect: DOMRectReadOnly;
    /**
     * The **`node`** read-only property of the LayoutShiftAttribution interface returns a Node representing the object that has shifted.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/LayoutShiftAttribution/node)
     */
    readonly node: Node | null;
    /**
     * The **`previousRect`** read-only property of the LayoutShiftAttribution interface returns a DOMRectReadOnly object representing the position of the element before the shift.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/LayoutShiftAttribution/previousRect)
     */
    readonly previousRect: DOMRectReadOnly;
}

declare var LayoutShiftAttribution: {
    prototype: LayoutShiftAttribution;
    new(): LayoutShiftAttribution;
};
