// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: webworker. Spec: local-network-access

interface Request {
    readonly targetAddressSpace: IPAddressSpace;
}

type IPAddressSpace = "local" | "loopback" | "public";
