// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: dom. Spec: local-font-access

interface QueryOptions {
    postscriptNames?: string[];
}

/**
 * The **`FontData`** interface of the Local Font Access API represents a single local font face.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/FontData)
 */
interface FontData {
    /**
     * The **`family`** read-only property of the FontData interface returns the family of the font face.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/FontData/family)
     */
    readonly family: string;
    /**
     * The **`fullName`** read-only property of the FontData interface returns the full name of the font face. This is usually a human-readable name used to identify the font, e.g., "Optima Bold".
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/FontData/fullName)
     */
    readonly fullName: string;
    /**
     * The **`postscriptName`** read-only property of the FontData interface returns the PostScript name of the font face.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/FontData/postscriptName)
     */
    readonly postscriptName: string;
    /**
     * The **`style`** read-only property of the FontData interface returns the style of the font face.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/FontData/style)
     */
    readonly style: string;
    /**
     * The **`blob()`** method of the FontData interface returns a Promise that fulfills with a Blob containing the raw bytes of the underlying font file.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/FontData/blob)
     */
    blob(): Promise<Blob>;
}

declare var FontData: {
    prototype: FontData;
    new(): FontData;
};

interface Window {
    /**
     * The **`window.queryLocalFonts()`** method returns a Promise that fulfills with an array of FontData objects representing the font faces available locally.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Window/queryLocalFonts)
     */
    queryLocalFonts(options?: QueryOptions): Promise<FontData[]>;
}

/**
 * The **`window.queryLocalFonts()`** method returns a Promise that fulfills with an array of FontData objects representing the font faces available locally.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Window/queryLocalFonts)
 */
declare function queryLocalFonts(options?: QueryOptions): Promise<FontData[]>;
