// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Spec: longtasks

/**
 * The **`PerformanceLongTaskTiming`** interface provides information about tasks that occupy the UI thread for 50 milliseconds or more.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PerformanceLongTaskTiming)
 */
interface PerformanceLongTaskTiming extends PerformanceEntry {
    /**
     * The **`attribution`** read-only property of the PerformanceLongTaskTiming interface returns an array of TaskAttributionTiming objects.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PerformanceLongTaskTiming/attribution)
     */
    readonly attribution: ReadonlyArray<TaskAttributionTiming>;
    /**
     * The **`toJSON()`** method of the PerformanceLongTaskTiming interface is a serializer; it returns a JSON representation of the PerformanceLongTaskTiming object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PerformanceLongTaskTiming/toJSON)
     */
    toJSON(): any;
}

declare var PerformanceLongTaskTiming: {
    prototype: PerformanceLongTaskTiming;
    new(): PerformanceLongTaskTiming;
};

/**
 * The **`TaskAttributionTiming`** interface returns information about the work involved in a long task and its associate frame context. The frame context, also called the container, is the iframe, embed or object that is being implicated, on the whole, for a long task.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/TaskAttributionTiming)
 */
interface TaskAttributionTiming extends PerformanceEntry {
    /**
     * The **`containerId`** read-only property of the TaskAttributionTiming interface returns the container's id attribute. A container is the iframe, embed or object etc. that is being implicated, on the whole, for a long task.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/TaskAttributionTiming/containerId)
     */
    readonly containerId: string;
    /**
     * The **`containerName`** read-only property of the TaskAttributionTiming interface returns the container's name attribute. A container is the iframe, embed or object etc. that is being implicated, on the whole, for a long task.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/TaskAttributionTiming/containerName)
     */
    readonly containerName: string;
    /**
     * The **`containerSrc`** read-only property of the TaskAttributionTiming interface returns the container's src attribute. A container is the iframe, embed or object etc. that is being implicated, on the whole, for a long task.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/TaskAttributionTiming/containerSrc)
     */
    readonly containerSrc: string;
    /**
     * The **`containerType`** read-only property of the TaskAttributionTiming interface returns the type of the container, one of iframe, embed, or object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/TaskAttributionTiming/containerType)
     */
    readonly containerType: string;
    /**
     * The **`toJSON()`** method of the TaskAttributionTiming interface is a serializer; it returns a JSON representation of the TaskAttributionTiming object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/TaskAttributionTiming/toJSON)
     */
    toJSON(): any;
}

declare var TaskAttributionTiming: {
    prototype: TaskAttributionTiming;
    new(): TaskAttributionTiming;
};
