// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: window. Spec: managed-configuration

interface Navigator {
    /** Available only in secure contexts. */
    readonly managed: NavigatorManagedData;
}

interface NavigatorManagedDataEventMap {
    "managedconfigurationchange": Event;
}

/** Available only in secure contexts. */
interface NavigatorManagedData extends EventTarget {
    onmanagedconfigurationchange: ((this: NavigatorManagedData, ev: Event) => any) | null;
    getManagedConfiguration(keys: string[]): Promise<Record<string, any>>;
    addEventListener<K extends keyof NavigatorManagedDataEventMap>(type: K, listener: (this: NavigatorManagedData, ev: NavigatorManagedDataEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof NavigatorManagedDataEventMap>(type: K, listener: (this: NavigatorManagedData, ev: NavigatorManagedDataEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

interface NavigatorManagedData {
    getManagedConfiguration(keys: Iterable<string>): Promise<Record<string, any>>;
}

declare var NavigatorManagedData: {
    prototype: NavigatorManagedData;
    new(): NavigatorManagedData;
};
