// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: dom. Spec: manifest-incubations

interface PromptResponseObject {
    userChoice?: AppBannerPromptOutcome;
}

/**
 * The **`BeforeInstallPromptEvent`** is the interface of the beforeinstallprompt event fired at the Window object before a user is prompted to "install" a website to a home screen on mobile.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BeforeInstallPromptEvent)
 */
interface BeforeInstallPromptEvent extends Event {
    /**
     * The **`prompt()`** method of the BeforeInstallPromptEvent interface allows a developer to show the install prompt at a time of their own choosing. Typically this will be called in the event handler for the app's custom install UI.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BeforeInstallPromptEvent/prompt)
     */
    prompt(): Promise<PromptResponseObject>;
}

declare var BeforeInstallPromptEvent: {
    prototype: BeforeInstallPromptEvent;
    new(type: string, eventInitDict?: EventInit): BeforeInstallPromptEvent;
};

interface Window {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/Window/appinstalled_event) */
    onappinstalled: ((this: Window, ev: Event) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/Window/beforeinstallprompt_event) */
    onbeforeinstallprompt: ((this: Window, ev: BeforeInstallPromptEvent) => any) | null;
}

type AppBannerPromptOutcome = "accepted" | "dismissed";
