// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: webworker. Spec: mediacapture-region

/**
 * The **`CropTarget`** interface of the Screen Capture API provides a static method, fromElement(), which returns a CropTarget instance that can be used to crop a captured video track to the area in which a specified element is rendered.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CropTarget)
 */
interface CropTarget {
}

declare var CropTarget: {
    prototype: CropTarget;
    new(): CropTarget;
};
