// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: dom. Spec: mediacapture-region

/**
 * The **`BrowserCaptureMediaStreamTrack`** interface of the Screen Capture API represents a single video track. It extends the MediaStreamTrack class with methods to limit the part of a self-capture stream (for example, a user's screen or window) that is captured.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BrowserCaptureMediaStreamTrack)
 */
interface BrowserCaptureMediaStreamTrack extends MediaStreamTrack {
    /**
     * The **`clone()`** method of the BrowserCaptureMediaStreamTrack interface returns a clone of the original BrowserCaptureMediaStreamTrack.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BrowserCaptureMediaStreamTrack/clone)
     */
    clone(): BrowserCaptureMediaStreamTrack;
    /**
     * The **`cropTo()`** method of the BrowserCaptureMediaStreamTrack interface crops a self-capture stream to the area in which a specified DOM element is rendered.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BrowserCaptureMediaStreamTrack/cropTo)
     */
    cropTo(cropTarget: CropTarget | null): Promise<void>;
    /**
     * The **`restrictTo()`** method of the BrowserCaptureMediaStreamTrack interface restricts a self-capture stream to a specific DOM element (and its descendants).
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BrowserCaptureMediaStreamTrack/restrictTo)
     */
    restrictTo(RestrictionTarget: RestrictionTarget | null): Promise<void>;
    addEventListener<K extends keyof MediaStreamTrackEventMap>(type: K, listener: (this: BrowserCaptureMediaStreamTrack, ev: MediaStreamTrackEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof MediaStreamTrackEventMap>(type: K, listener: (this: BrowserCaptureMediaStreamTrack, ev: MediaStreamTrackEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var BrowserCaptureMediaStreamTrack: {
    prototype: BrowserCaptureMediaStreamTrack;
    new(): BrowserCaptureMediaStreamTrack;
};

/**
 * The **`CropTarget`** interface of the Screen Capture API provides a static method, fromElement(), which returns a CropTarget instance that can be used to crop a captured video track to the area in which a specified element is rendered.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CropTarget)
 */
interface CropTarget {
}

declare var CropTarget: {
    prototype: CropTarget;
    new(): CropTarget;
    /**
     * The **`fromElement()`** static method of the CropTarget interface returns a CropTarget instance that can be used to crop a captured video track to the area in which a specified element is rendered.
     * Available only in secure contexts.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CropTarget/fromElement_static)
     */
    fromElement(element: Element): Promise<CropTarget>;
};
