// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: webworker. Spec: media-source

interface BufferedChangeEventInit extends EventInit {
}

/**
 * The **`BufferedChangeEvent`** interface of the Media Source Extensions API represents the event object for the bufferedchange event fired on a ManagedSourceBuffer. This event is fired whenever the buffered ranges of the ManagedSourceBuffer change, for example as a result of appendBuffer(), remove(), or endOfStream() calls, or when the user agent runs the memory cleanup algorithm.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BufferedChangeEvent)
 */
interface BufferedChangeEvent extends Event {
    /**
     * The **`addedRanges`** read-only property of the BufferedChangeEvent interface returns a TimeRanges object representing the time ranges that were added to the associated ManagedSourceBuffer. These are the ranges added between the last updatestart and updateend events, during the most recent run of the coded frame processing algorithm.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BufferedChangeEvent/addedRanges)
     */
    readonly addedRanges: any;
    /**
     * The **`removedRanges`** read-only property of the BufferedChangeEvent interface returns a TimeRanges object representing the time ranges that were removed from the associated ManagedSourceBuffer. These are the ranges removed between the last updatestart and updateend events, during the most recent run of the coded frame removal or coded frame eviction algorithm, or as a consequence of the user agent running the memory cleanup algorithm.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BufferedChangeEvent/removedRanges)
     */
    readonly removedRanges: any;
}

declare var BufferedChangeEvent: {
    prototype: BufferedChangeEvent;
    new(type: string, eventInitDict?: BufferedChangeEventInit): BufferedChangeEvent;
};

interface ManagedMediaSourceEventMap {
    "endstreaming": Event;
    "startstreaming": Event;
}

interface ManagedMediaSource {
        /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/ManagedMediaSource/endstreaming_event) */
        onendstreaming: ((this: ManagedMediaSource, ev: Event) => any) | null;
        /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/ManagedMediaSource/startstreaming_event) */
        onstartstreaming: ((this: ManagedMediaSource, ev: Event) => any) | null;
        /**
         * The **`streaming`** read-only property of the ManagedMediaSource interface is a boolean indicating whether the application should actively fetch and append media data.
         *
         * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ManagedMediaSource/streaming)
         */
        readonly streaming: boolean;
        addEventListener<K extends keyof ManagedMediaSourceEventMap>(type: K, listener: (this: ManagedMediaSource, ev: ManagedMediaSourceEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof ManagedMediaSourceEventMap>(type: K, listener: (this: ManagedMediaSource, ev: ManagedMediaSourceEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var ManagedMediaSource: {
    prototype: ManagedMediaSource;
    new(): ManagedMediaSource;
};

interface ManagedSourceBufferEventMap {
    "bufferedchange": BufferedChangeEvent;
}

interface ManagedSourceBuffer {
        /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/ManagedSourceBuffer/bufferedchange_event) */
        onbufferedchange: ((this: ManagedSourceBuffer, ev: BufferedChangeEvent) => any) | null;
        addEventListener<K extends keyof ManagedSourceBufferEventMap>(type: K, listener: (this: ManagedSourceBuffer, ev: ManagedSourceBufferEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof ManagedSourceBufferEventMap>(type: K, listener: (this: ManagedSourceBuffer, ev: ManagedSourceBufferEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var ManagedSourceBuffer: {
    prototype: ManagedSourceBuffer;
    new(): ManagedSourceBuffer;
};
