// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: dom. Spec: mediastream-recording

interface MediaRecorder {
    /**
     * The **`audioBitrateMode`** read-only property of the MediaRecorder interface returns the bitrate mode used to encode audio tracks.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/MediaRecorder/audioBitrateMode)
     */
    readonly audioBitrateMode: BitrateMode;
}
