// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: window. Spec: mediacapture-streams

interface MediaStreamTrackEventMap {
    "capturehandlechange": Event;
}
