// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: webworker. Spec: mediacapture-transform

/**
 * The **`VideoTrackGenerator`** interface of the Insertable Streams for MediaStreamTrack API has a WritableStream property that acts as a MediaStreamTrack source, by consuming a stream of VideoFrames as input.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/VideoTrackGenerator)
 */
interface VideoTrackGenerator {
    /**
     * The **`muted`** Boolean property of the VideoTrackGenerator interface can be used to temporarily halt or resume the generation of video frames in the output track.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/VideoTrackGenerator/muted)
     */
    muted: boolean;
    /**
     * The **`track`** property of the VideoTrackGenerator interface returns a MediaStreamTrack. VideoFrames written to VideoTrackGenerator.writable will be generated in this track.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/VideoTrackGenerator/track)
     */
    readonly track: any;
    /**
     * The **`writable`** property of the VideoTrackGenerator interface returns a WritableStream. This allows the writing of VideoFrames to the VideoTrackGenerator.track.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/VideoTrackGenerator/writable)
     */
    readonly writable: WritableStream;
}

declare var VideoTrackGenerator: {
    prototype: VideoTrackGenerator;
    new(): VideoTrackGenerator;
};
