// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Spec: mediasession

/**
 * The **`ChapterInformation`** interface of the Media Session API represents the metadata for an individual chapter of a media resource (i.e., a video or audio file).
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ChapterInformation)
 */
interface ChapterInformation {
    /**
     * The **`artwork`** read-only property of the ChapterInformation interface returns an Array of objects representing images associated with the chapter.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ChapterInformation/artwork)
     */
    readonly artwork: ReadonlyArray<MediaImage>;
    /**
     * The **`startTime`** read-only property of the ChapterInformation interface returns a number representing the start time of the chapter in seconds.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ChapterInformation/startTime)
     */
    readonly startTime: number;
    /**
     * The **`title`** read-only property of the ChapterInformation interface returns a string representing the title of the chapter.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ChapterInformation/title)
     */
    readonly title: string;
}

declare var ChapterInformation: {
    prototype: ChapterInformation;
    new(): ChapterInformation;
};

interface MediaMetadata {
    /**
     * The **`chapterInfo`** read-only property of the MediaMetadata interface returns an array of chapter information metadata associated with playing media, represented by ChapterInformation object instances.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/MediaMetadata/chapterInfo)
     */
    readonly chapterInfo: ReadonlyArray<ChapterInformation>;
}

interface MediaSession {
    /**
     * The **`setScreenshareActive()`** method of the MediaSession interface is used to indicate to the user agent whether the user's screenshare is considered to be active.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/MediaSession/setScreenshareActive)
     */
    setScreenshareActive(active: boolean): Promise<void>;
}
