// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: webworker. Spec: misc

interface BackgroundBlur extends MediaEffectInfo {
}

interface MediaEffectInfo {
    enabled: boolean;
}

interface Segment {
    boundingBox?: DOMRectInit;
    centerPoint?: Point2D;
    id: number;
    partOf?: number;
    probability: number;
    type: SegmentType;
}

declare function when(type: string, options?: ObservableEventListenerOptions): Observable;

type SegmentType = "eye" | "human-face" | "left-eye" | "mouth" | "right-eye";
