// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: window. Spec: misc

interface HTMLElementTagNameMap {
    "fencedframe": HTMLFencedFrameElement;
    "geolocation": HTMLGeolocationElement;
    "selectedcontent": HTMLSelectedContentElement;
}

/**
 * The **`crashReport`** read-only property of the Window interface returns a CrashReportContext object that enables arbitrary data to be recorded for the current top-level browsing context. The data is then included in CrashReport objects that are sent to a reporting endpoint when a browser crash occurs.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Window/crashReport)
 */
declare var crashReport: CrashReportContext;

/**
 * The **`window.credentialless`** read-only property returns a boolean that indicates whether the current document was loaded inside a credentialless <iframe>, meaning that it is loaded in a new, ephemeral context.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Window/credentialless)
 */
declare var credentialless: boolean;

/**
 * The **`fence`** read-only property of the Window interface returns a Fence object instance for the current document context.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Window/fence)
 */
declare var fence: Fence | null;

/**
 * The **`launchQueue`** read-only property of the Window interface provides access to the LaunchQueue class, which allows custom launch navigation handling to be implemented in a progressive web app (PWA), with the handling context signified by the launch_handler manifest field client_mode value.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Window/launchQueue)
 */
declare var launchQueue: LaunchQueue;

/** [MDN Reference](https://developer.mozilla.org/docs/Web/API/Window/appinstalled_event) */
declare var onappinstalled: ((this: Window, ev: Event) => any) | null;

/** [MDN Reference](https://developer.mozilla.org/docs/Web/API/Window/beforeinstallprompt_event) */
declare var onbeforeinstallprompt: ((this: Window, ev: BeforeInstallPromptEvent) => any) | null;

/**
 * The **`viewport`** read-only property of the Window interface returns a Viewport object instance, which provides information about the current state of the device's viewport.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Window/viewport)
 */
declare var viewport: Viewport;

declare function when(type: string, options?: ObservableEventListenerOptions): Observable;

/** [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/beforexrselect_event) */
declare var onbeforexrselect: ((this: Window, ev: Event) => any) | null;

interface XRHandIterator<T> extends IteratorObject<T, BuiltinIteratorReturn, unknown> {
    [Symbol.iterator](): XRHandIterator<T>;
}
