// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: webworker. Spec: misc

declare function when(type: string, options?: ObservableEventListenerOptions): Observable;
