// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: dom. Spec: navigation-timing

interface PerformanceNavigationTiming {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/PerformanceNavigationTiming/confidence) */
    readonly confidence: PerformanceTimingConfidence;
    /**
     * A website can indicate that a particular Client Hint is critical to the page by including it in a Critical-CH HTTP response header (as well as the Accept-CH HTTP request header which is needed for all client hints whether critical or not). Doing so will trigger a connection restart if the hint listed in the Critical-CH HTTP response header could have been, but wasn't, included in the HTTP request initially sent. If the browser does not support that client hint, it is ignored and no connection restart occurs.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PerformanceNavigationTiming/criticalCHRestart)
     */
    readonly criticalCHRestart: DOMHighResTimeStamp;
    /**
     * The **`notRestoredReasons`** read-only property of the PerformanceNavigationTiming interface returns a NotRestoredReasons object providing report data on reasons why the current document was blocked from using the back/forward cache (bfcache) on navigation.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PerformanceNavigationTiming/notRestoredReasons)
     */
    readonly notRestoredReasons: NotRestoredReasons | null;
}

/** [MDN Reference](https://developer.mozilla.org/docs/Web/API/PerformanceTimingConfidence) */
interface PerformanceTimingConfidence {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/PerformanceTimingConfidence/randomizedTriggerRate) */
    readonly randomizedTriggerRate: number;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/PerformanceTimingConfidence/value) */
    readonly value: PerformanceTimingConfidenceValue;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/PerformanceTimingConfidence/toJSON) */
    toJSON(): any;
}

declare var PerformanceTimingConfidence: {
    prototype: PerformanceTimingConfidence;
    new(): PerformanceTimingConfidence;
};

type PerformanceTimingConfidenceValue = "high" | "low";
