// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: webworker. Spec: netinfo

interface NavigatorNetworkInformation {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/Navigator/connection) */
    readonly connection: NetworkInformation;
}

interface NetworkInformationEventMap {
    "change": Event;
}

/**
 * The **`NetworkInformation`** interface of the Network Information API provides information about the connection a device is using to communicate with the network and provides a means for scripts to be notified if the connection type changes. The NetworkInformation interface cannot be instantiated. It is instead accessed through the connection property of the Navigator interface or the WorkerNavigator interface.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/NetworkInformation)
 */
interface NetworkInformation extends EventTarget, NetworkInformationSaveData {
    /**
     * The **`downlink`** read-only property of the NetworkInformation interface returns the effective bandwidth estimate in megabits per second, rounded to the nearest multiple of 25 kilobits per seconds. This value is based on recently observed application layer throughput across recently active connections, excluding connections made to a private address space. In the absence of recent bandwidth measurement data, the attribute value is determined by the properties of the underlying connection technology.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/NetworkInformation/downlink)
     */
    readonly downlink: Megabit;
    /**
     * The **`downlinkMax`** read-only property of the NetworkInformation interface returns the maximum downlink speed, in megabits per second (Mbps), for the underlying connection technology.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/NetworkInformation/downlinkMax)
     */
    readonly downlinkMax: Megabit;
    /**
     * The **`effectiveType`** read-only property of the NetworkInformation interface returns the effective type of the connection meaning one of slow-2g, 2g, 3g, or 4g. This value is determined using a combination of recently observed, round-trip time and downlink values.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/NetworkInformation/effectiveType)
     */
    readonly effectiveType: EffectiveConnectionType;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/NetworkInformation/change_event) */
    onchange: ((this: NetworkInformation, ev: Event) => any) | null;
    /**
     * The **`rtt`** read-only property of the NetworkInformation interface returns the estimated effective round-trip time of the current connection, rounded to the nearest multiple of 25 milliseconds. This value is based on recently observed application-layer RTT measurements across recently active connections. It excludes connections made to a private address space. If no recent measurement data is available, the value is based on the properties of the underlying connection technology.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/NetworkInformation/rtt)
     */
    readonly rtt: Millisecond;
    /**
     * The **`type`** read-only property of the NetworkInformation interface returns the type of connection a device is using to communicate with the network.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/NetworkInformation/type)
     */
    readonly type: ConnectionType;
    addEventListener<K extends keyof NetworkInformationEventMap>(type: K, listener: (this: NetworkInformation, ev: NetworkInformationEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof NetworkInformationEventMap>(type: K, listener: (this: NetworkInformation, ev: NetworkInformationEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var NetworkInformation: {
    prototype: NetworkInformation;
    new(): NetworkInformation;
};

type Megabit = number;

type Millisecond = number;

type ConnectionType = "bluetooth" | "cellular" | "ethernet" | "mixed" | "none" | "other" | "unknown" | "wifi";

type EffectiveConnectionType = "2g" | "3g" | "4g" | "slow-2g";
