// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Spec: page-lifecycle

interface Document {
    onfreeze: ((this: Document, ev: Event) => any) | null;
    onresume: ((this: Document, ev: Event) => any) | null;
    readonly wasDiscarded: boolean;
}
