// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: dom. Spec: page-lifecycle

interface Document {
    onfreeze: ((this: Document, ev: Event) => any) | null;
    onresume: ((this: Document, ev: Event) => any) | null;
    readonly wasDiscarded: boolean;
}
