// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: worker. Spec: performance-measure-memory

interface MemoryAttribution {
    container?: MemoryAttributionContainer;
    scope?: string;
    url?: string;
}

interface MemoryAttributionContainer {
    id?: string;
    src?: string;
}

interface MemoryBreakdownEntry {
    attribution?: MemoryAttribution[];
    bytes?: number;
    types?: string[];
}

interface MemoryMeasurement {
    breakdown?: MemoryBreakdownEntry[];
    bytes?: number;
}

interface Performance {
    /**
     * The **`measureUserAgentSpecificMemory()`** method is used to estimate the memory usage of a web application including all its iframes and workers.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Performance/measureUserAgentSpecificMemory)
     */
    measureUserAgentSpecificMemory(): Promise<MemoryMeasurement>;
}
