// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: dom. Spec: performance-timeline

/**
 * Maps each `entryType` reachable through the performance timeline to the
 * interface its entries implement, keyed by the identifier the timing entry
 * types registry assigns.
 */
interface PerformanceTimelineEntryTypeMap {
    "first-input": PerformanceEventTiming;
    "mark": PerformanceMark;
    "measure": PerformanceMeasure;
    "navigation": PerformanceNavigationTiming;
    "paint": PerformancePaintTiming;
    "resource": PerformanceResourceTiming;
}

/**
 * Maps every registered `entryType` to the interface its entries implement.
 * The types it adds to PerformanceTimelineEntryTypeMap are delivered only to a
 * `PerformanceObserver`.
 */
interface PerformanceEntryTypeMap extends PerformanceTimelineEntryTypeMap {
    "event": PerformanceEventTiming;
    "largest-contentful-paint": LargestContentfulPaint;
}

interface Performance {
    getEntriesByType<K extends keyof PerformanceTimelineEntryTypeMap>(type: K): PerformanceTimelineEntryTypeMap[K][];
    getEntriesByName<K extends keyof PerformanceTimelineEntryTypeMap>(name: string, type: K): PerformanceTimelineEntryTypeMap[K][];
}

interface PerformanceObserverEntryList {
    getEntriesByType<K extends keyof PerformanceEntryTypeMap>(type: K): PerformanceEntryTypeMap[K][];
    getEntriesByName<K extends keyof PerformanceEntryTypeMap>(name: string, type: K): PerformanceEntryTypeMap[K][];
}
