// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: dom. Spec: periodic-background-sync

interface BackgroundSyncOptions {
    minInterval?: number;
}

/**
 * The **`PeriodicSyncManager`** interface of the Web Periodic Background Synchronization API provides a way to register tasks to be run in a service worker at periodic intervals with network connectivity. These tasks are referred to as periodic background sync requests. Access PeriodicSyncManager through the ServiceWorkerRegistration.periodicSync.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PeriodicSyncManager)
 */
interface PeriodicSyncManager {
    /**
     * The **`getTags()`** method of the PeriodicSyncManager interface returns a Promise that resolves with a list of String objects representing the tags that are currently registered for periodic syncing.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PeriodicSyncManager/getTags)
     */
    getTags(): Promise<string[]>;
    /**
     * The **`register()`** method of the PeriodicSyncManager interface registers a periodic sync request with the browser with the specified tag and options. It returns a Promise that resolves when the registration completes.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PeriodicSyncManager/register)
     */
    register(tag: string, options?: BackgroundSyncOptions): Promise<void>;
    /**
     * The **`unregister()`** method of the PeriodicSyncManager interface unregisters the periodic sync request corresponding to the specified tag and returns a Promise that resolves when unregistration completes.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PeriodicSyncManager/unregister)
     */
    unregister(tag: string): Promise<void>;
}

declare var PeriodicSyncManager: {
    prototype: PeriodicSyncManager;
    new(): PeriodicSyncManager;
};

interface ServiceWorkerRegistration {
    /**
     * The **`periodicSync`** read-only property of the ServiceWorkerRegistration interface returns a reference to the PeriodicSyncManager interface, which allows for registering of tasks to run at specific intervals.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ServiceWorkerRegistration/periodicSync)
     */
    readonly periodicSync: PeriodicSyncManager;
}
