// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: dom. Spec: prerendering-revamped

interface Document {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/Document/prerenderingchange_event) */
    onprerenderingchange: ((this: Document, ev: Event) => any) | null;
    /**
     * The **`prerendering`** read-only property of the Document interface returns true if the document is currently in the process of prerendering, as initiated via the Speculation Rules API.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Document/prerendering)
     */
    readonly prerendering: boolean;
}

interface PerformanceNavigationTiming {
    /**
     * The **`activationStart`** read-only property represents the time between when a document starts prerendering and when it is activated.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PerformanceNavigationTiming/activationStart)
     */
    readonly activationStart: DOMHighResTimeStamp;
}
