// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Spec: private-click-measurement

interface HTMLAnchorElement {
    /**
     * The **`attributionSourceId`** property of the HTMLAnchorElement interface gets and sets the attributionsourceid HTML attribute on an <a> element.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLAnchorElement/attributionSourceId)
     */
    attributionSourceId: number;
}
