// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: dom. Spec: prompt-api

interface LanguageModelAppendOptions {
    signal?: AbortSignal;
}

interface LanguageModelCloneOptions {
    signal?: AbortSignal;
}

interface LanguageModelCreateCoreOptions {
    expectedInputs?: LanguageModelExpected[];
    expectedOutputs?: LanguageModelExpected[];
    temperature?: number;
    tools?: LanguageModelTool[];
    topK?: number;
}

interface LanguageModelCreateOptions extends LanguageModelCreateCoreOptions {
    initialPrompts?: LanguageModelMessage[];
    monitor?: CreateMonitorCallback;
    signal?: AbortSignal;
}

interface LanguageModelExpected {
    languages?: string[];
    type: LanguageModelMessageType;
}

interface LanguageModelMessage {
    content: string | LanguageModelMessageContent[];
    prefix?: boolean;
    role: LanguageModelMessageRole;
}

interface LanguageModelMessageContent {
    type: LanguageModelMessageType;
    value: LanguageModelMessageValue;
}

interface LanguageModelPromptOptions {
    omitResponseConstraintInput?: boolean;
    responseConstraint?: any;
    signal?: AbortSignal;
}

interface LanguageModelTool {
    description: string;
    execute: LanguageModelToolFunction;
    inputSchema: any;
    name: string;
}

interface LanguageModelEventMap {
    "contextoverflow": Event;
}

/** Available only in secure contexts. */
interface LanguageModel extends EventTarget, DestroyableModel {
    readonly contextUsage: number;
    readonly contextWindow: number;
    oncontextoverflow: ((this: LanguageModel, ev: Event) => any) | null;
    append(input: LanguageModelPrompt, options?: LanguageModelAppendOptions): Promise<void>;
    clone(options?: LanguageModelCloneOptions): Promise<LanguageModel>;
    measureContextUsage(input: LanguageModelPrompt, options?: LanguageModelPromptOptions): Promise<number>;
    prompt(input: LanguageModelPrompt, options?: LanguageModelPromptOptions): Promise<string>;
    promptStreaming(input: LanguageModelPrompt, options?: LanguageModelPromptOptions): ReadableStream;
    addEventListener<K extends keyof LanguageModelEventMap>(type: K, listener: (this: LanguageModel, ev: LanguageModelEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof LanguageModelEventMap>(type: K, listener: (this: LanguageModel, ev: LanguageModelEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

interface LanguageModel {
    append(input: Iterable<LanguageModelMessage>, options?: LanguageModelAppendOptions): Promise<void>;
    measureContextUsage(input: Iterable<LanguageModelMessage>, options?: LanguageModelPromptOptions): Promise<number>;
    prompt(input: Iterable<LanguageModelMessage>, options?: LanguageModelPromptOptions): Promise<string>;
    promptStreaming(input: Iterable<LanguageModelMessage>, options?: LanguageModelPromptOptions): ReadableStream;
}

declare var LanguageModel: {
    prototype: LanguageModel;
    new(): LanguageModel;
    availability(options?: LanguageModelCreateCoreOptions): Promise<Availability>;
    create(options?: LanguageModelCreateOptions): Promise<LanguageModel>;
};

interface LanguageModelToolFunction {
    (...arguments: any[]): string | PromiseLike<string>;
}

type LanguageModelMessageValue = ImageBitmapSource | AudioBuffer | BufferSource | string;

type LanguageModelPrompt = LanguageModelMessage[] | string;

type LanguageModelMessageRole = "assistant" | "system" | "user";

type LanguageModelMessageType = "audio" | "image" | "text" | "tool-call" | "tool-response";
