// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: worker. Spec: push-api

interface PushEvent {
    readonly notification: Notification | null;
}
