// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: dom. Spec: raw-camera-access

/** Available only in secure contexts. */
interface XRCamera {
    readonly height: number;
    readonly width: number;
}

declare var XRCamera: {
    prototype: XRCamera;
    new(): XRCamera;
};
