// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: webworker. Spec: resource-timing

interface PerformanceResourceTiming {
    readonly contentEncoding: string;
    /**
     * The **`renderBlockingStatus`** read-only property returns the render-blocking status of the resource.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PerformanceResourceTiming/renderBlockingStatus)
     */
    readonly renderBlockingStatus: RenderBlockingStatusType;
    readonly workerCacheLookupStart: DOMHighResTimeStamp;
    readonly workerRouterEvaluationStart: DOMHighResTimeStamp;
}

type RenderBlockingStatusType = "blocking" | "non-blocking";
