// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: window. Spec: saa-non-cookie-storage

interface Document {
    /**
     * The **`hasUnpartitionedCookieAccess()`** method of the Document interface returns a Promise that resolves with a boolean value indicating whether the document has access to third-party, unpartitioned cookies.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Document/hasUnpartitionedCookieAccess)
     */
    hasUnpartitionedCookieAccess(): Promise<boolean>;
}

/**
 * The **`StorageAccessHandle`** interface represents access to unpartitioned state granted by a call to Document.requestStorageAccess().
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/StorageAccessHandle)
 */
interface StorageAccessHandle {
    /**
     * The **`caches`** property of the StorageAccessHandle interface returns an unpartitioned CacheStorage object if access was granted, and throws a SecurityError DOMException otherwise.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/StorageAccessHandle/caches)
     */
    readonly caches: CacheStorage;
    /**
     * The **`indexedDB`** property of the StorageAccessHandle interface returns an unpartitioned IDBFactory object if access was granted, and throws a SecurityError DOMException otherwise.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/StorageAccessHandle/indexedDB)
     */
    readonly indexedDB: IDBFactory;
    /**
     * The **`localStorage`** property of the StorageAccessHandle interface returns an unpartitioned local Storage object if access was granted, and throws a SecurityError DOMException otherwise.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/StorageAccessHandle/localStorage)
     */
    readonly localStorage: Storage;
    /**
     * The **`locks`** property of the StorageAccessHandle interface returns an unpartitioned session LockManager object if access was granted, and throws a SecurityError DOMException otherwise.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/StorageAccessHandle/locks)
     */
    readonly locks: LockManager;
    /**
     * The **`sessionStorage`** property of the StorageAccessHandle interface returns an unpartitioned session Storage object if access was granted, and throws a SecurityError DOMException otherwise.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/StorageAccessHandle/sessionStorage)
     */
    readonly sessionStorage: Storage;
    /**
     * An unpartitioned **`BroadcastChannel`** object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/StorageAccessHandle/BroadcastChannel)
     */
    BroadcastChannel(name: string): BroadcastChannel;
    /**
     * An unpartitioned **`SharedWorker`** object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/StorageAccessHandle/SharedWorker)
     */
    SharedWorker(scriptURL: string | URL, options?: string | SharedWorkerOptions): SharedWorker;
    /**
     * A string containing an unpartitioned object URL that can be used to reference the contents of the specified source object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/StorageAccessHandle/createObjectURL)
     */
    createObjectURL(obj: Blob | MediaSource): string;
    /**
     * None.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/StorageAccessHandle/estimate)
     */
    estimate(): Promise<StorageEstimate>;
    /**
     * None.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/StorageAccessHandle/getDirectory)
     */
    getDirectory(): Promise<FileSystemDirectoryHandle>;
    /**
     * None (undefined).
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/StorageAccessHandle/revokeObjectURL)
     */
    revokeObjectURL(url: string): void;
}

declare var StorageAccessHandle: {
    prototype: StorageAccessHandle;
    new(): StorageAccessHandle;
};

type SameSiteCookiesType = "all" | "none";
