// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: dom. Spec: savedata

interface NetworkInformationSaveData {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/NetworkInformation/saveData) */
    readonly saveData: boolean;
}
