// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: dom. Spec: screen-capture

interface DisplayMediaStreamOptions {
    controller?: CaptureController;
}

interface CaptureControllerEventMap {
    "zoomlevelchange": Event;
}

/**
 * The **`CaptureController`** interface provides methods that can be used to further manipulate a captured display surface (captured via MediaDevices.getDisplayMedia())
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CaptureController)
 */
interface CaptureController extends EventTarget {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/CaptureController/zoomlevelchange_event) */
    onzoomlevelchange: ((this: CaptureController, ev: Event) => any) | null;
    /**
     * The **`zoomLevel`** read-only property of the CaptureController interface returns the captured display surface's current zoom level.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CaptureController/zoomLevel)
     */
    readonly zoomLevel: number | null;
    /**
     * The CaptureController interface's **`decreaseZoomLevel()`** method decreases the captured display surface's zoom level by one increment.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CaptureController/decreaseZoomLevel)
     */
    decreaseZoomLevel(): Promise<void>;
    /**
     * The CaptureController interface's **`forwardWheel()`** method starts forwarding wheel events fired on the referenced element to the viewport of an associated captured display surface.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CaptureController/forwardWheel)
     */
    forwardWheel(element: HTMLElement | null): Promise<void>;
    /**
     * The CaptureController interface's **`getSupportedZoomLevels()`** method returns the different zoom levels that the captured display surface supports.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CaptureController/getSupportedZoomLevels)
     */
    getSupportedZoomLevels(): number[];
    /**
     * The CaptureController interface's **`increaseZoomLevel()`** method increases the captured display surface's zoom level by one increment.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CaptureController/increaseZoomLevel)
     */
    increaseZoomLevel(): Promise<void>;
    /**
     * The CaptureController interface's **`resetZoomLevel()`** method resets the captured display surface's zoom to its initial level, which is 100.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CaptureController/resetZoomLevel)
     */
    resetZoomLevel(): Promise<void>;
    /**
     * The CaptureController interface's **`setFocusBehavior()`** method controls whether the captured tab or window will be focused when an associated MediaDevices.getDisplayMedia() Promise fulfills, or whether the focus will remain with the tab containing the capturing app.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CaptureController/setFocusBehavior)
     */
    setFocusBehavior(focusBehavior: CaptureStartFocusBehavior): void;
    addEventListener<K extends keyof CaptureControllerEventMap>(type: K, listener: (this: CaptureController, ev: CaptureControllerEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof CaptureControllerEventMap>(type: K, listener: (this: CaptureController, ev: CaptureControllerEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var CaptureController: {
    prototype: CaptureController;
    new(): CaptureController;
};

type CaptureStartFocusBehavior = "focus-captured-surface" | "focus-capturing-application" | "no-focus-change";
