// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: dom. Spec: secure-payment-confirmation

type SecurePaymentConfirmationCapabilities = Record<string, boolean>;

type SecurePaymentConfirmationAvailability = "available" | "unavailable-feature-not-enabled" | "unavailable-no-permission-policy" | "unavailable-no-user-verifying-platform-authenticator" | "unavailable-unknown-reason";
