// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Spec: secure-payment-confirmation

type SecurePaymentConfirmationCapabilities = Record<string, boolean>;

type SecurePaymentConfirmationAvailability = "available" | "unavailable-feature-not-enabled" | "unavailable-no-permission-policy" | "unavailable-no-user-verifying-platform-authenticator" | "unavailable-unknown-reason";
