// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: webworker. Spec: service-workers

interface RouterCondition {
    not?: RouterCondition;
    or?: RouterCondition[];
    requestDestination?: RequestDestination;
    requestMethod?: string;
    requestMode?: RequestMode;
    runningStatus?: RunningStatus;
    urlPattern?: URLPatternCompatible;
}

interface RouterRule {
    condition: RouterCondition;
    source: RouterSource;
}

interface RouterSourceDict {
    cacheName?: string;
}

/**
 * The parameter passed into an install event handler function, the **`InstallEvent`** interface represents an install action that is dispatched on the ServiceWorkerGlobalScope of a ServiceWorker. As a child of ExtendableEvent, it ensures that functional events such as FetchEvent are not dispatched during installation.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/InstallEvent)
 */
interface InstallEvent extends ExtendableEvent {
    /**
     * The **`addRoutes()`** method of the InstallEvent interface specifies one or more static routes, which define rules for fetching specified resources that will be used even before service worker startup. This allows you to, for example, bypass a service worker in cases where you always want to fetch a resource from the network or a browser Cache, and avoids the performance overhead of unnecessary service worker cycles.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/InstallEvent/addRoutes)
     */
    addRoutes(rules: RouterRule | RouterRule[]): Promise<void>;
}

interface InstallEvent {
    /**
     * The **`addRoutes()`** method of the InstallEvent interface specifies one or more static routes, which define rules for fetching specified resources that will be used even before service worker startup. This allows you to, for example, bypass a service worker in cases where you always want to fetch a resource from the network or a browser Cache, and avoids the performance overhead of unnecessary service worker cycles.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/InstallEvent/addRoutes)
     */
    addRoutes(rules: RouterRule | Iterable<RouterRule>): Promise<void>;
}

declare var InstallEvent: {
    prototype: InstallEvent;
    new(type: string, eventInitDict?: ExtendableEventInit): InstallEvent;
};

interface ServiceWorkerGlobalScopeEventMap {
    "backgroundfetchabort": BackgroundFetchEvent;
    "backgroundfetchclick": BackgroundFetchEvent;
    "backgroundfetchfail": BackgroundFetchUpdateUIEvent;
    "backgroundfetchsuccess": BackgroundFetchUpdateUIEvent;
    "canmakepayment": CanMakePaymentEvent;
    "contentdelete": ContentIndexEvent;
    "paymentrequest": PaymentRequestEvent;
    "periodicsync": PeriodicSyncEvent;
    "sync": SyncEvent;
}

interface WindowClient {
    /**
     * The **`ancestorOrigins`** read-only property of the WindowClient interface is an array of strings listing the origins of all ancestors of the browsing context represented by this WindowClient in reverse order.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/WindowClient/ancestorOrigins)
     */
    readonly ancestorOrigins: ReadonlyArray<string>;
}

type RouterSource = RouterSourceDict | RouterSourceEnum;

type RouterSourceEnum = "cache" | "fetch-event" | "network" | "race-network-and-fetch-handler";

type RunningStatus = "not-running" | "running";
