// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: webworker. Spec: shape-detection-api

interface BarcodeDetectorOptions {
    formats?: BarcodeFormat[];
}

interface DetectedBarcode {
    boundingBox: DOMRectReadOnly;
    cornerPoints: Point2D[];
    format: BarcodeFormat;
    rawValue: string;
}

/**
 * The **`BarcodeDetector`** interface of the Barcode Detection API allows detection of linear and two dimensional barcodes in images.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BarcodeDetector)
 */
interface BarcodeDetector {
    /**
     * The **`detect()`** method of the BarcodeDetector interface returns a Promise which fulfills with an Array of detected barcodes within an image.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BarcodeDetector/detect)
     */
    detect(image: ImageBitmapSource): Promise<DetectedBarcode[]>;
}

declare var BarcodeDetector: {
    prototype: BarcodeDetector;
    new(barcodeDetectorOptions?: BarcodeDetectorOptions): BarcodeDetector;
    /**
     * The **`getSupportedFormats()`** static method of the BarcodeDetector interface returns a Promise which fulfills with an Array of supported barcode format types.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BarcodeDetector/getSupportedFormats_static)
     */
    getSupportedFormats(): Promise<BarcodeFormat[]>;
};

type BarcodeFormat = "aztec" | "codabar" | "code_128" | "code_39" | "code_93" | "data_matrix" | "ean_13" | "ean_8" | "itf" | "pdf417" | "qr_code" | "unknown" | "upc_a" | "upc_e";
