// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: dom. Spec: speech-api

interface SpeechRecognitionOptions {
    langs: string[];
    processLocally?: boolean;
    quality?: SpeechRecognitionQuality;
}

/**
 * The **`SpeechGrammarList`** interface of the Web Speech API represents a list of SpeechGrammar objects containing words or patterns of words that we want the recognition service to recognize.
 * @deprecated
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechGrammarList)
 */
interface SpeechGrammarList {
    /**
     * The **`length`** read-only property of the SpeechGrammarList interface returns the number of SpeechGrammar objects contained in the SpeechGrammarList.
     * @deprecated
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechGrammarList/length)
     */
    readonly length: number;
    /**
     * The **`addFromString()`** method of the SpeechGrammarList interface takes a grammar present in a specific string within the code base (e.g., stored in a variable) and adds it to the SpeechGrammarList as a new SpeechGrammar object.
     * @deprecated
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechGrammarList/addFromString)
     */
    addFromString(string: string, weight?: number): void;
    /**
     * The **`addFromURI()`** method of the SpeechGrammarList interface takes a grammar present at a specific URI and adds it to the SpeechGrammarList as a new SpeechGrammar object.
     * @deprecated
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechGrammarList/addFromURI)
     */
    addFromURI(src: string, weight?: number): void;
    /**
     * The **`item`** getter of the SpeechGrammarList interface is a standard getter — it allows individual SpeechGrammar objects to be retrieved from the SpeechGrammarList using array syntax.
     * @deprecated
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechGrammarList/item)
     */
    item(index: number): any;
    [index: number]: any;
}

interface SpeechGrammarList {
    [Symbol.iterator](): ArrayIterator<any>;
}

/** @deprecated */
declare var SpeechGrammarList: {
    prototype: SpeechGrammarList;
    new(): SpeechGrammarList;
};

interface SpeechRecognitionEventMap {
    "audioend": Event;
    "audiostart": Event;
    "end": Event;
    "error": SpeechRecognitionErrorEvent;
    "nomatch": SpeechRecognitionEvent;
    "result": SpeechRecognitionEvent;
    "soundend": Event;
    "soundstart": Event;
    "speechend": Event;
    "speechstart": Event;
    "start": Event;
}

/**
 * The **`SpeechRecognition`** interface of the Web Speech API is the controller interface for the recognition service; this also handles the SpeechRecognitionEvent sent from the recognition service.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechRecognition)
 */
interface SpeechRecognition extends EventTarget {
    /**
     * The **`continuous`** property of the SpeechRecognition interface controls whether continuous results are returned for each recognition, or only a single result.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechRecognition/continuous)
     */
    continuous: boolean;
    /**
     * The **`grammars`** property of the SpeechRecognition interface returns and sets a collection of SpeechGrammar objects that represent the grammars that will be understood by the current SpeechRecognition.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechRecognition/grammars)
     */
    grammars: SpeechGrammarList;
    /**
     * The **`interimResults`** property of the SpeechRecognition interface controls whether interim results should be returned (true) or not (false). Interim results are results that are not yet final (e.g., the SpeechRecognitionResult.isFinal property is false).
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechRecognition/interimResults)
     */
    interimResults: boolean;
    /**
     * The **`lang`** property of the SpeechRecognition interface returns and sets the language of the current SpeechRecognition. If not specified, this defaults to the HTML lang attribute value, or the user agent's language setting if that isn't set either.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechRecognition/lang)
     */
    lang: string;
    /**
     * The **`maxAlternatives`** property of the SpeechRecognition interface sets the maximum number of SpeechRecognitionAlternatives provided per SpeechRecognitionResult.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechRecognition/maxAlternatives)
     */
    maxAlternatives: number;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechRecognition/audioend_event) */
    onaudioend: ((this: SpeechRecognition, ev: Event) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechRecognition/audiostart_event) */
    onaudiostart: ((this: SpeechRecognition, ev: Event) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechRecognition/end_event) */
    onend: ((this: SpeechRecognition, ev: Event) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechRecognition/error_event) */
    onerror: ((this: SpeechRecognition, ev: SpeechRecognitionErrorEvent) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechRecognition/nomatch_event) */
    onnomatch: ((this: SpeechRecognition, ev: SpeechRecognitionEvent) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechRecognition/result_event) */
    onresult: ((this: SpeechRecognition, ev: SpeechRecognitionEvent) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechRecognition/soundend_event) */
    onsoundend: ((this: SpeechRecognition, ev: Event) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechRecognition/soundstart_event) */
    onsoundstart: ((this: SpeechRecognition, ev: Event) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechRecognition/speechend_event) */
    onspeechend: ((this: SpeechRecognition, ev: Event) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechRecognition/speechstart_event) */
    onspeechstart: ((this: SpeechRecognition, ev: Event) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechRecognition/start_event) */
    onstart: ((this: SpeechRecognition, ev: Event) => any) | null;
    /**
     * The **`phrases`** property of the SpeechRecognition interface sets an array of SpeechRecognitionPhrase objects to be used for contextual biasing.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechRecognition/phrases)
     */
    phrases: SpeechRecognitionPhrase[];
    /**
     * The **`processLocally`** property of the SpeechRecognition interface specifies whether speech recognition must be performed locally on the user's device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechRecognition/processLocally)
     */
    processLocally: boolean;
    /**
     * The **`abort()`** method of the Web Speech API stops the speech recognition service from listening to incoming audio, and doesn't attempt to return a SpeechRecognitionResult.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechRecognition/abort)
     */
    abort(): void;
    /**
     * The **`start()`** method of the Web Speech API starts the speech recognition service to listen for incoming audio (from a microphone or an audio track) and returns the results of that recognition.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechRecognition/start)
     */
    start(): void;
    start(audioTrack: MediaStreamTrack): void;
    /**
     * The **`stop()`** method of the Web Speech API stops the speech recognition service from listening for incoming audio and attempts to return a SpeechRecognitionResult based on the results captured so far.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechRecognition/stop)
     */
    stop(): void;
    addEventListener<K extends keyof SpeechRecognitionEventMap>(type: K, listener: (this: SpeechRecognition, ev: SpeechRecognitionEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof SpeechRecognitionEventMap>(type: K, listener: (this: SpeechRecognition, ev: SpeechRecognitionEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var SpeechRecognition: {
    prototype: SpeechRecognition;
    new(): SpeechRecognition;
    /**
     * The **`available()`** static method of the Web Speech API checks whether the specified languages are available for speech recognition.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechRecognition/available_static)
     */
    available(options: SpeechRecognitionOptions): Promise<AvailabilityStatus>;
    /**
     * The **`install()`** static method of the Web Speech API installs the required language packs for on-device speech recognition in the specified languages.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechRecognition/install_static)
     */
    install(options: SpeechRecognitionOptions): Promise<boolean>;
};

/**
 * The **`SpeechRecognitionPhrase`** interface of the Web Speech API represents a phrase that can be passed to the speech recognition engine for contextual biasing.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechRecognitionPhrase)
 */
interface SpeechRecognitionPhrase {
    /**
     * The **`boost`** read-only property of the SpeechRecognitionPhrase interface returns a floating point number representing the weight you want to give the corresponding phrase.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechRecognitionPhrase/boost)
     */
    readonly boost: number;
    /**
     * The **`phrase`** read-only property of the SpeechRecognitionPhrase interface returns a string containing the word or phrase you want boosted in the recognition engine's contextual bias.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechRecognitionPhrase/phrase)
     */
    readonly phrase: string;
}

declare var SpeechRecognitionPhrase: {
    prototype: SpeechRecognitionPhrase;
    new(phrase: string, boost?: number): SpeechRecognitionPhrase;
};

type AvailabilityStatus = "available" | "downloadable" | "downloading" | "unavailable";

type SpeechRecognitionQuality = "command" | "conversation" | "dictation";
