// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: dom. Spec: storage-buckets

interface StorageBucketOptions {
    expires?: DOMHighResTimeStamp;
    persisted?: boolean;
    quota?: number;
}

/** Available only in secure contexts. */
interface NavigatorStorageBuckets {
    readonly storageBuckets: StorageBucketManager;
}

/** Available only in secure contexts. */
interface StorageBucket {
    readonly caches: CacheStorage;
    readonly indexedDB: IDBFactory;
    readonly name: string;
    estimate(): Promise<StorageEstimate>;
    expires(): Promise<DOMHighResTimeStamp | null>;
    getDirectory(): Promise<FileSystemDirectoryHandle>;
    persist(): Promise<boolean>;
    persisted(): Promise<boolean>;
    setExpires(expires: DOMHighResTimeStamp): Promise<void>;
}

declare var StorageBucket: {
    prototype: StorageBucket;
    new(): StorageBucket;
};

/** Available only in secure contexts. */
interface StorageBucketManager {
    delete(name: string): Promise<void>;
    keys(): Promise<string[]>;
    open(name: string, options?: StorageBucketOptions): Promise<StorageBucket>;
}

declare var StorageBucketManager: {
    prototype: StorageBucketManager;
    new(): StorageBucketManager;
};
