// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Spec: svg-paths

interface SVGPathDataSettings {
    normalize?: boolean;
}

interface SVGPathData {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGPathElement/getPathData) */
    getPathData(settings?: SVGPathDataSettings): any[];
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGPathElement/setPathData) */
    setPathData(pathData: any[]): void;
}

interface SVGPathData {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGPathElement/setPathData) */
    setPathData(pathData: Iterable<any>): void;
}

interface SVGPathElement {
    /**
     * The **`getPathSegmentAtLength()`** method of the SVGPathElement interface returns the path segment at a given distance along the path.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGPathElement/getPathSegmentAtLength)
     */
    getPathSegmentAtLength(distance: number): any;
}
