// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: dom. Spec: SVG

interface SVGMarkerElement {
    /**
     * The **`orient`** property of the SVGMarkerElement interface defines how the marker is rotated when it is placed at its position on the shape. It reflects the orient attribute value of the corresponding <marker> element.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGMarkerElement/orient)
     */
    orient: string;
}

interface SVGScriptElement {
    crossOrigin: string | null;
}
