// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: dom. Spec: trust-token-api

interface PrivateToken {
    issuers?: string[];
    operation: OperationType;
    refreshPolicy?: RefreshPolicy;
    version: TokenVersion;
}

interface Document {
    /**
     * The **`hasPrivateToken()`** method of the Document interface returns a promise that fulfills with a boolean indicating whether the browser has a private state token stored from a particular issuer server.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Document/hasPrivateToken)
     */
    hasPrivateToken(issuer: string): Promise<boolean>;
    /**
     * The **`hasRedemptionRecord()`** method of the Document interface returns a promise that fulfills with a boolean indicating whether the browser has a redemption record originating from a particular issuer.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Document/hasRedemptionRecord)
     */
    hasRedemptionRecord(issuer: string): Promise<boolean>;
}

interface HTMLIFrameElement {
    /**
     * The **`privateToken`** property of the HTMLIFrameElement interface returns a string representation of an options object representing a private state token operation; this object has the same structure as the RequestInit dictionary's privateToken property.
     * Available only in secure contexts.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLIFrameElement/privateToken)
     */
    privateToken: string;
}

interface XMLHttpRequest {
    /**
     * The XMLHttpRequest method **`setPrivateToken()`** adds private state token information to an XMLHttpRequest call, to initiate private state token operations.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XMLHttpRequest/setPrivateToken)
     */
    setPrivateToken(privateToken: PrivateToken): void;
}

type OperationType = "send-redemption-record" | "token-redemption" | "token-request";

type RefreshPolicy = "none" | "refresh";

type TokenVersion = "1";
