// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Spec: ua-client-hints

interface NavigatorUABrandVersion {
    brand?: string;
    version?: string;
}

interface UADataValues {
    architecture?: string;
    bitness?: string;
    brands?: NavigatorUABrandVersion[];
    formFactors?: string[];
    fullVersionList?: NavigatorUABrandVersion[];
    mobile?: boolean;
    model?: string;
    platform?: string;
    platformVersion?: string;
    uaFullVersion?: string;
    wow64?: boolean;
}

interface UALowEntropyJSON {
    brands?: NavigatorUABrandVersion[];
    mobile?: boolean;
    platform?: string;
}

interface NavigatorUA {
    /**
     * Available only in secure contexts.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Navigator/userAgentData)
     */
    readonly userAgentData: NavigatorUAData;
}

/**
 * The **`NavigatorUAData`** interface of the User-Agent Client Hints API returns information about the browser and operating system of a user.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/NavigatorUAData)
 */
interface NavigatorUAData {
    /**
     * The **`brands`** read-only property of the NavigatorUAData interface returns an array of brand information.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/NavigatorUAData/brands)
     */
    readonly brands: ReadonlyArray<NavigatorUABrandVersion>;
    /**
     * The **`mobile`** read-only property of the NavigatorUAData interface returns a value indicating whether the device is a mobile device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/NavigatorUAData/mobile)
     */
    readonly mobile: boolean;
    /**
     * The **`platform`** read-only property of the NavigatorUAData interface returns the platform brand information.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/NavigatorUAData/platform)
     */
    readonly platform: string;
    /**
     * The **`getHighEntropyValues()`** method of the NavigatorUAData interface returns a Promise that resolves with a dictionary object containing low entropy information and requested high entropy information about the browser.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/NavigatorUAData/getHighEntropyValues)
     */
    getHighEntropyValues(hints: string[]): Promise<UADataValues>;
    /**
     * The **`toJSON()`** method of the NavigatorUAData interface is a serializer that returns a JSON representation of the low entropy properties of the NavigatorUAData object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/NavigatorUAData/toJSON)
     */
    toJSON(): UALowEntropyJSON;
}

interface NavigatorUAData {
    /**
     * The **`getHighEntropyValues()`** method of the NavigatorUAData interface returns a Promise that resolves with a dictionary object containing low entropy information and requested high entropy information about the browser.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/NavigatorUAData/getHighEntropyValues)
     */
    getHighEntropyValues(hints: Iterable<string>): Promise<UADataValues>;
}

declare var NavigatorUAData: {
    prototype: NavigatorUAData;
    new(): NavigatorUAData;
};
