// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: worker. Spec: urlpattern

type URLPatternCompatible = string | URLPatternInit | URLPattern;
