// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: window. Spec: web-bluetooth

interface BluetoothDataFilterInit {
    dataPrefix?: BufferSource;
    mask?: BufferSource;
}

interface BluetoothLEScanFilterInit {
    manufacturerData?: BluetoothManufacturerDataFilterInit[];
    name?: string;
    namePrefix?: string;
    serviceData?: BluetoothServiceDataFilterInit[];
    services?: BluetoothServiceUUID[];
}

interface BluetoothManufacturerDataFilterInit extends BluetoothDataFilterInit {
    companyIdentifier: number;
}

interface BluetoothServiceDataFilterInit extends BluetoothDataFilterInit {
    service: BluetoothServiceUUID;
}

interface RequestDeviceOptions {
    acceptAllDevices?: boolean;
    exclusionFilters?: BluetoothLEScanFilterInit[];
    filters?: BluetoothLEScanFilterInit[];
    optionalManufacturerData?: number[];
    optionalServices?: BluetoothServiceUUID[];
}

interface BluetoothEventMap extends BluetoothDeviceEventHandlersEventMap, CharacteristicEventHandlersEventMap {
}

/**
 * The **`Bluetooth`** interface of the Web Bluetooth API provides methods to query Bluetooth availability and request access to devices.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Bluetooth)
 */
interface Bluetooth extends EventTarget, BluetoothDeviceEventHandlers, CharacteristicEventHandlers {
    /**
     * The **`getAvailability()`** method of the Bluetooth interface nominally returns true if the user agent can support Bluetooth (because the device has a Bluetooth adapter), and false otherwise.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Bluetooth/getAvailability)
     */
    getAvailability(): Promise<boolean>;
    /**
     * The **`Bluetooth.requestDevice()`** method of the Bluetooth interface returns a Promise that fulfills with a BluetoothDevice object matching the specified options. If there is no chooser UI, this method returns the first device matching the criteria.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Bluetooth/requestDevice)
     */
    requestDevice(options?: RequestDeviceOptions): Promise<BluetoothDevice>;
    addEventListener<K extends keyof BluetoothEventMap>(type: K, listener: (this: Bluetooth, ev: BluetoothEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof BluetoothEventMap>(type: K, listener: (this: Bluetooth, ev: BluetoothEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var Bluetooth: {
    prototype: Bluetooth;
    new(): Bluetooth;
};

/**
 * The **`BluetoothCharacteristicProperties`** interface of the Web Bluetooth API provides the operations that are valid on the given BluetoothRemoteGATTCharacteristic.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothCharacteristicProperties)
 */
interface BluetoothCharacteristicProperties {
    /**
     * The **`authenticatedSignedWrites`** read-only property of the BluetoothCharacteristicProperties interface returns a boolean that is true if signed writing to the characteristic value is permitted.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothCharacteristicProperties/authenticatedSignedWrites)
     */
    readonly authenticatedSignedWrites: boolean;
    /**
     * The **`broadcast`** read-only property of the BluetoothCharacteristicProperties interface returns a boolean that is true if the broadcast of the characteristic value is permitted using the Server Characteristic Configuration Descriptor.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothCharacteristicProperties/broadcast)
     */
    readonly broadcast: boolean;
    /**
     * The **`indicate`** read-only property of the BluetoothCharacteristicProperties interface returns a boolean that is true if indications of the characteristic value with acknowledgement is permitted.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothCharacteristicProperties/indicate)
     */
    readonly indicate: boolean;
    /**
     * The **`notify`** read-only property of the BluetoothCharacteristicProperties interface returns a boolean that is true if notifications of the characteristic value without acknowledgement is permitted.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothCharacteristicProperties/notify)
     */
    readonly notify: boolean;
    /**
     * The **`read`** read-only property of the BluetoothCharacteristicProperties interface returns a boolean that is true if the reading of the characteristic value is permitted.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothCharacteristicProperties/read)
     */
    readonly read: boolean;
    /**
     * The **`reliableWrite`** read-only property of the BluetoothCharacteristicProperties interface returns a boolean that is true if reliable writes to the characteristic is permitted.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothCharacteristicProperties/reliableWrite)
     */
    readonly reliableWrite: boolean;
    /**
     * The **`writableAuxiliaries`** read-only property of the BluetoothCharacteristicProperties interface returns a boolean that is true if reliable writes to the characteristic descriptor is permitted.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothCharacteristicProperties/writableAuxiliaries)
     */
    readonly writableAuxiliaries: boolean;
    /**
     * The **`write`** read-only property of the BluetoothCharacteristicProperties interface returns a boolean that is true if the writing to the characteristic with response is permitted.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothCharacteristicProperties/write)
     */
    readonly write: boolean;
    /**
     * The **`writeWithoutResponse`** read-only property of the BluetoothCharacteristicProperties interface returns a boolean that is true if the writing to the characteristic without response is permitted.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothCharacteristicProperties/writeWithoutResponse)
     */
    readonly writeWithoutResponse: boolean;
}

declare var BluetoothCharacteristicProperties: {
    prototype: BluetoothCharacteristicProperties;
    new(): BluetoothCharacteristicProperties;
};

interface BluetoothDeviceEventMap extends BluetoothDeviceEventHandlersEventMap, CharacteristicEventHandlersEventMap {
}

/**
 * The **`BluetoothDevice`** interface of the Web Bluetooth API represents a Bluetooth device inside a particular script execution environment.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothDevice)
 */
interface BluetoothDevice extends EventTarget, BluetoothDeviceEventHandlers, CharacteristicEventHandlers {
    /**
     * The **`BluetoothDevice.gatt`** read-only property returns a reference to the device's BluetoothRemoteGATTServer.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothDevice/gatt)
     */
    readonly gatt: BluetoothRemoteGATTServer | null;
    /**
     * The **`BluetoothDevice.id`** read-only property returns a string that uniquely identifies a device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothDevice/id)
     */
    readonly id: string;
    /**
     * The **`BluetoothDevice.name`** read-only property returns a string that provides a human-readable name for the device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothDevice/name)
     */
    readonly name: string | null;
    addEventListener<K extends keyof BluetoothDeviceEventMap>(type: K, listener: (this: BluetoothDevice, ev: BluetoothDeviceEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof BluetoothDeviceEventMap>(type: K, listener: (this: BluetoothDevice, ev: BluetoothDeviceEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var BluetoothDevice: {
    prototype: BluetoothDevice;
    new(): BluetoothDevice;
};

interface BluetoothDeviceEventHandlersEventMap {
    "gattserverdisconnected": Event;
}

/** Available only in secure contexts. */
interface BluetoothDeviceEventHandlers {
    ongattserverdisconnected: ((this: BluetoothDeviceEventHandlers, ev: Event) => any) | null;
    addEventListener<K extends keyof BluetoothDeviceEventHandlersEventMap>(type: K, listener: (this: BluetoothDeviceEventHandlers, ev: BluetoothDeviceEventHandlersEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof BluetoothDeviceEventHandlersEventMap>(type: K, listener: (this: BluetoothDeviceEventHandlers, ev: BluetoothDeviceEventHandlersEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

/**
 * The BluetoothRemoteGattCharacteristic interface of the Web Bluetooth API represents a GATT Characteristic, which is a basic data element that provides further information about a peripheral's service.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTCharacteristic)
 */
interface BluetoothRemoteGATTCharacteristic extends EventTarget, CharacteristicEventHandlers {
    /**
     * The **`BluetoothRemoteGATTCharacteristic.properties`** read-only property returns a BluetoothCharacteristicProperties instance containing the properties of this characteristic.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTCharacteristic/properties)
     */
    readonly properties: BluetoothCharacteristicProperties;
    /**
     * The **`BluetoothRemoteGATTCharacteristic.service`** read-only property returns the BluetoothRemoteGATTService this characteristic belongs to.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTCharacteristic/service)
     */
    readonly service: BluetoothRemoteGATTService;
    /**
     * The **`BluetoothRemoteGATTCharacteristic.uuid`** read-only property returns a string containing the UUID of the characteristic, for example '00002a37-0000-1000-8000-00805f9b34fb' for the Heart Rate Measurement characteristic.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTCharacteristic/uuid)
     */
    readonly uuid: UUID;
    /**
     * The **`BluetoothRemoteGATTCharacteristic.value`** read-only property returns currently cached characteristic value. This value gets updated when the value of the characteristic is read or updated via a notification or indication.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTCharacteristic/value)
     */
    readonly value: DataView<ArrayBuffer> | null;
    /**
     * The **`BluetoothRemoteGATTCharacteristic.getDescriptor()`** method returns a Promise that resolves to the first BluetoothRemoteGATTDescriptor for a given descriptor UUID.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTCharacteristic/getDescriptor)
     */
    getDescriptor(descriptor: BluetoothDescriptorUUID): Promise<BluetoothRemoteGATTDescriptor>;
    /**
     * The **`BluetoothRemoteGATTCharacteristic.getDescriptors()`** method returns a Promise that resolves to an Array of all BluetoothRemoteGATTDescriptor objects for a given descriptor UUID.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTCharacteristic/getDescriptors)
     */
    getDescriptors(descriptor?: BluetoothDescriptorUUID): Promise<BluetoothRemoteGATTDescriptor[]>;
    /**
     * The **`BluetoothRemoteGATTCharacteristic.readValue()`** method returns a Promise that resolves to a DataView holding a duplicate of the value property if it is available and supported. Otherwise it throws an error.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTCharacteristic/readValue)
     */
    readValue(): Promise<DataView<ArrayBuffer>>;
    /**
     * The **`BluetoothRemoteGATTCharacteristic.startNotifications()`** method returns a Promise to the BluetoothRemoteGATTCharacteristic instance when there is an active notification on it.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTCharacteristic/startNotifications)
     */
    startNotifications(): Promise<BluetoothRemoteGATTCharacteristic>;
    /**
     * The **`BluetoothRemoteGATTCharacteristic.stopNotifications()`** method returns a Promise to the BluetoothRemoteGATTCharacteristic instance when there is no longer an active notification on it.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTCharacteristic/stopNotifications)
     */
    stopNotifications(): Promise<BluetoothRemoteGATTCharacteristic>;
    /**
     * Use **`BluetoothRemoteGATTCharacteristic.writeValue`**WithResponse() and BluetoothRemoteGATTCharacteristic.writeValueWithoutResponse() instead.
     * @deprecated
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTCharacteristic/writeValue)
     */
    writeValue(value: BufferSource): Promise<void>;
    /**
     * The **`BluetoothRemoteGATTCharacteristic.writeValueWithResponse()`** method sets a BluetoothRemoteGATTCharacteristic object's value property to the bytes contained in a given ArrayBuffer, TypedArray, or DataView, writes the characteristic value with required response, and returns the resulting Promise.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTCharacteristic/writeValueWithResponse)
     */
    writeValueWithResponse(value: BufferSource): Promise<void>;
    /**
     * The **`BluetoothRemoteGATTCharacteristic.writeValueWithoutResponse()`** method sets a BluetoothRemoteGATTCharacteristic object's value property to the bytes contained in a given ArrayBuffer, TypedArray, or DataView, writes the characteristic value without response, and returns the resulting Promise.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTCharacteristic/writeValueWithoutResponse)
     */
    writeValueWithoutResponse(value: BufferSource): Promise<void>;
    addEventListener<K extends keyof CharacteristicEventHandlersEventMap>(type: K, listener: (this: BluetoothRemoteGATTCharacteristic, ev: CharacteristicEventHandlersEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof CharacteristicEventHandlersEventMap>(type: K, listener: (this: BluetoothRemoteGATTCharacteristic, ev: CharacteristicEventHandlersEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var BluetoothRemoteGATTCharacteristic: {
    prototype: BluetoothRemoteGATTCharacteristic;
    new(): BluetoothRemoteGATTCharacteristic;
};

/**
 * The **`BluetoothRemoteGATTDescriptor`** interface of the Web Bluetooth API provides a GATT Descriptor, which provides further information about a characteristic's value.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTDescriptor)
 */
interface BluetoothRemoteGATTDescriptor {
    /**
     * The **`BluetoothRemoteGATTDescriptor.characteristic`** read-only property returns the BluetoothRemoteGATTCharacteristic this descriptor belongs to.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTDescriptor/characteristic)
     */
    readonly characteristic: BluetoothRemoteGATTCharacteristic;
    /**
     * The **`BluetoothRemoteGATTDescriptor.uuid`** read-only property returns the UUID of the characteristic descriptor. For example "00002902-0000-1000-8000-00805f9b34fb" for the Client Characteristic Configuration descriptor.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTDescriptor/uuid)
     */
    readonly uuid: UUID;
    /**
     * The **`BluetoothRemoteGATTDescriptor.value`** read-only property returns a DataView containing the currently cached descriptor value. This value gets updated when the value of the descriptor is read.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTDescriptor/value)
     */
    readonly value: DataView<ArrayBuffer> | null;
    /**
     * The **`BluetoothRemoteGATTDescriptor.readValue()`** method returns a Promise that resolves to a DataView holding a duplicate of the value property if it is available and supported. Otherwise it throws an error.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTDescriptor/readValue)
     */
    readValue(): Promise<DataView<ArrayBuffer>>;
    /**
     * The **`BluetoothRemoteGATTDescriptor.writeValue()`** method sets the value property to the bytes contained in an ArrayBuffer, TypedArray, or DataView and returns a Promise.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTDescriptor/writeValue)
     */
    writeValue(value: BufferSource): Promise<void>;
}

declare var BluetoothRemoteGATTDescriptor: {
    prototype: BluetoothRemoteGATTDescriptor;
    new(): BluetoothRemoteGATTDescriptor;
};

/**
 * The **`BluetoothRemoteGATTServer`** interface of the Web Bluetooth API represents a GATT Server on a remote device.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTServer)
 */
interface BluetoothRemoteGATTServer {
    /**
     * The **`BluetoothRemoteGATTServer.connected`** read-only property returns a boolean value that returns true while this script execution environment is connected to this.device. It can be false while the user agent is physically connected.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTServer/connected)
     */
    readonly connected: boolean;
    /**
     * The **`BluetoothRemoteGATTServer.device`** read-only property returns a reference to the BluetoothDevice running the server.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTServer/device)
     */
    readonly device: BluetoothDevice;
    /**
     * The **`BluetoothRemoteGATTServer.connect()`** method causes the script execution environment to connect to this.device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTServer/connect)
     */
    connect(): Promise<BluetoothRemoteGATTServer>;
    /**
     * The **`BluetoothRemoteGATTServer.disconnect()`** method causes the script execution environment to disconnect from this.device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTServer/disconnect)
     */
    disconnect(): void;
    /**
     * The **`BluetoothRemoteGATTServer.getPrimaryService()`** method returns a promise to the primary BluetoothRemoteGATTService offered by the Bluetooth device for a specified bluetooth service UUID.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTServer/getPrimaryService)
     */
    getPrimaryService(service: BluetoothServiceUUID): Promise<BluetoothRemoteGATTService>;
    /**
     * The **`BluetoothRemoteGATTServer.getPrimaryServices()`** method returns a promise to a list of primary BluetoothRemoteGATTService objects offered by the Bluetooth device for a specified BluetoothServiceUUID.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTServer/getPrimaryServices)
     */
    getPrimaryServices(service?: BluetoothServiceUUID): Promise<BluetoothRemoteGATTService[]>;
}

declare var BluetoothRemoteGATTServer: {
    prototype: BluetoothRemoteGATTServer;
    new(): BluetoothRemoteGATTServer;
};

/**
 * The **`BluetoothRemoteGATTService`** interface of the Web Bluetooth API represents a service provided by a GATT server, including a device, a list of referenced services, and a list of the characteristics of this service.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTService)
 */
interface BluetoothRemoteGATTService extends EventTarget, CharacteristicEventHandlers {
    /**
     * The **`BluetoothGATTService.device`** read-only property returns information about a Bluetooth device through an instance of BluetoothDevice.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTService/device)
     */
    readonly device: BluetoothDevice;
    /**
     * The **`BluetoothGATTService.isPrimary`** read-only property returns a boolean value that indicates whether this is a primary service. If it is not a primary service, it is a secondary service.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTService/isPrimary)
     */
    readonly isPrimary: boolean;
    /**
     * The **`BluetoothGATTService.uuid`** read-only property returns a string representing the UUID of this service.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTService/uuid)
     */
    readonly uuid: UUID;
    /**
     * The **`BluetoothGATTService.getCharacteristic()`** method returns a Promise to an instance of BluetoothRemoteGATTCharacteristic for a given universally unique identifier (UUID).
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTService/getCharacteristic)
     */
    getCharacteristic(characteristic: BluetoothCharacteristicUUID): Promise<BluetoothRemoteGATTCharacteristic>;
    /**
     * The **`BluetoothGATTService.getCharacteristics()`** method returns a Promise to a list of BluetoothRemoteGATTCharacteristic instances for a given universally unique identifier (UUID).
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothRemoteGATTService/getCharacteristics)
     */
    getCharacteristics(characteristic?: BluetoothCharacteristicUUID): Promise<BluetoothRemoteGATTCharacteristic[]>;
    addEventListener<K extends keyof CharacteristicEventHandlersEventMap>(type: K, listener: (this: BluetoothRemoteGATTService, ev: CharacteristicEventHandlersEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof CharacteristicEventHandlersEventMap>(type: K, listener: (this: BluetoothRemoteGATTService, ev: CharacteristicEventHandlersEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var BluetoothRemoteGATTService: {
    prototype: BluetoothRemoteGATTService;
    new(): BluetoothRemoteGATTService;
};

/**
 * The **`BluetoothUUID`** interface of the Web Bluetooth API provides a way to look up Universally Unique Identifier (UUID) values by name in the registry maintained by the Bluetooth SIG.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothUUID)
 */
interface BluetoothUUID {
}

declare var BluetoothUUID: {
    prototype: BluetoothUUID;
    new(): BluetoothUUID;
    /**
     * The **`canonicalUUID()`** static method of the BluetoothUUID interface returns the 128-bit UUID when passed a 16- or 32-bit UUID alias.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothUUID/canonicalUUID_static)
     */
    canonicalUUID(alias: number): UUID;
    /**
     * The **`getCharacteristic()`** static method of the BluetoothUUID interface returns a UUID representing a registered characteristic when passed a name or the 16- or 32-bit UUID alias.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothUUID/getCharacteristic_static)
     */
    getCharacteristic(name: string | number): UUID;
    /**
     * The **`getDescriptor()`** static method of the BluetoothUUID interface returns a UUID representing a registered descriptor when passed a name or the 16- or 32-bit UUID alias.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothUUID/getDescriptor_static)
     */
    getDescriptor(name: string | number): UUID;
    /**
     * The **`getService()`** static method of the BluetoothUUID interface returns a UUID representing a registered service when passed a name or the 16- or 32-bit UUID alias.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/BluetoothUUID/getService_static)
     */
    getService(name: string | number): UUID;
};

interface CharacteristicEventHandlersEventMap {
    "characteristicvaluechanged": Event;
}

/** Available only in secure contexts. */
interface CharacteristicEventHandlers {
    oncharacteristicvaluechanged: ((this: CharacteristicEventHandlers, ev: Event) => any) | null;
    addEventListener<K extends keyof CharacteristicEventHandlersEventMap>(type: K, listener: (this: CharacteristicEventHandlers, ev: CharacteristicEventHandlersEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof CharacteristicEventHandlersEventMap>(type: K, listener: (this: CharacteristicEventHandlers, ev: CharacteristicEventHandlersEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

interface Navigator {
    /**
     * The **`bluetooth`** read-only property of the Navigator interface returns a Bluetooth object for the current document, providing access to Web Bluetooth API functionality.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Navigator/bluetooth)
     */
    readonly bluetooth: Bluetooth;
}

type BluetoothCharacteristicUUID = string | number;

type BluetoothDescriptorUUID = string | number;

type UUID = string;
