// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Spec: web-animations-2

interface AnimationTriggerOptions {
    behavior?: AnimationTriggerBehavior | null;
    exitRangeEnd?: TimelineRangeOffset | CSSNumericValue | CSSKeywordValue | string;
    exitRangeStart?: TimelineRangeOffset | CSSNumericValue | CSSKeywordValue | string;
    rangeEnd?: TimelineRangeOffset | CSSNumericValue | CSSKeywordValue | string;
    rangeStart?: TimelineRangeOffset | CSSNumericValue | CSSKeywordValue | string;
    timeline?: AnimationTimeline | null;
}

interface KeyframeAnimationOptions {
    trigger?: AnimationTrigger | null;
}

interface AnimationTrigger {
}

declare var AnimationTrigger: {
    prototype: AnimationTrigger;
    new(options?: AnimationTriggerOptions): AnimationTrigger;
};

type AnimationTriggerBehavior = "alternate" | "once" | "repeat" | "state";
