// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: dom. Spec: web-nfc

interface NDEFMakeReadOnlyOptions {
    signal?: AbortSignal | null;
}

interface NDEFMessageInit {
    records: NDEFRecordInit[];
}

interface NDEFReadingEventInit extends EventInit {
    message: NDEFMessageInit;
    serialNumber?: string | null;
}

interface NDEFRecordInit {
    data?: any;
    encoding?: string;
    id?: string;
    lang?: string;
    mediaType?: string;
    recordType: string;
}

interface NDEFScanOptions {
    signal?: AbortSignal;
}

interface NDEFWriteOptions {
    overwrite?: boolean;
    signal?: AbortSignal | null;
}

/**
 * The **`NDEFMessage`** interface of the Web NFC API represents the content of an NDEF message that has been read from or could be written to an NFC tag. An instance is acquired by calling the NDEFMessage() constructor or from the NDEFReadingEvent.message property, which is passed to the reading event.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/NDEFMessage)
 */
interface NDEFMessage {
    /**
     * The **`records`** property of NDEFMessage interface represents a list of NDEFRecords present in the NDEF message.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/NDEFMessage/records)
     */
    readonly records: ReadonlyArray<NDEFRecord>;
}

declare var NDEFMessage: {
    prototype: NDEFMessage;
    new(messageInit: NDEFMessageInit): NDEFMessage;
};

interface NDEFReaderEventMap {
    "reading": NDEFReadingEvent;
    "readingerror": Event;
}

/**
 * The **`NDEFReader`** interface of the Web NFC API is used to read from and write data to compatible NFC devices, e.g., NFC tags supporting NDEF, when these devices are within the reader's magnetic induction field.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/NDEFReader)
 */
interface NDEFReader extends EventTarget {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/NDEFReader/reading_event) */
    onreading: ((this: NDEFReader, ev: NDEFReadingEvent) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/NDEFReader/readingerror_event) */
    onreadingerror: ((this: NDEFReader, ev: Event) => any) | null;
    makeReadOnly(options?: NDEFMakeReadOnlyOptions): Promise<void>;
    /**
     * The **`scan()`** method of the NDEFReader interface activates a reading device and returns a Promise that either resolves when an NFC tag read operation is scheduled or rejects if a hardware or permission error is encountered. This method triggers a permission prompt if the "nfc" permission has not been previously granted.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/NDEFReader/scan)
     */
    scan(options?: NDEFScanOptions): Promise<void>;
    /**
     * The **`write()`** method of the NDEFReader interface attempts to write an NDEF message to a tag and returns a Promise that either resolves when a message has been written to the tag or rejects if a hardware or permission error is encountered. This method triggers a permission prompt if the "nfc" permission has not been previously granted.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/NDEFReader/write)
     */
    write(message: NDEFMessageSource, options?: NDEFWriteOptions): Promise<void>;
    addEventListener<K extends keyof NDEFReaderEventMap>(type: K, listener: (this: NDEFReader, ev: NDEFReaderEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof NDEFReaderEventMap>(type: K, listener: (this: NDEFReader, ev: NDEFReaderEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var NDEFReader: {
    prototype: NDEFReader;
    new(): NDEFReader;
};

/**
 * The **`NDEFReadingEvent`** interface of the Web NFC API represents events dispatched on new NFC readings obtained by NDEFReader.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/NDEFReadingEvent)
 */
interface NDEFReadingEvent extends Event {
    /**
     * The **`message`** property of the NDEFReadingEvent interface returns an NDEFMessage object containing the received message.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/NDEFReadingEvent/message)
     */
    readonly message: NDEFMessage;
    /**
     * The **`serialNumber`** property of the NDEFReadingEvent interface returns the serial number of the device, which is used for anti-collision and identification, or an empty string if no serial number is available.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/NDEFReadingEvent/serialNumber)
     */
    readonly serialNumber: string;
}

declare var NDEFReadingEvent: {
    prototype: NDEFReadingEvent;
    new(type: string, readingEventInitDict: NDEFReadingEventInit): NDEFReadingEvent;
};

/**
 * The **`NDEFRecord`** interface of the Web NFC API provides data that can be read from, or written to, compatible NFC devices, e.g., NFC tags supporting NDEF.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/NDEFRecord)
 */
interface NDEFRecord {
    /**
     * The **`data`** property of the NDEFRecord interface returns a DataView containing the raw bytes of the record's payload.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/NDEFRecord/data)
     */
    readonly data: DataView<ArrayBuffer> | null;
    /**
     * The **`encoding`** property of the NDEFRecord interface returns the encoding of a textual payload, or null otherwise.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/NDEFRecord/encoding)
     */
    readonly encoding: string | null;
    /**
     * The **`id`** property of the NDEFRecord interface returns the record identifier, which is an absolute or relative URL used to identify the record.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/NDEFRecord/id)
     */
    readonly id: string | null;
    /**
     * The **`lang`** property of the NDEFRecord interface returns the language of a textual payload, or null if one was not supplied.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/NDEFRecord/lang)
     */
    readonly lang: string | null;
    /**
     * The **`mediaType`** property of the NDEFRecord interface returns the MIME type of the record. This value will be null if recordType is not equal to "mime".
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/NDEFRecord/mediaType)
     */
    readonly mediaType: string | null;
    /**
     * The **`recordType`** property of the NDEFRecord interface returns the record type of the record.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/NDEFRecord/recordType)
     */
    readonly recordType: string;
    /**
     * The **`toRecords()`** method of the NDEFRecord interface converts NDEFRecord.data to a sequence of records based on NDEFRecord.recordType, and returns the result. This allows parsing the payloads of record types which may contain nested records, such as smart poster and external type records.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/NDEFRecord/toRecords)
     */
    toRecords(): NDEFRecord[] | null;
}

declare var NDEFRecord: {
    prototype: NDEFRecord;
    new(recordInit: NDEFRecordInit): NDEFRecord;
};

type NDEFMessageSource = string | BufferSource | NDEFMessageInit;
