// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: webworker. Spec: web-based-payment-handler

interface AddressInit {
    addressLine?: string[];
    city?: string;
    country?: string;
    dependentLocality?: string;
    organization?: string;
    phone?: string;
    postalCode?: string;
    recipient?: string;
    region?: string;
    sortingCode?: string;
}

interface PaymentHandlerResponse {
    details?: any;
    methodName?: string;
    payerEmail?: string | null;
    payerName?: string | null;
    payerPhone?: string | null;
    shippingAddress?: AddressInit;
    shippingOption?: string | null;
}

interface PaymentRequestDetailsUpdate {
    error?: string;
    modifiers?: PaymentDetailsModifier[];
    paymentMethodErrors?: any;
    shippingAddressErrors?: AddressErrors;
    shippingOptions?: PaymentShippingOption[];
    total?: PaymentCurrencyAmount;
}

interface PaymentRequestEventInit extends ExtendableEventInit {
    methodData?: PaymentMethodData[];
    modifiers?: PaymentDetailsModifier[];
    paymentOptions?: PaymentOptions;
    paymentRequestId?: string;
    paymentRequestOrigin?: string;
    shippingOptions?: PaymentShippingOption[];
    topOrigin?: string;
    total?: PaymentCurrencyAmount;
}

/**
 * The **`CanMakePaymentEvent`** interface of the Web-based Payment Handler API is the event object for the canmakepayment event, fired on a payment app's service worker to check whether it is ready to handle a payment. Specifically, it is fired when the merchant website calls the PaymentRequest() constructor.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CanMakePaymentEvent)
 */
interface CanMakePaymentEvent extends ExtendableEvent {
    /**
     * The **`respondWith()`** method of the CanMakePaymentEvent interface enables the service worker to respond appropriately to signal whether it is ready to handle payments.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CanMakePaymentEvent/respondWith)
     */
    respondWith(canMakePaymentResponse: boolean | PromiseLike<boolean>): void;
}

declare var CanMakePaymentEvent: {
    prototype: CanMakePaymentEvent;
    new(type: string): CanMakePaymentEvent;
};

/**
 * The **`PaymentRequestEvent`** interface of the Web-based Payment Handler API is the object passed to a payment handler when a PaymentRequest is made.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PaymentRequestEvent)
 */
interface PaymentRequestEvent extends ExtendableEvent {
    /**
     * The **`methodData`** read-only property of the PaymentRequestEvent interface returns an array of PaymentMethodData objects containing payment method identifiers for the payment methods that the website accepts and any associated payment method-specific data.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PaymentRequestEvent/methodData)
     */
    readonly methodData: ReadonlyArray<PaymentMethodData>;
    /**
     * The **`modifiers`** read-only property of the PaymentRequestEvent interface returns an Array of PaymentDetailsModifier objects containing modifiers for payment details.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PaymentRequestEvent/modifiers)
     */
    readonly modifiers: ReadonlyArray<PaymentDetailsModifier>;
    readonly paymentOptions: any;
    /**
     * The **`paymentRequestId`** read-only property of the PaymentRequestEvent interface returns the ID of the PaymentRequest object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PaymentRequestEvent/paymentRequestId)
     */
    readonly paymentRequestId: string;
    /**
     * The **`paymentRequestOrigin`** read-only property of the PaymentRequestEvent interface returns the origin where the PaymentRequest object was initialized.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PaymentRequestEvent/paymentRequestOrigin)
     */
    readonly paymentRequestOrigin: string;
    readonly shippingOptions: ReadonlyArray<PaymentShippingOption> | null;
    /**
     * The **`topOrigin`** read-only property of the PaymentRequestEvent interface returns the top-level payee origin where the PaymentRequest object was initialized.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PaymentRequestEvent/topOrigin)
     */
    readonly topOrigin: string;
    /**
     * The **`total`** read-only property of the PaymentRequestEvent interface returns a PaymentCurrencyAmount object containing the total amount being requested for payment.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PaymentRequestEvent/total)
     */
    readonly total: any;
    /**
     * The **`changePaymentMethod()`** method of the PaymentRequestEvent interface is used by the payment handler to get an updated total, given such payment method details as the billing address.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PaymentRequestEvent/changePaymentMethod)
     */
    changePaymentMethod(methodName: string, methodDetails?: any): Promise<PaymentRequestDetailsUpdate | null>;
    changeShippingAddress(shippingAddress?: AddressInit): Promise<PaymentRequestDetailsUpdate | null>;
    changeShippingOption(shippingOption: string): Promise<PaymentRequestDetailsUpdate | null>;
    /**
     * The **`openWindow()`** method of the PaymentRequestEvent interface opens the specified URL in a new window, only if the given URL is on the same origin as the calling page. It returns a Promise that resolves with a reference to a WindowClient.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PaymentRequestEvent/openWindow)
     */
    openWindow(url: string | URL): Promise<WindowClient | null>;
    /**
     * The **`respondWith()`** method of the PaymentRequestEvent interface prevents the default event handling and allows you to provide a Promise for a payment handler response object yourself.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/PaymentRequestEvent/respondWith)
     */
    respondWith(handlerResponsePromise: PaymentHandlerResponse | PromiseLike<PaymentHandlerResponse>): void;
}

declare var PaymentRequestEvent: {
    prototype: PaymentRequestEvent;
    new(type: string, eventInitDict?: PaymentRequestEventInit): PaymentRequestEvent;
};

interface ServiceWorkerGlobalScope {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/ServiceWorkerGlobalScope/canmakepayment_event) */
    oncanmakepayment: ((this: ServiceWorkerGlobalScope, ev: CanMakePaymentEvent) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/ServiceWorkerGlobalScope/paymentrequest_event) */
    onpaymentrequest: ((this: ServiceWorkerGlobalScope, ev: PaymentRequestEvent) => any) | null;
}

interface ServiceWorkerRegistration {
    /**
     * The **`paymentManager`** read-only property of the ServiceWorkerRegistration interface returns a payment app's PaymentManager instance, which is used to manage various payment app functionality.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ServiceWorkerRegistration/paymentManager)
     */
    readonly paymentManager: any;
}
