// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: dom. Spec: web-app-launch

/**
 * The **`LaunchParams`** interface of the Launch Handler API is used when implementing custom launch navigation handling in a PWA. When window.launchQueue.setConsumer() is invoked to set up the launch navigation handling functionality, the callback function inside setConsumer() is passed a LaunchParams object instance.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/LaunchParams)
 */
interface LaunchParams {
    /**
     * The **`files`** read-only property of the LaunchParams interface returns an array of FileSystemHandle objects representing any files passed along with the launch navigation via the POST method.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/LaunchParams/files)
     */
    readonly files: ReadonlyArray<FileSystemHandle>;
    /**
     * The **`targetURL`** read-only property of the LaunchParams interface returns the target URL of the associated web app launch.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/LaunchParams/targetURL)
     */
    readonly targetURL: string | null;
}

declare var LaunchParams: {
    prototype: LaunchParams;
    new(): LaunchParams;
};

/**
 * The **`LaunchQueue`** interface of the Launch Handler API is available via the Window.launchQueue property. When a progressive web app (PWA) is launched with a launch_handler client_mode value of focus-existing, navigate-new, or navigate-existing, LaunchQueue provides access to functionality that allows custom launch navigation handling to be implemented in the PWA. This functionality is controlled by the properties of the LaunchParams object passed into the setConsumer() callback function.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/LaunchQueue)
 */
interface LaunchQueue {
    /**
     * The **`setConsumer()`** method of the LaunchQueue interface is used to declare the callback that will handle custom launch navigation handling in a progressive web app (PWA). Such custom navigation is initiated via Window.launchQueue when a PWA has been launched with a launch_handler client_mode value of focus-existing, navigate-new, or navigate-existing.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/LaunchQueue/setConsumer)
     */
    setConsumer(consumer: LaunchConsumer): void;
}

declare var LaunchQueue: {
    prototype: LaunchQueue;
    new(): LaunchQueue;
};

interface Window {
    /**
     * The **`launchQueue`** read-only property of the Window interface provides access to the LaunchQueue class, which allows custom launch navigation handling to be implemented in a progressive web app (PWA), with the handling context signified by the launch_handler manifest field client_mode value.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Window/launchQueue)
     */
    readonly launchQueue: LaunchQueue;
}

interface LaunchConsumer {
    (params: LaunchParams): any;
}
