// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Spec: webaudio

interface AudioSinkOptions {
    type: AudioSinkType;
}

interface MediaStreamTrackAudioSourceOptions {
    mediaStreamTrack: MediaStreamTrack;
}

interface AudioContextEventMap extends BaseAudioContextEventMap {
    "error": Event;
    "sinkchange": Event;
}

interface AudioContext {
    onerror: ((this: AudioContext, ev: Event) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/AudioContext/sinkchange_event) */
    onsinkchange: ((this: AudioContext, ev: Event) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/AudioContext/playbackStats) */
    readonly playbackStats: AudioPlaybackStats;
    /**
     * The **`sinkId`** read-only property of the AudioContext interface returns the sink ID of the current output audio device.
     * Available only in secure contexts.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/AudioContext/sinkId)
     */
    readonly sinkId: string | AudioSinkInfo;
    /**
     * The **`createMediaStreamTrackSource()`** method of the AudioContext interface creates and returns a MediaStreamTrackAudioSourceNode which represents an audio source whose data comes from the specified MediaStreamTrack.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/AudioContext/createMediaStreamTrackSource)
     */
    createMediaStreamTrackSource(mediaStreamTrack: MediaStreamTrack): MediaStreamTrackAudioSourceNode;
    /**
     * The **`setSinkId()`** method of the AudioContext interface sets the output audio device for the AudioContext. If a sink ID is not explicitly set, the default system audio output device will be used.
     * Available only in secure contexts.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/AudioContext/setSinkId)
     */
    setSinkId(sinkId: string | AudioSinkOptions): Promise<void>;
    addEventListener<K extends keyof AudioContextEventMap>(type: K, listener: (this: AudioContext, ev: AudioContextEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof AudioContextEventMap>(type: K, listener: (this: AudioContext, ev: AudioContextEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
}

/**
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/AudioPlaybackStats)
 */
interface AudioPlaybackStats {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/AudioPlaybackStats/averageLatency) */
    readonly averageLatency: number;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/AudioPlaybackStats/maximumLatency) */
    readonly maximumLatency: number;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/AudioPlaybackStats/minimumLatency) */
    readonly minimumLatency: number;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/AudioPlaybackStats/totalDuration) */
    readonly totalDuration: number;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/AudioPlaybackStats/underrunDuration) */
    readonly underrunDuration: number;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/AudioPlaybackStats/underrunEvents) */
    readonly underrunEvents: number;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/AudioPlaybackStats/resetLatency) */
    resetLatency(): void;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/AudioPlaybackStats/toJSON) */
    toJSON(): any;
}

declare var AudioPlaybackStats: {
    prototype: AudioPlaybackStats;
    new(): AudioPlaybackStats;
};

/**
 * The **`AudioSinkInfo`** interface of the Web Audio API represents information describing an AudioContext's sink ID, retrieved via AudioContext.sinkId.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/AudioSinkInfo)
 */
interface AudioSinkInfo {
    /**
     * The **`type`** read-only property of the AudioSinkInfo interface returns the type of the audio output device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/AudioSinkInfo/type)
     */
    readonly type: AudioSinkType;
}

declare var AudioSinkInfo: {
    prototype: AudioSinkInfo;
    new(): AudioSinkInfo;
};

interface AudioWorklet {
    /**
     * The **`port`** read-only property of the AudioWorklet interface returns a MessagePort object that can be used to send and receive messages between the main thread and the associated AudioWorkletGlobalScope.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/AudioWorklet/port)
     */
    readonly port: MessagePort;
}

/**
 * The **`MediaStreamTrackAudioSourceNode`** interface is a type of AudioNode which represents a source of audio data taken from a specific MediaStreamTrack obtained through the WebRTC or Media Capture and Streams APIs.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/MediaStreamTrackAudioSourceNode)
 */
interface MediaStreamTrackAudioSourceNode extends AudioNode {
}

declare var MediaStreamTrackAudioSourceNode: {
    prototype: MediaStreamTrackAudioSourceNode;
    new(context: AudioContext, options: MediaStreamTrackAudioSourceOptions): MediaStreamTrackAudioSourceNode;
};

type AudioSinkType = "none";
