// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: window. Spec: webcodecs

interface VideoFrameMetadata {
}

interface VideoFrame {
    /**
     * The **`flip`** property of the VideoFrame interface returns a boolean that indicates whether the VideoFrame is horizontally mirrored.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/VideoFrame/flip)
     */
    readonly flip: boolean;
    /**
     * The **`rotation`** property of the VideoFrame interface returns the rotation of the video frame.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/VideoFrame/rotation)
     */
    readonly rotation: number;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/VideoFrame/metadata) */
    metadata(): VideoFrameMetadata;
}
