// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: webworker. Spec: webgpu

interface GPUTexture {
    readonly textureBindingViewDimension: GPUTextureViewDimension | undefined;
}
