// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Spec: webhid

interface HIDCollectionInfo {
    children?: HIDCollectionInfo[];
    featureReports?: HIDReportInfo[];
    inputReports?: HIDReportInfo[];
    outputReports?: HIDReportInfo[];
    type?: number;
    usage?: number;
    usagePage?: number;
}

interface HIDConnectionEventInit extends EventInit {
    device: HIDDevice;
}

interface HIDDeviceFilter {
    productId?: number;
    usage?: number;
    usagePage?: number;
    vendorId?: number;
}

interface HIDDeviceRequestOptions {
    exclusionFilters?: HIDDeviceFilter[];
    filters: HIDDeviceFilter[];
}

interface HIDInputReportEventInit extends EventInit {
    data: DataView<ArrayBuffer>;
    device: HIDDevice;
    reportId: number;
}

interface HIDReportInfo {
    items?: HIDReportItem[];
    reportId?: number;
}

interface HIDReportItem {
    hasNull?: boolean;
    hasPreferredState?: boolean;
    isAbsolute?: boolean;
    isArray?: boolean;
    isBufferedBytes?: boolean;
    isConstant?: boolean;
    isLinear?: boolean;
    isRange?: boolean;
    isVolatile?: boolean;
    logicalMaximum?: number;
    logicalMinimum?: number;
    physicalMaximum?: number;
    physicalMinimum?: number;
    reportCount?: number;
    reportSize?: number;
    strings?: string[];
    unitExponent?: number;
    unitFactorCurrentExponent?: number;
    unitFactorLengthExponent?: number;
    unitFactorLuminousIntensityExponent?: number;
    unitFactorMassExponent?: number;
    unitFactorTemperatureExponent?: number;
    unitFactorTimeExponent?: number;
    unitSystem?: HIDUnitSystem;
    usageMaximum?: number;
    usageMinimum?: number;
    usages?: number[];
    wrap?: boolean;
}

interface HIDEventMap {
    "connect": HIDConnectionEvent;
    "disconnect": HIDConnectionEvent;
}

/**
 * The **`HID`** interface provides methods for connecting to HID devices, listing attached HID devices and event handlers for connected HID devices.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/HID)
 */
interface HID extends EventTarget {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/HID/connect_event) */
    onconnect: ((this: HID, ev: HIDConnectionEvent) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/HID/disconnect_event) */
    ondisconnect: ((this: HID, ev: HIDConnectionEvent) => any) | null;
    /**
     * The **`getDevices()`** method of the HID interface gets a list of connected HID devices that the user has previously been granted access to in response to a requestDevice() call.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/HID/getDevices)
     */
    getDevices(): Promise<HIDDevice[]>;
    /**
     * The **`requestDevice()`** method of the HID interface requests access to a HID device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/HID/requestDevice)
     */
    requestDevice(options: HIDDeviceRequestOptions): Promise<HIDDevice[]>;
    addEventListener<K extends keyof HIDEventMap>(type: K, listener: (this: HID, ev: HIDEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof HIDEventMap>(type: K, listener: (this: HID, ev: HIDEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var HID: {
    prototype: HID;
    new(): HID;
};

/**
 * The **`HIDConnectionEvent`** interface of the WebHID API represents HID connection events, and is the event type passed to connect and disconnect event handlers when a device's connection state changes.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/HIDConnectionEvent)
 */
interface HIDConnectionEvent extends Event {
    /**
     * The **`device`** read-only property of the HIDConnectionEvent interface returns the HIDDevice associated with this connection event.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/HIDConnectionEvent/device)
     */
    readonly device: HIDDevice;
}

declare var HIDConnectionEvent: {
    prototype: HIDConnectionEvent;
    new(type: string, eventInitDict: HIDConnectionEventInit): HIDConnectionEvent;
};

interface HIDDeviceEventMap {
    "inputreport": HIDInputReportEvent;
}

/**
 * The **`HIDDevice`** interface of the WebHID API represents a HID Device. It provides properties for accessing information about the device, methods for opening and closing the connection, and the sending and receiving of reports.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/HIDDevice)
 */
interface HIDDevice extends EventTarget {
    /**
     * The **`collections`** read-only property of the HIDDevice interface returns an array of report formats
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/HIDDevice/collections)
     */
    readonly collections: ReadonlyArray<HIDCollectionInfo>;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/HIDDevice/inputreport_event) */
    oninputreport: ((this: HIDDevice, ev: HIDInputReportEvent) => any) | null;
    /**
     * The **`opened`** read-only property of the HIDDevice interface returns true if the connection to the HIDDevice is open and ready to transfer data.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/HIDDevice/opened)
     */
    readonly opened: boolean;
    /**
     * The **`productId`** read-only property of the HIDDevice interface returns the product ID of the connected HID device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/HIDDevice/productId)
     */
    readonly productId: number;
    /**
     * The **`productName`** read-only property of the HIDDevice interface returns the product name of the connected HID device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/HIDDevice/productName)
     */
    readonly productName: string;
    /**
     * The **`vendorId`** read-only property of the HIDDevice interface returns the vendor ID of the connected HID device. This identifies the vendor of the device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/HIDDevice/vendorId)
     */
    readonly vendorId: number;
    /**
     * The **`close()`** method of the HIDDevice interface closes the connection to the HID device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/HIDDevice/close)
     */
    close(): Promise<void>;
    /**
     * The **`forget()`** method of the HIDDevice interface closes the connection to the HID device and forgets the device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/HIDDevice/forget)
     */
    forget(): Promise<void>;
    /**
     * The **`open()`** method of the HIDDevice interface requests that the operating system opens the HID device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/HIDDevice/open)
     */
    open(): Promise<void>;
    /**
     * The **`receiveFeatureReport()`** method of the HIDDevice interface receives a feature report from the HID device. Feature reports are a way for HID devices and applications to exchange non-standardized HID data.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/HIDDevice/receiveFeatureReport)
     */
    receiveFeatureReport(reportId: number): Promise<DataView<ArrayBuffer>>;
    /**
     * The **`sendFeatureReport()`** method of the HIDDevice interface sends a feature report to the HID device. Feature reports are a way for HID devices and applications to exchange non-standardized HID data.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/HIDDevice/sendFeatureReport)
     */
    sendFeatureReport(reportId: number, data: BufferSource): Promise<void>;
    /**
     * The **`sendReport()`** method of the HIDDevice interface sends an output report to the HID device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/HIDDevice/sendReport)
     */
    sendReport(reportId: number, data: BufferSource): Promise<void>;
    addEventListener<K extends keyof HIDDeviceEventMap>(type: K, listener: (this: HIDDevice, ev: HIDDeviceEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof HIDDeviceEventMap>(type: K, listener: (this: HIDDevice, ev: HIDDeviceEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var HIDDevice: {
    prototype: HIDDevice;
    new(): HIDDevice;
};

/**
 * The **`HIDInputReportEvent`** interface of the WebHID API is passed to inputreport event of HIDDevice when an input report is received from any associated HID device.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/HIDInputReportEvent)
 */
interface HIDInputReportEvent extends Event {
    /**
     * The **`data`** property of the HIDInputReportEvent interface returns a DataView containing the data from the input report, excluding the reportId if the HID interface uses report IDs.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/HIDInputReportEvent/data)
     */
    readonly data: DataView<ArrayBuffer>;
    /**
     * The **`device`** property of the HIDInputReportEvent interface returns the HIDDevice instance that represents the HID interface that sent the input report.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/HIDInputReportEvent/device)
     */
    readonly device: HIDDevice;
    /**
     * The **`reportId`** property of the HIDInputReportEvent interface returns the one-byte identification prefix for this report, or 0 if the HID interface does not use report IDs.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/HIDInputReportEvent/reportId)
     */
    readonly reportId: number;
}

declare var HIDInputReportEvent: {
    prototype: HIDInputReportEvent;
    new(type: string, eventInitDict: HIDInputReportEventInit): HIDInputReportEvent;
};

interface Navigator {
    /**
     * The **`Navigator.hid`** read-only property returns an HID object providing methods for accessing HID device connections and events that fire when the user agent connects to or disconnects from a device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Navigator/hid)
     */
    readonly hid: HID;
}

type HIDUnitSystem = "english-linear" | "english-rotation" | "none" | "reserved" | "si-linear" | "si-rotation" | "vendor-defined";
