// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: worker. Spec: webidl

interface QuotaExceededErrorOptions {
    quota?: number;
    requested?: number;
}

/**
 * The **`QuotaExceededError`** interface represents an error when a requested operation would exceed a system-imposed storage quota.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/QuotaExceededError)
 */
interface QuotaExceededError extends DOMException {
    /**
     * The **`quota`** read-only property of the QuotaExceededError interface returns the system-defined storage quota (in bytes) that the operation attempted to exceed, or undefined if the information is not available.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/QuotaExceededError/quota)
     */
    readonly quota: number | null;
    /**
     * The **`requested`** read-only property of the QuotaExceededError interface returns the number of bytes that were requested when the error occurred, or undefined if the information is not available.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/QuotaExceededError/requested)
     */
    readonly requested: number | null;
}

declare var QuotaExceededError: {
    prototype: QuotaExceededError;
    new(message?: string, options?: QuotaExceededErrorOptions): QuotaExceededError;
};
