// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: webworker. Spec: webrtc-priority

interface RTCDataChannel {
    /**
     * The read-only **`priority`** property of the RTCDataChannel interface returns a string indicating the priority of the data channel. The priority is assigned by the user agent at channel creation time based on the priority option in the dataChannelDict parameter passed to RTCPeerConnection.createDataChannel(), or from the remote peer for incoming data channels.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/RTCDataChannel/priority)
     */
    readonly priority: RTCPriorityType;
}

type RTCPriorityType = "high" | "low" | "medium" | "very-low";
