// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: window. Spec: webrtc-identity

interface RTCIdentityProviderOptions {
    peerIdentity?: string;
    protocol?: string;
    usernameHint?: string;
}

interface RTCError {
    readonly httpRequestStatusCode: number | null;
}

/**
 * The **`RTCIdentityAssertion`** interface of the WebRTC API represents the identity of a remote peer of the current connection. If no peer has yet been set and verified, then this interface returns null. Once set it can't be changed.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/RTCIdentityAssertion)
 */
interface RTCIdentityAssertion {
    /**
     * The **`idp`** property of the RTCIdentityAssertion interface indicates the domain name of the identity provider (IdP) that validated the identity assertion (a verified claim of the remote peer's identity).
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/RTCIdentityAssertion/idp)
     */
    idp: string;
    /**
     * The **`name`** property of the RTCIdentityAssertion interface indicates the verified peer identity. It is a string in an email address-like format (for example, user@example.com), as defined by RFC 5322.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/RTCIdentityAssertion/name)
     */
    name: string;
}

declare var RTCIdentityAssertion: {
    prototype: RTCIdentityAssertion;
    new(idp: string, name: string): RTCIdentityAssertion;
};

interface RTCPeerConnection {
    /**
     * The **`idpLoginUrl`** read-only property of the RTCPeerConnection interface returns a string containing the URL endpoint the application can open to log users in to the identity provider (IdP). This value is null until the IdP indicates that login is needed.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/RTCPeerConnection/idpLoginUrl)
     */
    readonly idpLoginUrl: string | null;
    /**
     * The **`peerIdentity`** read-only property of the RTCPeerConnection interface returns a JavaScript Promise that resolves to an RTCIdentityAssertion which contains a string identifying the remote peer. Once this promise resolves successfully, the resulting identity is the target peer identity and cannot change for the duration of the connection.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/RTCPeerConnection/peerIdentity)
     */
    readonly peerIdentity: Promise<RTCIdentityAssertion>;
    /**
     * The **`getIdentityAssertion()`** method of the RTCPeerConnection interface initiates the gathering of an identity assertion. This has an effect only if the signalingState is not "closed".
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/RTCPeerConnection/getIdentityAssertion)
     */
    getIdentityAssertion(): Promise<string>;
    /**
     * The **`setIdentityProvider()`** method of the RTCPeerConnection interface sets the Identity Provider (IdP) to the triplet given in parameter: its name, the protocol used to communicate with it (optional) and an optional username. The IdP will be used only when an assertion is needed.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/RTCPeerConnection/setIdentityProvider)
     */
    setIdentityProvider(provider: string, options?: RTCIdentityProviderOptions): void;
}
