// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: dom. Spec: webrtc

interface RTCIceParameters {
    iceLite?: boolean;
    password?: string;
    usernameFragment?: string;
}

interface RTCIceCandidate {
    readonly relayProtocol: RTCIceServerTransportProtocol | null;
    readonly url: string | null;
}

interface RTCIceTransport {
    /**
     * The **`getLocalCandidates()`** method of the RTCIceTransport interface returns an array of RTCIceCandidate objects, one for each of the candidates that have been gathered by the local device during the current ICE agent session.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/RTCIceTransport/getLocalCandidates)
     */
    getLocalCandidates(): RTCIceCandidate[];
    /**
     * The **`getLocalParameters()`** method of the RTCIceTransport interface returns an RTCIceParameters object that provides information uniquely identifying the local peer for the duration of the ICE session.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/RTCIceTransport/getLocalParameters)
     */
    getLocalParameters(): RTCIceParameters | null;
    /**
     * The **`getRemoteCandidates()`** method of the RTCIceTransport interface returns an array that contains one RTCIceCandidate for each of the candidates that have been received from the remote peer so far during the current ICE gathering session.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/RTCIceTransport/getRemoteCandidates)
     */
    getRemoteCandidates(): RTCIceCandidate[];
    /**
     * The **`getRemoteParameters()`** method of the RTCIceTransport interface returns an RTCIceParameters object that provides information uniquely identifying the remote peer for the duration of the ICE session.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/RTCIceTransport/getRemoteParameters)
     */
    getRemoteParameters(): RTCIceParameters | null;
}

interface RTCPeerConnectionIceEvent {
    /**
     * The read-only **`url`** property of the RTCPeerConnectionIceEvent interface returns the URL of the STUN or TURN server used to gather the ICE candidate that caused the event. If the candidate was not gathered from a STUN or TURN server, the value is null.
     * @deprecated
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/RTCPeerConnectionIceEvent/url)
     */
    readonly url: string | null;
}

type RTCIceServerTransportProtocol = "tcp" | "tls" | "udp";
