// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: dom. Spec: webtransport

interface WebTransportSendOptions {
    sendGroup?: WebTransportSendGroup | null;
}

interface WebTransport {
    anticipatedConcurrentIncomingBidirectionalStreams: number | null;
    anticipatedConcurrentIncomingUnidirectionalStreams: number | null;
    readonly draining: Promise<void>;
    createSendGroup(): WebTransportSendGroup;
}

interface WebTransportDatagramDuplexStream {
    createWritable(options?: WebTransportSendOptions): WebTransportDatagramsWritable;
}

/** Available only in secure contexts. */
interface WebTransportDatagramsWritable extends WritableStream {
    sendGroup: WebTransportSendGroup | null;
    sendOrder: number;
}

declare var WebTransportDatagramsWritable: {
    prototype: WebTransportDatagramsWritable;
    new(): WebTransportDatagramsWritable;
};

/** Available only in secure contexts. */
interface WebTransportSendGroup {
    getStats(): Promise<WebTransportSendStreamStats>;
}

declare var WebTransportSendGroup: {
    prototype: WebTransportSendGroup;
    new(): WebTransportSendGroup;
};

interface WebTransportSendStream {
    sendGroup: WebTransportSendGroup | null;
}
