// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: dom. Spec: webtransport

interface WebTransportSendOptions {
    sendGroup?: WebTransportSendGroup | null;
}

interface WebTransport {
    anticipatedConcurrentIncomingBidirectionalStreams: number | null;
    anticipatedConcurrentIncomingUnidirectionalStreams: number | null;
    readonly draining: Promise<void>;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/WebTransport/createSendGroup) */
    createSendGroup(): WebTransportSendGroup;
}

interface WebTransportDatagramDuplexStream {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/WebTransportDatagramDuplexStream/createWritable) */
    createWritable(options?: WebTransportSendOptions): WebTransportDatagramsWritable;
}

/**
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/WebTransportDatagramsWritable)
 */
interface WebTransportDatagramsWritable extends WritableStream {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/WebTransportDatagramsWritable/sendGroup) */
    sendGroup: WebTransportSendGroup | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/WebTransportDatagramsWritable/sendOrder) */
    sendOrder: number;
}

declare var WebTransportDatagramsWritable: {
    prototype: WebTransportDatagramsWritable;
    new(): WebTransportDatagramsWritable;
};

/**
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/WebTransportSendGroup)
 */
interface WebTransportSendGroup {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/WebTransportSendGroup/getStats) */
    getStats(): Promise<WebTransportSendStreamStats>;
}

declare var WebTransportSendGroup: {
    prototype: WebTransportSendGroup;
    new(): WebTransportSendGroup;
};

interface WebTransportSendStream {
    sendGroup: WebTransportSendGroup | null;
}
