// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: window. Spec: webusb

interface USBConnectionEventInit extends EventInit {
    device: USBDevice;
}

interface USBControlTransferParameters {
    index: number;
    recipient: USBRecipient;
    request: number;
    requestType: USBRequestType;
    value: number;
}

interface USBDeviceFilter {
    classCode?: number;
    productId?: number;
    protocolCode?: number;
    serialNumber?: string;
    subclassCode?: number;
    vendorId?: number;
}

interface USBDeviceRequestOptions {
    exclusionFilters?: USBDeviceFilter[];
    filters: USBDeviceFilter[];
}

interface Navigator {
    /**
     * The **`usb`** read-only property of the Navigator interface returns a USB object for the current document, providing access to WebUSB API functionality.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Navigator/usb)
     */
    readonly usb: USB;
}

interface USBEventMap {
    "connect": USBConnectionEvent;
    "disconnect": USBConnectionEvent;
}

/**
 * The **`USB`** interface of the WebUSB API provides attributes and methods for finding and connecting USB devices from a web page.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USB)
 */
interface USB extends EventTarget {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/USB/connect_event) */
    onconnect: ((this: USB, ev: USBConnectionEvent) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/USB/disconnect_event) */
    ondisconnect: ((this: USB, ev: USBConnectionEvent) => any) | null;
    /**
     * The **`getDevices`** method of the USB interface returns a Promise that resolves with an array of USBDevice objects for paired attached devices. For information on pairing devices, see USB.requestDevice().
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USB/getDevices)
     */
    getDevices(): Promise<USBDevice[]>;
    /**
     * The **`requestDevice()`** method of the USB interface returns a Promise that resolves with an instance of USBDevice if the specified device is found. Calling this function triggers the user agent's pairing flow.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USB/requestDevice)
     */
    requestDevice(options: USBDeviceRequestOptions): Promise<USBDevice>;
    addEventListener<K extends keyof USBEventMap>(type: K, listener: (this: USB, ev: USBEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof USBEventMap>(type: K, listener: (this: USB, ev: USBEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var USB: {
    prototype: USB;
    new(): USB;
};

/**
 * The **`USBAlternateInterface`** interface of the WebUSB API provides information about a particular configuration of an interface provided by the USB device. An interface includes one or more alternate settings which can configure a set of endpoints based on the operating mode of the device.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBAlternateInterface)
 */
interface USBAlternateInterface {
    readonly alternateSetting: number;
    readonly endpoints: ReadonlyArray<USBEndpoint>;
    readonly interfaceClass: number;
    readonly interfaceName: string | null;
    readonly interfaceProtocol: number;
    readonly interfaceSubclass: number;
}

declare var USBAlternateInterface: {
    prototype: USBAlternateInterface;
    new(deviceInterface: USBInterface, alternateSetting: number): USBAlternateInterface;
};

/**
 * The **`USBConfiguration`** interface of the WebUSB API provides information about a particular configuration of a USB device and the interfaces that it supports.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBConfiguration)
 */
interface USBConfiguration {
    /**
     * The **`configurationName`** read-only property of the USBConfiguration interface returns the name provided by the device to describe this configuration. This is equal to the value of the string descriptor with the index provided in the iConfiguration field of the configuration descriptor defining this configuration.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBConfiguration/configurationName)
     */
    readonly configurationName: string | null;
    /**
     * The **`configurationValue`** read-only property of the USBConfiguration interface returns the configuration value of this configuration. This is equal to the bConfigurationValue field of the configuration descriptor provided by the device defining this configuration.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBConfiguration/configurationValue)
     */
    readonly configurationValue: number;
    /**
     * The **`interfaces`** read-only property of the USBConfiguration interface returns an array containing instances of the USBInterface describing each interface supported by this configuration.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBConfiguration/interfaces)
     */
    readonly interfaces: ReadonlyArray<USBInterface>;
}

declare var USBConfiguration: {
    prototype: USBConfiguration;
    new(device: USBDevice, configurationValue: number): USBConfiguration;
};

/**
 * The **`USBConnectionEvent`** interface of the WebUSB API is the event type passed to USB connect and disconnect events when the user agent detects that a new USB device has been connected or disconnected.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBConnectionEvent)
 */
interface USBConnectionEvent extends Event {
    /**
     * The **`device`** read-only property of the USBConnectionEvent interface returns a USBDevice object representing the device being connected or disconnected.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBConnectionEvent/device)
     */
    readonly device: USBDevice;
}

declare var USBConnectionEvent: {
    prototype: USBConnectionEvent;
    new(type: string, eventInitDict: USBConnectionEventInit): USBConnectionEvent;
};

/**
 * The **`USBDevice`** interface of the WebUSB API provides access to metadata about a paired USB device and methods for controlling it.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice)
 */
interface USBDevice {
    /**
     * The **`configuration`** read only property of the USBDevice interface returns a USBConfiguration object for the currently selected interface for a paired USB device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/configuration)
     */
    readonly configuration: USBConfiguration | null;
    /**
     * The **`configurations`** read only property of the USBDevice interface an array of device-specific interfaces for controlling a paired USB device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/configurations)
     */
    readonly configurations: ReadonlyArray<USBConfiguration>;
    /**
     * The **`deviceClass`** read only property of the USBDevice interface one of three properties that identify USB devices for the purpose of loading a USB driver that will work with that device. The other two properties are USBDevice.deviceSubclass and USBDevice.deviceProtocol.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/deviceClass)
     */
    readonly deviceClass: number;
    /**
     * The **`deviceProtocol`** read only property of the USBDevice interface one of three properties that identify USB devices for the purpose of loading a USB driver that will work with that device. The other two properties are USBDevice.deviceClass and USBDevice.deviceSubclass.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/deviceProtocol)
     */
    readonly deviceProtocol: number;
    /**
     * The **`deviceSubclass`** read only property of the USBDevice interface one of three properties that identify USB devices for the purpose of loading a USB driver that will work with that device. The other two properties are USBDevice.deviceClass and USBDevice.deviceProtocol.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/deviceSubclass)
     */
    readonly deviceSubclass: number;
    /**
     * The **`deviceVersionMajor`** read only property of the USBDevice interface he major version number of the device in a semantic versioning scheme.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/deviceVersionMajor)
     */
    readonly deviceVersionMajor: number;
    /**
     * The **`deviceVersionMinor`** read only property of the USBDevice interface the minor version number of the device in a semantic versioning scheme.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/deviceVersionMinor)
     */
    readonly deviceVersionMinor: number;
    /**
     * The **`deviceVersionSubminor`** read only property of the USBDevice interface the patch version number of the device in a semantic versioning scheme.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/deviceVersionSubminor)
     */
    readonly deviceVersionSubminor: number;
    /**
     * The **`manufacturerName`** read only property of the USBDevice interface the of the organization that manufactured the USB device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/manufacturerName)
     */
    readonly manufacturerName: string | null;
    /**
     * The **`opened`** read only property of the USBDevice interface indicates whether a session has been started with a paired USB device. A device must be opened before it can be controlled by a web page.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/opened)
     */
    readonly opened: boolean;
    /**
     * The **`productId`** read only property of the USBDevice interface the manufacturer-defined code that identifies a USB device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/productId)
     */
    readonly productId: number;
    /**
     * The **`productName`** read only property of the USBDevice interface the manufacturer-defined name that identifies a USB device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/productName)
     */
    readonly productName: string | null;
    /**
     * The **`serialNumber`** read only property of the USBDevice interface is the manufacturer-defined serial number for the specific USB device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/serialNumber)
     */
    readonly serialNumber: string | null;
    /**
     * The **`usbVersionMajor`** read only property of the USBDevice interface is one of three properties that declare the USB protocol version supported by the device. The other two properties are USBDevice.usbVersionMinor and USBDevice.usbVersionSubminor.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/usbVersionMajor)
     */
    readonly usbVersionMajor: number;
    /**
     * The **`usbVersionMinor`** read only property of the USBDevice interface is one of three properties that declare the USB protocol version supported by the device. The other two properties are USBDevice.usbVersionMajor and USBDevice.usbVersionSubminor.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/usbVersionMinor)
     */
    readonly usbVersionMinor: number;
    /**
     * The **`usbVersionSubminor`** read only property of the USBDevice interface is one of three properties that declare the USB protocol version supported by the device. The other two properties are USBDevice.usbVersionMajor and USBDevice.usbVersionMinor.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/usbVersionSubminor)
     */
    readonly usbVersionSubminor: number;
    /**
     * The **`vendorId`** read only property of the USBDevice interface is the official usb.org-assigned vendor ID.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/vendorId)
     */
    readonly vendorId: number;
    /**
     * The **`claimInterface()`** method of the USBDevice interface returns a promise that resolves when the requested interface is claimed for exclusive access.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/claimInterface)
     */
    claimInterface(interfaceNumber: number): Promise<void>;
    /**
     * The **`clearHalt()`** method of the USBDevice interface returns a promise that resolves when a halt condition is cleared. A halt condition is when a data transfer to or from the device has a status of 'stall', which requires the web page (the host system, in USB terminology) to clear that condition. See the for details.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/clearHalt)
     */
    clearHalt(direction: USBDirection, endpointNumber: number): Promise<void>;
    /**
     * The **`close()`** method of the USBDevice interface returns a promise that resolves when all open interfaces are released and the device session has ended.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/close)
     */
    close(): Promise<void>;
    /**
     * The **`controlTransferIn()`** method of the USBDevice interface returns a Promise that resolves with a USBInTransferResult when a command or status request has been transmitted to (received by) the USB device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/controlTransferIn)
     */
    controlTransferIn(setup: USBControlTransferParameters, length: number): Promise<USBInTransferResult>;
    /**
     * The **`controlTransferOut()`** method of the USBDevice interface returns a Promise that resolves with a USBOutTransferResult when a command or status operation has been transmitted from the USB device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/controlTransferOut)
     */
    controlTransferOut(setup: USBControlTransferParameters, data?: BufferSource): Promise<USBOutTransferResult>;
    /**
     * The **`forget()`** method of the USBDevice interface returns a Promise that resolves when all pending operations are aborted, all open interfaces are released, the device session has ended, and the permission is reset.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/forget)
     */
    forget(): Promise<void>;
    /**
     * The **`isochronousTransferIn()`** method of the USBDevice interface returns a Promise that resolves with a USBIsochronousInTransferResult when time sensitive information has been transmitted to (received by) the USB device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/isochronousTransferIn)
     */
    isochronousTransferIn(endpointNumber: number, packetLengths: number[]): Promise<USBIsochronousInTransferResult>;
    /**
     * The **`isochronousTransferOut()`** method of the USBDevice interface returns a Promise that resolves with a USBIsochronousOutTransferResult when time sensitive information has been transmitted from the USB device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/isochronousTransferOut)
     */
    isochronousTransferOut(endpointNumber: number, data: BufferSource, packetLengths: number[]): Promise<USBIsochronousOutTransferResult>;
    /**
     * The **`open()`** method of the USBDevice interface returns a promise that resolves when a device session has started.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/open)
     */
    open(): Promise<void>;
    /**
     * The **`releaseInterface()`** method of the USBDevice interface returns a promise that resolves when a claimed interface is released from exclusive access.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/releaseInterface)
     */
    releaseInterface(interfaceNumber: number): Promise<void>;
    /**
     * The **`reset()`** method of the USBDevice interface returns a promise that resolves when the device is reset and all app operations canceled and their promises rejected.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/reset)
     */
    reset(): Promise<void>;
    /**
     * The **`selectAlternateInterface()`** method of the USBDevice interface returns a promise that resolves when the specified alternative endpoint is selected.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/selectAlternateInterface)
     */
    selectAlternateInterface(interfaceNumber: number, alternateSetting: number): Promise<void>;
    /**
     * The **`selectConfiguration()`** method of the USBDevice interface returns a promise that resolves when the specified configuration is selected.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/selectConfiguration)
     */
    selectConfiguration(configurationValue: number): Promise<void>;
    /**
     * The **`transferIn()`** method of the USBDevice interface returns a promise that resolves with a USBInTransferResult when bulk or interrupt data is received from the USB device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/transferIn)
     */
    transferIn(endpointNumber: number, length: number): Promise<USBInTransferResult>;
    /**
     * The **`transferOut()`** method of the USBDevice interface returns a promise that resolves with a USBOutTransferResult when bulk or interrupt data is sent to the USB device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/transferOut)
     */
    transferOut(endpointNumber: number, data: BufferSource): Promise<USBOutTransferResult>;
}

interface USBDevice {
    /**
     * The **`isochronousTransferIn()`** method of the USBDevice interface returns a Promise that resolves with a USBIsochronousInTransferResult when time sensitive information has been transmitted to (received by) the USB device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/isochronousTransferIn)
     */
    isochronousTransferIn(endpointNumber: number, packetLengths: Iterable<number>): Promise<USBIsochronousInTransferResult>;
    /**
     * The **`isochronousTransferOut()`** method of the USBDevice interface returns a Promise that resolves with a USBIsochronousOutTransferResult when time sensitive information has been transmitted from the USB device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBDevice/isochronousTransferOut)
     */
    isochronousTransferOut(endpointNumber: number, data: BufferSource, packetLengths: Iterable<number>): Promise<USBIsochronousOutTransferResult>;
}

declare var USBDevice: {
    prototype: USBDevice;
    new(): USBDevice;
};

/**
 * The **`USBEndpoint`** interface of the WebUSB API provides information about an endpoint provided by the USB device. An endpoint represents a unidirectional data stream into or out of a device.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBEndpoint)
 */
interface USBEndpoint {
    readonly direction: USBDirection;
    readonly endpointNumber: number;
    readonly packetSize: number;
    readonly type: USBEndpointType;
}

declare var USBEndpoint: {
    prototype: USBEndpoint;
    new(alternate: USBAlternateInterface, endpointNumber: number, direction: USBDirection): USBEndpoint;
};

/**
 * The **`USBInTransferResult`** interface of the WebUSB API provides the result from a call to the transferIn() and controlTransferIn() methods of the USBDevice interface. It represents the result from requesting a transfer of data from the USB device to the USB host.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBInTransferResult)
 */
interface USBInTransferResult {
    readonly data: DataView<ArrayBuffer> | null;
    readonly status: USBTransferStatus;
}

declare var USBInTransferResult: {
    prototype: USBInTransferResult;
    new(status: USBTransferStatus, data?: DataView<ArrayBuffer> | null): USBInTransferResult;
};

/**
 * The **`USBInterface`** interface of the WebUSB API provides information about an interface provided by the USB device. An interface represents a feature of the device which implements a particular protocol and may contain endpoints for bidirectional communication.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBInterface)
 */
interface USBInterface {
    readonly alternate: USBAlternateInterface;
    readonly alternates: ReadonlyArray<USBAlternateInterface>;
    readonly claimed: boolean;
    readonly interfaceNumber: number;
}

declare var USBInterface: {
    prototype: USBInterface;
    new(configuration: USBConfiguration, interfaceNumber: number): USBInterface;
};

/**
 * The **`USBIsochronousInTransferPacket`** interface of the WebUSB API is part of the response from a call to the isochronousTransferIn() method of the USBDevice interface. It represents the status of an individual packet from a request to transfer data from the USB device to the USB host over an isochronous endpoint.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBIsochronousInTransferPacket)
 */
interface USBIsochronousInTransferPacket {
    readonly data: DataView<ArrayBuffer> | null;
    readonly status: USBTransferStatus;
}

declare var USBIsochronousInTransferPacket: {
    prototype: USBIsochronousInTransferPacket;
    new(status: USBTransferStatus, data?: DataView<ArrayBuffer> | null): USBIsochronousInTransferPacket;
};

/**
 * The **`USBIsochronousInTransferResult`** interface of the WebUSB API provides the result from a call to the isochronousTransferIn() method of the USBDevice interface. It represents the result from requesting a transfer of data from the USB device to the USB host.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBIsochronousInTransferResult)
 */
interface USBIsochronousInTransferResult {
    readonly data: DataView<ArrayBuffer> | null;
    readonly packets: ReadonlyArray<USBIsochronousInTransferPacket>;
}

declare var USBIsochronousInTransferResult: {
    prototype: USBIsochronousInTransferResult;
    new(packets: USBIsochronousInTransferPacket[], data?: DataView<ArrayBuffer> | null): USBIsochronousInTransferResult;
};

/**
 * The **`USBIsochronousOutTransferPacket`** interface of the WebUSB API is part of the response from a call to the isochronousTransferOut() method of the USBDevice interface. It represents the status of an individual packet from a request to transfer data from the USB host to the USB device over an isochronous endpoint.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBIsochronousOutTransferPacket)
 */
interface USBIsochronousOutTransferPacket {
    readonly bytesWritten: number;
    readonly status: USBTransferStatus;
}

declare var USBIsochronousOutTransferPacket: {
    prototype: USBIsochronousOutTransferPacket;
    new(status: USBTransferStatus, bytesWritten?: number): USBIsochronousOutTransferPacket;
};

/**
 * The **`USBIsochronousOutTransferResult`** interface of the WebUSB API provides the result from a call to the isochronousTransferOut() method of the USBDevice interface. It represents the result from requesting a transfer of data from the USB host to the USB device.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBIsochronousOutTransferResult)
 */
interface USBIsochronousOutTransferResult {
    readonly packets: ReadonlyArray<USBIsochronousOutTransferPacket>;
}

declare var USBIsochronousOutTransferResult: {
    prototype: USBIsochronousOutTransferResult;
    new(packets: USBIsochronousOutTransferPacket[]): USBIsochronousOutTransferResult;
};

/**
 * The **`USBOutTransferResult`** interface of the WebUSB API provides the result from a call to the transferOut() and controlTransferOut() methods of the USBDevice interface. It represents the result from requesting a transfer of data from the USB host to the USB device.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/USBOutTransferResult)
 */
interface USBOutTransferResult {
    readonly bytesWritten: number;
    readonly status: USBTransferStatus;
}

declare var USBOutTransferResult: {
    prototype: USBOutTransferResult;
    new(status: USBTransferStatus, bytesWritten?: number): USBOutTransferResult;
};

type USBDirection = "in" | "out";

type USBEndpointType = "bulk" | "interrupt" | "isochronous";

type USBRecipient = "device" | "endpoint" | "interface" | "other";

type USBRequestType = "class" | "standard" | "vendor";

type USBTransferStatus = "babble" | "ok" | "stall";
