// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Spec: webxr-depth-sensing

interface XRDepthStateInit {
    dataFormatPreference: XRDepthDataFormat[];
    depthTypeRequest?: XRDepthType[];
    matchDepthView?: boolean;
    usagePreference: XRDepthUsage[];
}

/**
 * The **`XRCPUDepthInformation`** interface contains depth information from the CPU (returned by XRFrame.getDepthInformation()).
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRCPUDepthInformation)
 */
interface XRCPUDepthInformation extends XRDepthInformation {
    /**
     * The read-only **`data`** property of the XRCPUDepthInformation interface is an ArrayBuffer containing depth-buffer information in raw format.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRCPUDepthInformation/data)
     */
    readonly data: ArrayBuffer;
    /**
     * The **`getDepthInMeters()`** method of the XRCPUDepthInformation interface returns the depth in meters at (x, y) in normalized view coordinates (origin in the top left corner).
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRCPUDepthInformation/getDepthInMeters)
     */
    getDepthInMeters(x: number, y: number): number;
}

declare var XRCPUDepthInformation: {
    prototype: XRCPUDepthInformation;
    new(): XRCPUDepthInformation;
};

/**
 * The **`XRDepthInformation`** interface contains information about the distance from the user's device to the real-world geometry in the user's environment.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRDepthInformation)
 */
interface XRDepthInformation extends XRViewGeometry {
    /**
     * The read-only **`height`** property of the XRDepthInformation interface contains the height of the depth buffer (number of rows).
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRDepthInformation/height)
     */
    readonly height: number;
    /**
     * The read-only **`normDepthBufferFromNormView`** property of the XRDepthInformation interface contains the 3D geometric transform that needs to be applied when indexing into the depth buffer.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRDepthInformation/normDepthBufferFromNormView)
     */
    readonly normDepthBufferFromNormView: XRRigidTransform;
    /**
     * The read-only **`rawValueToMeters`** property of the XRDepthInformation interface contains the scale factor by which the raw depth values must be multiplied in order to get the depths in meters.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRDepthInformation/rawValueToMeters)
     */
    readonly rawValueToMeters: number;
    /**
     * The read-only **`width`** property of the XRDepthInformation interface contains the width of the depth buffer (number of columns).
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRDepthInformation/width)
     */
    readonly width: number;
}

declare var XRDepthInformation: {
    prototype: XRDepthInformation;
    new(): XRDepthInformation;
};

/**
 * The **`XRWebGLDepthInformation`** interface contains depth information from the GPU/WebGL (returned by XRWebGLBinding.getDepthInformation()).
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRWebGLDepthInformation)
 */
interface XRWebGLDepthInformation extends XRDepthInformation {
    /**
     * The read-only **`texture`** property of the XRWebGLDepthInformation interface is a WebGLTexture containing depth buffer information as an opaque texture.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRWebGLDepthInformation/texture)
     */
    readonly texture: WebGLTexture;
}

declare var XRWebGLDepthInformation: {
    prototype: XRWebGLDepthInformation;
    new(): XRWebGLDepthInformation;
};

type XRDepthDataFormat = "float32" | "luminance-alpha" | "unsigned-short";

type XRDepthType = "raw" | "smooth";

type XRDepthUsage = "cpu-optimized" | "gpu-optimized";
