// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: dom. Spec: webxr-dom-overlays

interface XRDOMOverlayInit {
    root: Element;
}

interface XRDOMOverlayState {
    type?: XRDOMOverlayType;
}

interface GlobalEventHandlers {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/Element/beforexrselect_event) */
    onbeforexrselect: ((this: GlobalEventHandlers, ev: Event) => any) | null;
}

type XRDOMOverlayType = "floating" | "head-locked" | "screen";
