// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: window. Spec: webxr-hit-test

interface XRHitTestOptionsInit {
    entityTypes?: XRHitTestTrackableType[];
    offsetRay?: XRRay;
    space: XRSpace;
}

interface XRRayDirectionInit {
    w?: number;
    x?: number;
    y?: number;
    z?: number;
}

interface XRTransientInputHitTestOptionsInit {
    entityTypes?: XRHitTestTrackableType[];
    offsetRay?: XRRay;
    profile: string;
}

/**
 * The **`XRHitTestResult`** interface of the WebXR Device API contains a single result of a hit test. You can get an array of XRHitTestResult objects for a frame by calling XRFrame.getHitTestResults().
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRHitTestResult)
 */
interface XRHitTestResult {
    /**
     * The **`createAnchor()`** method of the XRHitTestResult interface creates an XRAnchor from a hit test result that is attached to a real-world object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRHitTestResult/createAnchor)
     */
    createAnchor(): Promise<XRAnchor>;
    /**
     * The **`getPose()`** method of the XRHitTestResult interface returns the XRPose of the hit test result relative to the given base space.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRHitTestResult/getPose)
     */
    getPose(baseSpace: XRSpace): XRPose | null;
}

declare var XRHitTestResult: {
    prototype: XRHitTestResult;
    new(): XRHitTestResult;
};

/**
 * The **`XRHitTestSource`** interface of the WebXR Device API handles hit test subscriptions. You can get an XRHitTestSource object by using the XRSession.requestHitTestSource() method.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRHitTestSource)
 */
interface XRHitTestSource {
    /**
     * The **`cancel()`** method of the XRHitTestSource interface unsubscribes a hit test.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRHitTestSource/cancel)
     */
    cancel(): void;
}

declare var XRHitTestSource: {
    prototype: XRHitTestSource;
    new(): XRHitTestSource;
};

/**
 * The **`XRRay`** interface of the WebXR Device API is a geometric ray described by an origin point and a direction vector.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRRay)
 */
interface XRRay {
    /**
     * The read-only **`direction`** property of the XRRay interface is a DOMPointReadOnly representing the ray's 3-dimensional directional vector, normalized to a unit vector with a length of 1.0.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRRay/direction)
     */
    readonly direction: DOMPointReadOnly;
    /**
     * The read-only **`matrix`** property of the XRRay interface is a transform that can be used to position objects along the XRRay. This is a 4 by 4 matrix given as a 16 element Float32Array in column major order.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRRay/matrix)
     */
    readonly matrix: Float32Array<ArrayBuffer>;
    /**
     * The read-only **`origin`** property of the XRRay interface is a DOMPointReadOnly representing the 3-dimensional point in space that the ray originates from, in meters.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRRay/origin)
     */
    readonly origin: DOMPointReadOnly;
}

declare var XRRay: {
    prototype: XRRay;
    new(origin?: DOMPointInit, direction?: XRRayDirectionInit): XRRay;
    new(transform: XRRigidTransform): XRRay;
};

/**
 * The **`XRTransientInputHitTestResult`** interface of the WebXR Device API contains an array of results of a hit test for transient input, grouped by input source.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRTransientInputHitTestResult)
 */
interface XRTransientInputHitTestResult {
    /**
     * The read-only **`inputSource`** property of the XRTransientInputHitTestResult interface represents an XRInputSource object that was used to compute the results array.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRTransientInputHitTestResult/inputSource)
     */
    readonly inputSource: XRInputSource;
    /**
     * The read-only **`results`** property of the XRTransientInputHitTestResult interface represents an array of XRHitTestResult objects containing the hit test results for the input source, ordered by the distance along the ray used to perform the hit test, with the closest result at position 0.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRTransientInputHitTestResult/results)
     */
    readonly results: ReadonlyArray<XRHitTestResult>;
}

declare var XRTransientInputHitTestResult: {
    prototype: XRTransientInputHitTestResult;
    new(): XRTransientInputHitTestResult;
};

/**
 * The **`XRTransientInputHitTestSource`** interface of the WebXR Device API handles transient input hit test subscriptions. You can get an XRTransientInputHitTestSource object by calling the XRSession.requestHitTestSourceForTransientInput().
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRTransientInputHitTestSource)
 */
interface XRTransientInputHitTestSource {
    /**
     * The **`cancel()`** method of the XRTransientInputHitTestSource interface unsubscribes a transient input hit test.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRTransientInputHitTestSource/cancel)
     */
    cancel(): void;
}

declare var XRTransientInputHitTestSource: {
    prototype: XRTransientInputHitTestSource;
    new(): XRTransientInputHitTestSource;
};

type XRHitTestTrackableType = "mesh" | "plane" | "point";
