// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: window. Spec: webxr-hand-input

/**
 * The **`XRHand`** interface is pair iterator (an ordered map) with the key being the hand joints and the value being an XRJointSpace.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRHand)
 */
interface XRHand {
    readonly size: number;
    get(key: XRHandJoint): XRJointSpace;
    forEach(callbackfn: (value: XRJointSpace, key: XRHandJoint, parent: XRHand) => void, thisArg?: any): void;
}

interface XRHand {
    [Symbol.iterator](): XRHandIterator<[XRHandJoint, XRJointSpace]>;
    entries(): XRHandIterator<[XRHandJoint, XRJointSpace]>;
    keys(): XRHandIterator<XRHandJoint>;
    values(): XRHandIterator<XRJointSpace>;
}

declare var XRHand: {
    prototype: XRHand;
    new(): XRHand;
};

/**
 * The **`XRJointPose`** interface is an XRPose with additional information about the size of the skeleton joint it represents.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRJointPose)
 */
interface XRJointPose extends XRPose {
    /**
     * The read-only **`radius`** property of the XRJointPose interface indicates the radius (distance from skin) for a joint.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRJointPose/radius)
     */
    readonly radius: number;
}

declare var XRJointPose: {
    prototype: XRJointPose;
    new(): XRJointPose;
};

/**
 * The **`XRJointSpace`** interface is an XRSpace and represents the position and orientation of an XRHand joint.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRJointSpace)
 */
interface XRJointSpace extends XRSpace {
    /**
     * The read-only **`jointName`** property of the XRJointSpace interface contains the name of the joint it tracks.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRJointSpace/jointName)
     */
    readonly jointName: XRHandJoint;
}

declare var XRJointSpace: {
    prototype: XRJointSpace;
    new(): XRJointSpace;
};

type XRHandJoint = "index-finger-metacarpal" | "index-finger-phalanx-distal" | "index-finger-phalanx-intermediate" | "index-finger-phalanx-proximal" | "index-finger-tip" | "middle-finger-metacarpal" | "middle-finger-phalanx-distal" | "middle-finger-phalanx-intermediate" | "middle-finger-phalanx-proximal" | "middle-finger-tip" | "pinky-finger-metacarpal" | "pinky-finger-phalanx-distal" | "pinky-finger-phalanx-intermediate" | "pinky-finger-phalanx-proximal" | "pinky-finger-tip" | "ring-finger-metacarpal" | "ring-finger-phalanx-distal" | "ring-finger-phalanx-intermediate" | "ring-finger-phalanx-proximal" | "ring-finger-tip" | "thumb-metacarpal" | "thumb-phalanx-distal" | "thumb-phalanx-proximal" | "thumb-tip" | "wrist";
