// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Spec: webxr

interface XRInputSourceEventInit extends EventInit {
    frame: XRFrame;
    inputSource: XRInputSource;
}

interface XRInputSourcesChangeEventInit extends EventInit {
    added: XRInputSource[];
    removed: XRInputSource[];
    session: XRSession;
}

interface XRReferenceSpaceEventInit extends EventInit {
    referenceSpace: XRReferenceSpace;
    transform?: XRRigidTransform | null;
}

interface XRRenderStateInit {
    baseLayer?: XRWebGLLayer | null;
    depthFar?: number;
    depthNear?: number;
    inlineVerticalFieldOfView?: number;
    layers?: XRLayer[] | null;
    passthroughFullyObscured?: boolean;
}

interface XRSessionEventInit extends EventInit {
    session: XRSession;
}

interface XRSessionInit {
    depthSensing?: XRDepthStateInit;
    domOverlay?: XRDOMOverlayInit | null;
    optionalFeatures?: string[];
    requiredFeatures?: string[];
}

interface XRVisibilityMaskChangeEventInit extends EventInit {
    eye: XREye;
    index: number;
    indices: Uint32Array<ArrayBuffer>;
    session: XRSession;
    vertices: Float32Array<ArrayBuffer>;
}

interface XRWebGLLayerInit {
    alpha?: boolean;
    antialias?: boolean;
    depth?: boolean;
    framebufferScaleFactor?: number;
    ignoreDepthValues?: boolean;
    stencil?: boolean;
}

interface Navigator {
    /**
     * The read-only **`xr`** property provided by the Navigator interface returns an XRSystem object which can be used to access the WebXR Device API.
     * Available only in secure contexts.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Navigator/xr)
     */
    readonly xr: XRSystem;
}

interface WebGLRenderingContextBase {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/WebGLRenderingContext/makeXRCompatible) */
    makeXRCompatible(): Promise<void>;
}

/**
 * The WebXR Device API's **`XRBoundedReferenceSpace`** interface describes a virtual world reference space which has preset boundaries. This extends XRReferenceSpace, which describes an essentially unrestricted space around the viewer's position. These bounds are defined using an array of points, each of which defines a vertex in a polygon inside which the user is allowed to move.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRBoundedReferenceSpace)
 */
interface XRBoundedReferenceSpace extends XRReferenceSpace {
    /**
     * The read-only XRBoundedReferenceSpace property **`boundsGeometry`** is an array of DOMPointReadOnly objects which specifies the points making up a polygon inside which the viewer is allowed to move. Each point is treated as a two-dimensional point, and must be located at ground level (that is, its y coordinate must be 0).
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRBoundedReferenceSpace/boundsGeometry)
     */
    readonly boundsGeometry: ReadonlyArray<DOMPointReadOnly>;
    addEventListener<K extends keyof XRReferenceSpaceEventMap>(type: K, listener: (this: XRBoundedReferenceSpace, ev: XRReferenceSpaceEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof XRReferenceSpaceEventMap>(type: K, listener: (this: XRBoundedReferenceSpace, ev: XRReferenceSpaceEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var XRBoundedReferenceSpace: {
    prototype: XRBoundedReferenceSpace;
    new(): XRBoundedReferenceSpace;
};

/**
 * A WebXR Device API **`XRFrame`** object is passed into the requestAnimationFrame() callback function and provides access to the information needed in order to render a single frame of animation for an XRSession describing a VR or AR scene. Events which communicate the tracking state of objects also provide an XRFrame reference as part of their structure.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRFrame)
 */
interface XRFrame {
    readonly detectedPlanes: XRPlaneSet;
    /**
     * An XRFrame object's read-only **`session`** property returns the XRSession object that generated the frame.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRFrame/session)
     */
    readonly session: XRSession;
    /**
     * The read-only trackedAnchor property of the XRFrame interface returns an XRAnchorSet object containing all anchors still tracked in the frame.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRFrame/trackedAnchors)
     */
    readonly trackedAnchors: XRAnchorSet;
    /**
     * The **`createAnchor()`** method of the XRFrame interface creates a free-floating XRAnchor which will be fixed relative to the real world.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRFrame/createAnchor)
     */
    createAnchor(pose: XRRigidTransform, space: XRSpace): Promise<XRAnchor>;
    /**
     * The **`fillJointRadii()`** method of the XRFrame interface populates a Float32Array with radii for a list of hand joint spaces and returns true if successful for all spaces.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRFrame/fillJointRadii)
     */
    fillJointRadii(jointSpaces: XRJointSpace[], radii: Float32Array<ArrayBuffer>): boolean;
    /**
     * The **`fillPoses()`** method of the XRFrame interface populates a Float32Array with the matrices of the poses relative to a given base space and returns true if successful for all spaces.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRFrame/fillPoses)
     */
    fillPoses(spaces: XRSpace[], baseSpace: XRSpace, transforms: Float32Array<ArrayBuffer>): boolean;
    /**
     * The **`getDepthInformation()`** method of the XRFrame interface returns an XRCPUDepthInformation object containing CPU depth information for the active and animated frame.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRFrame/getDepthInformation)
     */
    getDepthInformation(view: XRView): XRCPUDepthInformation | null;
    /**
     * The **`getHitTestResults()`** method of the XRFrame interface returns an array of XRHitTestResult objects containing hit test results for a given XRHitTestSource.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRFrame/getHitTestResults)
     */
    getHitTestResults(hitTestSource: XRHitTestSource): XRHitTestResult[];
    /**
     * The **`getHitTestResultsForTransientInput()`** method of the XRFrame interface returns an array of XRTransientInputHitTestResult objects containing transient input hit test results for a given XRTransientInputHitTestSource.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRFrame/getHitTestResultsForTransientInput)
     */
    getHitTestResultsForTransientInput(hitTestSource: XRTransientInputHitTestSource): XRTransientInputHitTestResult[];
    /**
     * The **`getJointPose()`** method of the XRFrame interface returns an XRJointPose object providing the pose of a hand joint (see XRHand) relative to a given base space.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRFrame/getJointPose)
     */
    getJointPose(joint: XRJointSpace, baseSpace: XRSpace): XRJointPose | null;
    /**
     * The **`getLightEstimate()`** method of the XRFrame interface returns an XRLightEstimate object containing estimated lighting values for a given XRLightProbe.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRFrame/getLightEstimate)
     */
    getLightEstimate(lightProbe: XRLightProbe): XRLightEstimate | null;
    /**
     * The XRFrame method **`getPose()`** returns the relative position and orientation—the pose—of one XRSpace to that of another space. With this, you can observe the motion of objects relative to each other and to fixed locations throughout the scene.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRFrame/getPose)
     */
    getPose(space: XRSpace, baseSpace: XRSpace): XRPose | null;
    /**
     * The **`getViewerPose()`** method, a member of the XRFrame interface, returns a XRViewerPose object which describes the viewer's pose (position and orientation) relative to the specified reference space.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRFrame/getViewerPose)
     */
    getViewerPose(referenceSpace: XRReferenceSpace): XRViewerPose | null;
}

interface XRFrame {
    /**
     * The **`fillJointRadii()`** method of the XRFrame interface populates a Float32Array with radii for a list of hand joint spaces and returns true if successful for all spaces.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRFrame/fillJointRadii)
     */
    fillJointRadii(jointSpaces: Iterable<XRJointSpace>, radii: Float32Array<ArrayBuffer>): boolean;
    /**
     * The **`fillPoses()`** method of the XRFrame interface populates a Float32Array with the matrices of the poses relative to a given base space and returns true if successful for all spaces.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRFrame/fillPoses)
     */
    fillPoses(spaces: Iterable<XRSpace>, baseSpace: XRSpace, transforms: Float32Array<ArrayBuffer>): boolean;
}

declare var XRFrame: {
    prototype: XRFrame;
    new(): XRFrame;
};

/**
 * The WebXR Device API's **`XRInputSource`** interface describes a single source of control input which is part of the user's WebXR-compatible virtual or augmented reality system. The device is specific to the platform being used, but provides the direction in which it is being aimed and optionally may generate events if the user triggers performs actions using the device.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRInputSource)
 */
interface XRInputSource {
    /**
     * The read-only XRInputSource property **`gamepad`** returns a Gamepad object describing the state of the buttons and axes on the XR input source, if it is a gamepad or comparable device. If the device isn't a gamepad-like device, this property's value is null.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRInputSource/gamepad)
     */
    readonly gamepad: Gamepad | null;
    /**
     * The read-only XRInputSource property **`gripSpace`** returns an XRSpace whose native origin tracks the pose used to render virtual objects so they appear to be held in (or part of) the user's hand. For example, if a user were holding a virtual straight rod, the native origin of this XRSpace would be located at the approximate center of mass of the user's fist.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRInputSource/gripSpace)
     */
    readonly gripSpace: XRSpace | null;
    /**
     * The read-only **`hand`** property of the XRInputSource interface is a XRHand object providing access to a hand-tracking device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRInputSource/hand)
     */
    readonly hand: XRHand | null;
    /**
     * The read-only XRInputSource property **`handedness`** indicates which of the user's hands the WebXR input source is associated with, or if it's not associated with a hand at all.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRInputSource/handedness)
     */
    readonly handedness: XRHandedness;
    /**
     * The read-only XRInputSource property **`profiles`** returns an array of strings, each describing a configuration profile for the input source. The profile strings are listed in order of specificity, with the most specific profile listed first.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRInputSource/profiles)
     */
    readonly profiles: ReadonlyArray<string>;
    /**
     * The read-only XRInputSource property **`targetRayMode`** indicates the method by which the target ray for the input source should be generated and how it should be presented to the user.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRInputSource/targetRayMode)
     */
    readonly targetRayMode: XRTargetRayMode;
    /**
     * The read-only XRInputSource property **`targetRaySpace`** returns an XRSpace (typically an XRReferenceSpace) representing the position and orientation of the target ray in the virtual space. Its native origin tracks the position of the origin point of the target ray, and its orientation indicates the orientation of the controller device itself. These values, interpreted in the context of the input source's targetRayMode, can be used both to fully interpret the device as an input source.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRInputSource/targetRaySpace)
     */
    readonly targetRaySpace: XRSpace;
}

declare var XRInputSource: {
    prototype: XRInputSource;
    new(): XRInputSource;
};

/**
 * The interface **`XRInputSourceArray`** represents a live list of WebXR input sources, and is used as the return value of the XRSession property inputSources. Each entry is an XRInputSource representing one input device connected to the WebXR system.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRInputSourceArray)
 */
interface XRInputSourceArray {
    /**
     * The read-only **`length`** property returns an integer value indicating the number of items in the input source list represented by the XRInputSourceArray object.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRInputSourceArray/length)
     */
    readonly length: number;
    forEach(callbackfn: (value: XRInputSource, key: number, parent: XRInputSourceArray) => void, thisArg?: any): void;
    [index: number]: XRInputSource;
}

interface XRInputSourceArray {
    [Symbol.iterator](): ArrayIterator<XRInputSource>;
    entries(): ArrayIterator<[number, XRInputSource]>;
    keys(): ArrayIterator<number>;
    values(): ArrayIterator<XRInputSource>;
}

declare var XRInputSourceArray: {
    prototype: XRInputSourceArray;
    new(): XRInputSourceArray;
};

/**
 * The WebXR Device API's **`XRInputSourceEvent`** interface describes an event which has occurred on a WebXR user input device such as a hand controller, gaze tracking system, or motion tracking system. More specifically, they represent a change in the state of an XRInputSource.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRInputSourceEvent)
 */
interface XRInputSourceEvent extends Event {
    /**
     * The read-only XRInputSourceEvent property **`frame`** specifies an XRFrame object representing the event frame during which a WebXR user input occurred. This may thus be an event which occurred in the past rather than a current or impending event.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRInputSourceEvent/frame)
     */
    readonly frame: XRFrame;
    /**
     * The XRInputSourceEvent interface's read-only **`inputSource`** property specifies the XRInputSource which generated the input event. This information lets you handle the event appropriately given the particulars of the user input device being manipulated.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRInputSourceEvent/inputSource)
     */
    readonly inputSource: XRInputSource;
}

declare var XRInputSourceEvent: {
    prototype: XRInputSourceEvent;
    new(type: string, eventInitDict: XRInputSourceEventInit): XRInputSourceEvent;
};

/**
 * The WebXR Device API interface **`XRInputSourcesChangeEvent`** is used to represent the inputsourceschange event sent to an XRSession when the set of available WebXR input controllers changes.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRInputSourcesChangeEvent)
 */
interface XRInputSourcesChangeEvent extends Event {
    /**
     * The read-only XRInputSourcesChangeEvent property **`added`** is a list of zero or more input sources, each identified using an XRInputSource object, which have been newly made available for use.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRInputSourcesChangeEvent/added)
     */
    readonly added: ReadonlyArray<XRInputSource>;
    /**
     * The read-only XRInputSourcesChangeEvent property **`removed`** is an array of zero or more XRInputSource objects representing the input sources that have been removed from the XRSession.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRInputSourcesChangeEvent/removed)
     */
    readonly removed: ReadonlyArray<XRInputSource>;
    /**
     * The XRInputSourcesChangeEvent property **`session`** specifies the XRSession to which the input source list change event applies.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRInputSourcesChangeEvent/session)
     */
    readonly session: XRSession;
}

declare var XRInputSourcesChangeEvent: {
    prototype: XRInputSourcesChangeEvent;
    new(type: string, eventInitDict: XRInputSourcesChangeEventInit): XRInputSourcesChangeEvent;
};

/**
 * The **`XRLayer`** interface of the WebXR Device API is the base class for WebXR layer types. It inherits methods from EventTarget.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRLayer)
 */
interface XRLayer extends EventTarget {
}

declare var XRLayer: {
    prototype: XRLayer;
    new(): XRLayer;
};

/**
 * **`XRPose`** is a WebXR API interface representing a position and orientation in the 3D space, relative to the XRSpace within which it resides. The XRSpace—which is either an XRReferenceSpace or an XRBoundedReferenceSpace—defines the coordinate system used for the pose and, in the case of an XRViewerPose, its underlying views.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRPose)
 */
interface XRPose {
    /**
     * The **`emulatedPosition`** read-only attribute of the XRPose interface is a Boolean value indicating whether or not both the position component of the pose's transform is directly taken from the XR device, or it's simulated or computed based on other sources.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRPose/emulatedPosition)
     */
    readonly emulatedPosition: boolean;
    /**
     * The **`transform`** read-only attribute of the XRPose interface is a XRRigidTransform object providing the position and orientation of the pose relative to the base XRSpace as specified when the pose was obtained by calling XRFrame.getPose().
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRPose/transform)
     */
    readonly transform: XRRigidTransform;
}

declare var XRPose: {
    prototype: XRPose;
    new(): XRPose;
};

interface XRReferenceSpaceEventMap {
    "reset": XRReferenceSpaceEvent;
}

/**
 * The WebXR Device API's **`XRReferenceSpace`** interface describes the coordinate system for a specific tracked entity or object within the virtual world using a specified tracking behavior. The tracking behavior is defined by the selected reference space type. It expands upon the base class, XRSpace, by adding support for several different tracking behaviors as well as to request a new reference space which describes the offset transform between the tracked object and another location in the world.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRReferenceSpace)
 */
interface XRReferenceSpace extends XRSpace {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRReferenceSpace/reset_event) */
    onreset: ((this: XRReferenceSpace, ev: XRReferenceSpaceEvent) => any) | null;
    /**
     * The XRReferenceSpace interface's **`getOffsetReferenceSpace()`** method returns a new reference space object which describes the relative difference in position between the object on which the method is called and a given point in 3D space. The object returned by getOffsetReferenceSpace() is an XRReferenceSpace if called on an XRReferenceSpace, or an XRBoundedReferenceSpace if called on an object of that type.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRReferenceSpace/getOffsetReferenceSpace)
     */
    getOffsetReferenceSpace(originOffset: XRRigidTransform): XRReferenceSpace;
    addEventListener<K extends keyof XRReferenceSpaceEventMap>(type: K, listener: (this: XRReferenceSpace, ev: XRReferenceSpaceEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof XRReferenceSpaceEventMap>(type: K, listener: (this: XRReferenceSpace, ev: XRReferenceSpaceEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var XRReferenceSpace: {
    prototype: XRReferenceSpace;
    new(): XRReferenceSpace;
};

/**
 * The WebXR Device API interface **`XRReferenceSpaceEvent`** represents an event sent to an XRReferenceSpace. Currently, the only event that uses this type is the reset event.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRReferenceSpaceEvent)
 */
interface XRReferenceSpaceEvent extends Event {
    /**
     * The read-only XRReferenceSpaceEvent property **`referenceSpace`** specifies the reference space which is the originator of the event.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRReferenceSpaceEvent/referenceSpace)
     */
    readonly referenceSpace: XRReferenceSpace;
    /**
     * The read-only XRReferenceSpaceEvent property **`transform`** indicates the position and orientation of the affected referenceSpace's native origin after the changes the event represents are applied. The transform is defined using the old coordinate system, which allows it to be used to convert coordinates from the pre-event coordinate system to the post-event coordinate system.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRReferenceSpaceEvent/transform)
     */
    readonly transform: XRRigidTransform | null;
}

declare var XRReferenceSpaceEvent: {
    prototype: XRReferenceSpaceEvent;
    new(type: string, eventInitDict: XRReferenceSpaceEventInit): XRReferenceSpaceEvent;
};

/**
 * The **`XRRenderState`** interface of the WebXR Device API contains configurable values which affect how the imagery generated by an XRSession gets composited. These properties include the range of distances from the viewer within which content should be rendered, the vertical field of view (for inline presentations), and a reference to the XRWebGLLayer being used as the target for rendering the scene prior to it being presented on the XR device's display or displays.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRRenderState)
 */
interface XRRenderState {
    /**
     * The read-only **`baseLayer`** property of the XRRenderState interface returns the XRWebGLLayer instance that is the source of bitmap images and a description of how the image is to be rendered in the device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRRenderState/baseLayer)
     */
    readonly baseLayer: XRWebGLLayer | null;
    /**
     * The **`depthFar`** read-only property of the XRRenderState interface returns the distance in meters of the far clip plane from the viewer.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRRenderState/depthFar)
     */
    readonly depthFar: number;
    /**
     * The **`depthNear`** read-only property of the XRRenderState interface returns the distance in meters of the near clip plane from the viewer.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRRenderState/depthNear)
     */
    readonly depthNear: number;
    /**
     * The read-only **`inlineVerticalFieldOfView`** property of the XRRenderState interface returns the default vertical field of view for "inline" sessions and null for all immersive sessions.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRRenderState/inlineVerticalFieldOfView)
     */
    readonly inlineVerticalFieldOfView: number | null;
    /**
     * The read-only **`layers`** property of the XRRenderState interface is an ordered array containing XRLayer objects that are displayed by the XR compositor.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRRenderState/layers)
     */
    readonly layers: ReadonlyArray<XRLayer>;
}

declare var XRRenderState: {
    prototype: XRRenderState;
    new(): XRRenderState;
};

/**
 * The **`XRRigidTransform`** is a WebXR API interface that represents the 3D geometric transform described by a position and orientation.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRRigidTransform)
 */
interface XRRigidTransform {
    /**
     * The read-only **`inverse`** property of the XRRigidTransform interface returns another XRRigidTransform object which is the inverse of its owning transform. That is, you can always get the inverse of any XRRigidTransform using its inverse property, instead of having to explicitly generate it.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRRigidTransform/inverse)
     */
    readonly inverse: XRRigidTransform;
    /**
     * The read-only XRRigidTransform property **`matrix`** returns the transform matrix represented by the object. The returned matrix can then be premultiplied with a column vector to rotate the vector by the 3D rotation specified by the orientation, then translate it by the position.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRRigidTransform/matrix)
     */
    readonly matrix: Float32Array<ArrayBuffer>;
    /**
     * The read-only XRRigidTransform property **`orientation`** is a DOMPointReadOnly containing a normalized quaternion (also called a unit quaternion or versor) specifying the rotational component of the transform represented by the object. If you specify a quaternion whose length is not exactly 1.0 meters, it will be normalized for you.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRRigidTransform/orientation)
     */
    readonly orientation: DOMPointReadOnly;
    /**
     * The read-only XRRigidTransform property **`position`** is a DOMPointReadOnly object which provides the 3D point, specified in meters, describing the translation component of the transform.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRRigidTransform/position)
     */
    readonly position: DOMPointReadOnly;
}

declare var XRRigidTransform: {
    prototype: XRRigidTransform;
    new(position?: DOMPointInit, orientation?: DOMPointInit): XRRigidTransform;
};

interface XRSessionEventMap {
    "end": XRSessionEvent;
    "inputsourceschange": XRInputSourcesChangeEvent;
    "select": XRInputSourceEvent;
    "selectend": XRInputSourceEvent;
    "selectstart": XRInputSourceEvent;
    "squeeze": XRInputSourceEvent;
    "squeezeend": XRInputSourceEvent;
    "squeezestart": XRInputSourceEvent;
    "visibilitychange": XRSessionEvent;
}

/**
 * The **`XRSession`** interface of the WebXR Device API represents an ongoing XR session, providing methods and properties used to interact with and control the session. To open a WebXR session, use the XRSystem interface's requestSession() method.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSession)
 */
interface XRSession extends EventTarget {
    readonly depthActive: boolean | null;
    /**
     * The read-only **`depthDataFormat`** property of an immersive-ar XRSession describes which depth sensing data format is used.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSession/depthDataFormat)
     */
    readonly depthDataFormat: XRDepthDataFormat;
    readonly depthType: XRDepthType | null;
    /**
     * The read-only **`depthUsage`** property of an immersive-ar XRSession describes which depth-sensing usage is used.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSession/depthUsage)
     */
    readonly depthUsage: XRDepthUsage;
    /**
     * The read-only **`domOverlayState`** property of an immersive-ar XRSession provides information about the DOM overlay, if the feature is enabled.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSession/domOverlayState)
     */
    readonly domOverlayState: XRDOMOverlayState | null;
    /**
     * The XRSession interface's read-only **`enabledFeatures`** property returns an array of features enabled (granted) for an XRSession. This contains all requiredFeatures and a subset of optionalFeatures that have been requested with XRSystem.requestSession().
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSession/enabledFeatures)
     */
    readonly enabledFeatures: ReadonlyArray<string>;
    /**
     * The XRSession interface's read-only **`environmentBlendMode`** property identifies if, and to what degree, the computer-generated imagery is overlaid atop the real world.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSession/environmentBlendMode)
     */
    readonly environmentBlendMode: XREnvironmentBlendMode;
    /**
     * The read-only **`inputSources`** property of the XRSession interface returns an XRInputSourceArray object which lists all controllers and input devices which are expressly associated with the XR device and are currently available. These controllers may include handheld controllers, XR-equipped gloves, optically tracked hands, and gaze-based input methods. Keyboards, gamepads, and mice are not considered WebXR input sources.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSession/inputSources)
     */
    readonly inputSources: XRInputSourceArray;
    /**
     * The XRSession interface's read-only **`interactionMode`** property describes the best space (according to the user agent) for the application to draw an interactive UI for the current session.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSession/interactionMode)
     */
    readonly interactionMode: XRInteractionMode;
    readonly maxRenderLayers: number;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSession/end_event) */
    onend: ((this: XRSession, ev: XRSessionEvent) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSession/inputsourceschange_event) */
    oninputsourceschange: ((this: XRSession, ev: XRInputSourcesChangeEvent) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSession/select_event) */
    onselect: ((this: XRSession, ev: XRInputSourceEvent) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSession/selectend_event) */
    onselectend: ((this: XRSession, ev: XRInputSourceEvent) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSession/selectstart_event) */
    onselectstart: ((this: XRSession, ev: XRInputSourceEvent) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSession/squeeze_event) */
    onsqueeze: ((this: XRSession, ev: XRInputSourceEvent) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSession/squeezeend_event) */
    onsqueezeend: ((this: XRSession, ev: XRInputSourceEvent) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSession/squeezestart_event) */
    onsqueezestart: ((this: XRSession, ev: XRInputSourceEvent) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSession/visibilitychange_event) */
    onvisibilitychange: ((this: XRSession, ev: XRSessionEvent) => any) | null;
    /**
     * The read-only **`preferredReflectionFormat`** property of the XRSession interface returns this session's preferred reflection format used for lighting estimation texture data.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSession/preferredReflectionFormat)
     */
    readonly preferredReflectionFormat: XRReflectionFormat;
    /**
     * The read-only **`renderState`** property of an XRSession object indicates the returns a XRRenderState object describing how the user's environment which should be rendered. The information provided covers the minimum and maximum distance at which to render objects, the vertical field of view to use when rendering the in the inline session mode, and the XRWebGLLayer to render into for inline composition.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSession/renderState)
     */
    readonly renderState: XRRenderState;
    /**
     * The read-only **`visibilityState`** property of the XRSession interface is a string indicating whether the WebXR content is currently visible to the user, and if it is, whether it's the primary focus.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSession/visibilityState)
     */
    readonly visibilityState: XRVisibilityState;
    /**
     * The **`cancelAnimationFrame()`** method of the XRSession interface cancels an animation frame which was previously requested by calling requestAnimationFrame.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSession/cancelAnimationFrame)
     */
    cancelAnimationFrame(handle: number): void;
    /**
     * The **`end()`** method shuts down the XRSession on which it's called, returning a promise which resolves once the session has fully shut down.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSession/end)
     */
    end(): Promise<void>;
    initiateRoomCapture(): Promise<void>;
    pauseDepthSensing(): void;
    /**
     * The XRSession method **`requestAnimationFrame()`**, much like the Window method of the same name, schedules a callback to be executed the next time the browser is ready to paint the session's virtual environment to the XR display. The specified callback is executed once before the next repaint; if you wish for it to be executed for the following repaint, you must call requestAnimationFrame() again. This can be done from within the callback itself.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSession/requestAnimationFrame)
     */
    requestAnimationFrame(callback: XRFrameRequestCallback): number;
    /**
     * The **`requestHitTestSource()`** method of the XRSession interface returns a Promise that resolves with an XRHitTestSource object that can be passed to XRFrame.getHitTestResults().
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSession/requestHitTestSource)
     */
    requestHitTestSource(options: XRHitTestOptionsInit): Promise<XRHitTestSource>;
    /**
     * The **`requestHitTestSourceForTransientInput()`** method of the XRSession interface returns a Promise that resolves with an XRTransientInputHitTestSource object that can be passed to XRFrame.getHitTestResultsForTransientInput().
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSession/requestHitTestSourceForTransientInput)
     */
    requestHitTestSourceForTransientInput(options: XRTransientInputHitTestOptionsInit): Promise<XRTransientInputHitTestSource>;
    /**
     * The **`requestLightProbe()`** method of the XRSession interface returns a Promise that resolves with an XRLightProbe object that estimates lighting information at a given point in the user's environment.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSession/requestLightProbe)
     */
    requestLightProbe(options?: XRLightProbeInit): Promise<XRLightProbe>;
    /**
     * The **`requestReferenceSpace()`** method of the XRSession interface returns a promise that resolves with an instance of either XRReferenceSpace or XRBoundedReferenceSpace as appropriate given the type of reference space requested.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSession/requestReferenceSpace)
     */
    requestReferenceSpace(type: XRReferenceSpaceType): Promise<XRReferenceSpace>;
    resumeDepthSensing(): void;
    /**
     * The **`updateRenderState()`** method of the XRSession interface of the WebXR API schedules changes to be applied to the active render state (XRRenderState) prior to rendering of the next frame.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSession/updateRenderState)
     */
    updateRenderState(state?: XRRenderStateInit): void;
    addEventListener<K extends keyof XRSessionEventMap>(type: K, listener: (this: XRSession, ev: XRSessionEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof XRSessionEventMap>(type: K, listener: (this: XRSession, ev: XRSessionEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var XRSession: {
    prototype: XRSession;
    new(): XRSession;
};

/**
 * The WebXR Device API's **`XRSessionEvent`** interface describes an event which indicates the change of the state of an XRSession. These events occur, for example, when the session ends or the visibility of its context changes.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSessionEvent)
 */
interface XRSessionEvent extends Event {
    /**
     * The read-only XRSessionEvent interface's **`session`** property indicates which XRSession the event is about.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSessionEvent/session)
     */
    readonly session: XRSession;
}

declare var XRSessionEvent: {
    prototype: XRSessionEvent;
    new(type: string, eventInitDict: XRSessionEventInit): XRSessionEvent;
};

/**
 * The **`XRSpace`** interface of the WebXR Device API is an abstract interface providing a common basis for every class which represents a virtual coordinate system within the virtual world, in which its origin corresponds to a physical location. Spatial data in WebXR is always expressed relative to an object based upon one of the descendant interfaces of XRSpace, at the time at which a given XRFrame takes place.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSpace)
 */
interface XRSpace extends EventTarget {
}

declare var XRSpace: {
    prototype: XRSpace;
    new(): XRSpace;
};

interface XRSystemEventMap {
    "devicechange": Event;
}

/**
 * The WebXR Device API interface **`XRSystem`** provides methods which let you get access to an XRSession object representing a WebXR session. With that XRSession in hand, you can use it to interact with the Augmented Reality (AR) or Virtual Reality (VR) device.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSystem)
 */
interface XRSystem extends EventTarget {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSystem/devicechange_event) */
    ondevicechange: ((this: XRSystem, ev: Event) => any) | null;
    /**
     * The XRSystem method **`isSessionSupported()`** returns a promise which resolves to true if the specified WebXR session mode is supported by the user's WebXR device. Otherwise, the promise resolves with false.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSystem/isSessionSupported)
     */
    isSessionSupported(mode: XRSessionMode): Promise<boolean>;
    /**
     * The XRSystem interface's **`requestSession()`** method returns a promise which resolves to an XRSession object through which you can manage the requested type of WebXR session.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSystem/requestSession)
     */
    requestSession(mode: XRSessionMode, options?: XRSessionInit): Promise<XRSession>;
    addEventListener<K extends keyof XRSystemEventMap>(type: K, listener: (this: XRSystem, ev: XRSystemEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof XRSystemEventMap>(type: K, listener: (this: XRSystem, ev: XRSystemEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var XRSystem: {
    prototype: XRSystem;
    new(): XRSystem;
};

/**
 * The WebXR Device API's **`XRView`** interface describes a single view into the XR scene for a specific frame, providing orientation and position information for the viewpoint. You can think of it as a description of a specific eye or camera and how it views the world. A 3D frame will involve two views, one for each eye, separated by an appropriate distance which approximates the distance between the viewer's eyes. This allows the two views, when projected in isolation into the appropriate eyes, to simulate a 3D world.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRView)
 */
interface XRView extends XRViewGeometry {
    readonly camera: XRCamera | null;
    /**
     * The XRView interface's read-only **`eye`** property is a string indicating which eye's viewpoint the XRView represents: left or right. For views which represent neither eye, such as monoscopic views, this property's value is none.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRView/eye)
     */
    readonly eye: XREye;
    readonly index: number;
    /**
     * The XRView interface's read-only **`isFirstPersonObserver`** property is a boolean indicating if the XRView is a first-person observer view.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRView/isFirstPersonObserver)
     */
    readonly isFirstPersonObserver: boolean;
    /**
     * The read-only **`recommendedViewportScale`** property of the XRView interface is the recommended viewport scale value that you can use for XRView.requestViewportScale() if the user agent has such a recommendation; null otherwise.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRView/recommendedViewportScale)
     */
    readonly recommendedViewportScale: number | null;
    /**
     * The **`requestViewportScale()`** method of the XRView interface requests that the user agent sets the requested viewport scale for this viewport to the given value. This is used for dynamic viewport scaling which allows rendering to a subset of the WebXR viewport using a scale factor that can be changed every animation frame.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRView/requestViewportScale)
     */
    requestViewportScale(scale: number | null): void;
}

declare var XRView: {
    prototype: XRView;
    new(): XRView;
};

/** Available only in secure contexts. */
interface XRViewGeometry {
    readonly projectionMatrix: Float32Array<ArrayBuffer>;
    readonly transform: XRRigidTransform;
}

/**
 * The WebXR Device API interface **`XRViewerPose`** represents the pose (the position and orientation) of a viewer's point of view on the scene. Each XRViewerPose can have multiple views to represent, for example, the slight separation between the left and right eye.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRViewerPose)
 */
interface XRViewerPose extends XRPose {
    /**
     * The read-only XRViewerPose property **`views`** returns an array which contains every XRView which must be rendered in order to fully represent the scene from the viewpoint defined by the viewer pose. For monoscopic devices, this array contains a single view.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRViewerPose/views)
     */
    readonly views: ReadonlyArray<XRView>;
}

declare var XRViewerPose: {
    prototype: XRViewerPose;
    new(): XRViewerPose;
};

/**
 * The WebXR Device API's **`XRViewport`** interface provides properties used to describe the size and position of the current viewport within the XRWebGLLayer being used to render the 3D scene.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRViewport)
 */
interface XRViewport {
    /**
     * The read-only XRViewport property **`height`** specifies the height, in pixels, of the viewport onto the drawing surface within which the WebXR view is to be rendered. Along with width and the origin point given by x and y, this defines the area within which rendered content will be drawn.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRViewport/height)
     */
    readonly height: number;
    /**
     * The read-only XRViewport property **`width`** specifies the width of the viewport, in pixels, onto the drawing surface the 3D scene is to be rendered into. This is defined using this property along with the viewport's height and its origin given by its properties x and y.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRViewport/width)
     */
    readonly width: number;
    /**
     * The read-only XRViewport interface's **`x`** property indicates the offset from the left edge of the destination surface (typically a XRWebGLLayer) to the left edge of the viewport within the surface into which WebXR content is to be rendered. The viewport's y property identifies the y component of the origin, and its is given by the width and height properties.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRViewport/x)
     */
    readonly x: number;
    /**
     * The read-onl**`y`** XRViewport interface's y property indicates the offset from the bottom edge of the destination surface (typically a XRWebGLLayer) to the bottom edge of the viewport within the surface into which WebXR content is to be rendered. The viewport's x property identifies the x component of the origin, and its is given by the width and height properties.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRViewport/y)
     */
    readonly y: number;
}

declare var XRViewport: {
    prototype: XRViewport;
    new(): XRViewport;
};

/** Available only in secure contexts. */
interface XRVisibilityMaskChangeEvent extends Event {
    readonly eye: XREye;
    readonly index: number;
    readonly indices: Uint32Array<ArrayBuffer>;
    readonly session: XRSession;
    readonly vertices: Float32Array<ArrayBuffer>;
}

declare var XRVisibilityMaskChangeEvent: {
    prototype: XRVisibilityMaskChangeEvent;
    new(type: string, eventInitDict: XRVisibilityMaskChangeEventInit): XRVisibilityMaskChangeEvent;
};

/**
 * The **`XRWebGLLayer`** interface of the WebXR Device API provides a linkage between the WebXR device (or simulated XR device, in the case of an inline session) and a WebGL context used to render the scene for display on the device. In particular, it provides access to the WebGL framebuffer and viewport to ease access to the context.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRWebGLLayer)
 */
interface XRWebGLLayer extends XRLayer {
    /**
     * The read-only XRWebGLLayer property **`antialias`** is a Boolean value which is true if the rendering layer's frame buffer supports anti-aliasing. Otherwise, this property's value is false. The specific anti-aliasing technique used is left to the user agent's discretion and cannot be specified by the website or web app.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRWebGLLayer/antialias)
     */
    readonly antialias: boolean;
    /**
     * The read-only XRWebGLLayer property **`framebuffer`** is an opaque WebGLFramebuffer which is used to buffer the rendered image if the XR compositor is being used. Otherwise, this property's value is null. The opaque framebuffer is functionally nearly the same as a standard WebGL framebuffer, except for the differences covered in the section How opaque framebuffers are special below.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRWebGLLayer/framebuffer)
     */
    readonly framebuffer: WebGLFramebuffer | null;
    /**
     * The read-only XRWebGLLayer property **`framebufferHeight`** indicates the height of the framebuffer, in pixels.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRWebGLLayer/framebufferHeight)
     */
    readonly framebufferHeight: number;
    /**
     * The read-only XRWebGLLayer property **`framebufferWidth`** specifies the width of the framebuffer, in pixels.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRWebGLLayer/framebufferWidth)
     */
    readonly framebufferWidth: number;
    /**
     * The read-only XRWebGLLayer property **`ignoreDepthValues`** is a Boolean value which is true if the session has been configured to ignore the values in the depth buffer while rendering the scene. If the depth buffer is being used to determine the position of vertices, this property is false.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRWebGLLayer/ignoreDepthValues)
     */
    readonly ignoreDepthValues: boolean;
    /**
     * The XRWebGLLayer interface's **`getViewport()`** method returns the XRViewport that should be used to render the specified XRView into the WebGL layer. For WebXR devices which use a single framebuffer for both the left and right eyes, the returned viewport represents the region of the framebuffer into which the scene should be rendered for the eye represented by the view.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRWebGLLayer/getViewport)
     */
    getViewport(view: XRView): XRViewport | null;
}

declare var XRWebGLLayer: {
    prototype: XRWebGLLayer;
    new(session: XRSession, context: XRWebGLRenderingContext, layerInit?: XRWebGLLayerInit): XRWebGLLayer;
    /**
     * The static method **`XRWebGLLayer.getNativeFramebufferScaleFactor()`** returns a floating-point scaling factor by which one can multiply the specified XRSession's resolution to get the native resolution of the WebXR device's frame buffer.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRWebGLLayer/getNativeFramebufferScaleFactor_static)
     */
    getNativeFramebufferScaleFactor(session: XRSession): number;
};

interface XRFrameRequestCallback {
    (time: DOMHighResTimeStamp, frame: XRFrame): void;
}

type XRWebGLRenderingContext = WebGLRenderingContext | WebGL2RenderingContext;

type XREye = "left" | "none" | "right";

type XRHandedness = "left" | "none" | "right";

type XRReferenceSpaceType = "bounded-floor" | "local" | "local-floor" | "unbounded" | "viewer";

type XRSessionMode = "immersive-ar" | "immersive-vr" | "inline";

type XRTargetRayMode = "gaze" | "screen" | "tracked-pointer" | "transient-pointer";

type XRVisibilityState = "hidden" | "visible" | "visible-blurred";
