// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: window. Spec: webxrlayers

interface XRCubeLayerInit extends XRLayerInit {
    orientation?: DOMPointReadOnly | null;
}

interface XRCylinderLayerInit extends XRLayerInit {
    aspectRatio?: number;
    centralAngle?: number;
    radius?: number;
    transform?: XRRigidTransform | null;
}

interface XREquirectLayerInit extends XRLayerInit {
    centralHorizontalAngle?: number;
    lowerVerticalAngle?: number;
    radius?: number;
    transform?: XRRigidTransform | null;
    upperVerticalAngle?: number;
}

interface XRLayerEventInit extends EventInit {
    layer: XRLayer;
}

interface XRLayerInit {
    clearOnAccess?: boolean;
    colorFormat?: GLenum;
    depthFormat?: GLenum | null;
    isStatic?: boolean;
    layout?: XRLayerLayout;
    mipLevels?: number;
    space: XRSpace;
    textureType?: XRTextureType;
    viewPixelHeight: number;
    viewPixelWidth: number;
}

interface XRProjectionLayerInit {
    clearOnAccess?: boolean;
    colorFormat?: GLenum;
    depthFormat?: GLenum;
    scaleFactor?: number;
    textureType?: XRTextureType;
}

interface XRQuadLayerInit extends XRLayerInit {
    height?: number;
    transform?: XRRigidTransform | null;
    width?: number;
}

/**
 * The **`XRCompositionLayer`** interface of the WebXR Device API is a base class that defines a set of common properties and behaviors for WebXR layer types. It is not constructable on its own.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRCompositionLayer)
 */
interface XRCompositionLayer extends XRLayer {
    /**
     * The **`blendTextureSourceAlpha`** property of the XRCompositionLayer interface is a boolean enabling the layer's texture alpha channel.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRCompositionLayer/blendTextureSourceAlpha)
     */
    blendTextureSourceAlpha: boolean;
    forceMonoPresentation: boolean;
    /**
     * The read-only **`layout`** property of the XRCompositionLayer interface is the layout type of the layer.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRCompositionLayer/layout)
     */
    readonly layout: XRLayerLayout;
    /**
     * The read-only **`mipLevels`** property of the XRCompositionLayer interface is a layer's number of mip levels in the color and texture data. See also Mipmap on Wikipedia.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRCompositionLayer/mipLevels)
     */
    readonly mipLevels: number;
    /**
     * The read-only **`needsRedraw`** property of the XRCompositionLayer interface is a boolean signaling that the layer should be re-rendered in the next frame.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRCompositionLayer/needsRedraw)
     */
    readonly needsRedraw: boolean;
    opacity: number;
    /**
     * The **`destroy()`** method of the XRCompositionLayer interface deletes the references to the underlying graphics library for the layer. It also sets the color textures and depth stencil texture arrays to an empty array.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRCompositionLayer/destroy)
     */
    destroy(): void;
}

declare var XRCompositionLayer: {
    prototype: XRCompositionLayer;
    new(): XRCompositionLayer;
};

interface XRCubeLayerEventMap {
    "redraw": XRLayerEvent;
}

/**
 * The **`XRCubeLayer`** interface of the WebXR Device API is a layer that renders directly from a cubemap and projects it onto the inside faces of a cube.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRCubeLayer)
 */
interface XRCubeLayer extends XRCompositionLayer {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRCubeLayer/redraw_event) */
    onredraw: ((this: XRCubeLayer, ev: XRLayerEvent) => any) | null;
    /**
     * The **`orientation`** property of the XRCubeLayer interface represents the orientation relative to the space property.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRCubeLayer/orientation)
     */
    orientation: DOMPointReadOnly;
    /**
     * The **`space`** property of the XRCubeLayer interface represents the layer's spatial relationship with the user's physical environment.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRCubeLayer/space)
     */
    space: XRSpace;
    addEventListener<K extends keyof XRCubeLayerEventMap>(type: K, listener: (this: XRCubeLayer, ev: XRCubeLayerEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof XRCubeLayerEventMap>(type: K, listener: (this: XRCubeLayer, ev: XRCubeLayerEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var XRCubeLayer: {
    prototype: XRCubeLayer;
    new(): XRCubeLayer;
};

interface XRCylinderLayerEventMap {
    "redraw": XRLayerEvent;
}

/**
 * The **`XRCylinderLayer`** interface of the WebXR Device API is a layer that takes up a curved rectangular space in the virtual environment. Only the front of the layer is visible.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRCylinderLayer)
 */
interface XRCylinderLayer extends XRCompositionLayer {
    /**
     * The **`aspectRatio`** property of the XRCylinderLayer interface represents the ratio of the visible cylinder section. It is the ratio of the width of the visible section of the cylinder divided by its height. The width is calculated by multiplying the radius with the centralAngle.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRCylinderLayer/aspectRatio)
     */
    aspectRatio: number;
    /**
     * The **`centralAngle`** property of the XRCylinderLayer interface represents the angle in radians of the visible section of the cylinder.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRCylinderLayer/centralAngle)
     */
    centralAngle: number;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRCylinderLayer/redraw_event) */
    onredraw: ((this: XRCylinderLayer, ev: XRLayerEvent) => any) | null;
    /**
     * The **`radius`** property of the XRCylinderLayer interface represents the radius of the cylinder.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRCylinderLayer/radius)
     */
    radius: number;
    /**
     * The **`space`** property of the XRCylinderLayer interface represents the layer's spatial relationship with the user's physical environment.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRCylinderLayer/space)
     */
    space: XRSpace;
    /**
     * The **`transform`** property of the XRCylinderLayer interface represents the offset and orientation relative to the layer's space.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRCylinderLayer/transform)
     */
    transform: XRRigidTransform;
    addEventListener<K extends keyof XRCylinderLayerEventMap>(type: K, listener: (this: XRCylinderLayer, ev: XRCylinderLayerEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof XRCylinderLayerEventMap>(type: K, listener: (this: XRCylinderLayer, ev: XRCylinderLayerEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var XRCylinderLayer: {
    prototype: XRCylinderLayer;
    new(): XRCylinderLayer;
};

interface XREquirectLayerEventMap {
    "redraw": XRLayerEvent;
}

/**
 * The **`XREquirectLayer`** interface of the WebXR Device API is a layer that maps equirectangular coded data onto the inside of a sphere.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XREquirectLayer)
 */
interface XREquirectLayer extends XRCompositionLayer {
    /**
     * The **`centralHorizontalAngle`** property of the XREquirectLayer interface represents the central horizontal angle in radians for the sphere.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XREquirectLayer/centralHorizontalAngle)
     */
    centralHorizontalAngle: number;
    /**
     * The **`lowerVerticalAngle`** property of the XREquirectLayer interface represents the lower vertical angle in radians for the sphere.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XREquirectLayer/lowerVerticalAngle)
     */
    lowerVerticalAngle: number;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/XREquirectLayer/redraw_event) */
    onredraw: ((this: XREquirectLayer, ev: XRLayerEvent) => any) | null;
    /**
     * The **`radius`** property of the XREquirectLayer interface represents the radius of the sphere.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XREquirectLayer/radius)
     */
    radius: number;
    /**
     * The **`space`** property of the XREquirectLayer interface represents the layer's spatial relationship with the user's physical environment.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XREquirectLayer/space)
     */
    space: XRSpace;
    /**
     * The **`transform`** property of the XREquirectLayer interface represents the offset and orientation relative to the layer's space.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XREquirectLayer/transform)
     */
    transform: XRRigidTransform;
    /**
     * The **`upperVerticalAngle`** property of the XREquirectLayer interface represents the upper vertical angle in radians for the sphere.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XREquirectLayer/upperVerticalAngle)
     */
    upperVerticalAngle: number;
    addEventListener<K extends keyof XREquirectLayerEventMap>(type: K, listener: (this: XREquirectLayer, ev: XREquirectLayerEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof XREquirectLayerEventMap>(type: K, listener: (this: XREquirectLayer, ev: XREquirectLayerEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var XREquirectLayer: {
    prototype: XREquirectLayer;
    new(): XREquirectLayer;
};

/**
 * The **`XRLayerEvent`** interface of the WebXR Device API is the event type for events related to a change of state of an XRLayer object. These events occur, for example, when the layer needs to be redrawn.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRLayerEvent)
 */
interface XRLayerEvent extends Event {
    /**
     * The **`layer`** property of the XRLayerEvent interface is a reference to the XRLayer which generated the event.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRLayerEvent/layer)
     */
    readonly layer: XRLayer;
}

declare var XRLayerEvent: {
    prototype: XRLayerEvent;
    new(type: string, eventInitDict: XRLayerEventInit): XRLayerEvent;
};

/**
 * The **`XRProjectionLayer`** interface of the WebXR Device API is a layer that fills the entire view of the observer and is refreshed close to the device's native frame rate.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRProjectionLayer)
 */
interface XRProjectionLayer extends XRCompositionLayer {
    deltaPose: XRRigidTransform | null;
    /**
     * The **`fixedFoveation`** property of the XRProjectionLayer interface is a number indicating the amount of foveation used by the XR compositor for the layer. Fixed Foveated Rendering (FFR) renders the edges of the eye textures at a lower resolution than the center and reduces the GPU load.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRProjectionLayer/fixedFoveation)
     */
    fixedFoveation: number | null;
    /**
     * The read-only **`ignoreDepthValues`** property of the XRProjectionLayer interface is a boolean indicating if the XR compositor is not making use of depth buffer values when rendering the layer.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRProjectionLayer/ignoreDepthValues)
     */
    readonly ignoreDepthValues: boolean;
    /**
     * The read-only **`textureArrayLength`** property of the XRProjectionLayer interface indicates layer's layer count for array textures when using texture-array as the textureType.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRProjectionLayer/textureArrayLength)
     */
    readonly textureArrayLength: number;
    /**
     * The read-only **`textureHeight`** property of the XRProjectionLayer interface indicates the height in pixels of the color textures of this layer.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRProjectionLayer/textureHeight)
     */
    readonly textureHeight: number;
    /**
     * The read-only **`textureWidth`** property of the XRProjectionLayer interface indicates the width in pixels of the color textures of this layer.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRProjectionLayer/textureWidth)
     */
    readonly textureWidth: number;
}

declare var XRProjectionLayer: {
    prototype: XRProjectionLayer;
    new(): XRProjectionLayer;
};

interface XRQuadLayerEventMap {
    "redraw": XRLayerEvent;
}

/**
 * The **`XRQuadLayer`** interface of the WebXR Device API is a layer that takes up a flat rectangular space in the virtual environment. An XRQuadLayer has no thickness. It is a two-dimensional object positioned and oriented in 3D space. The position of a quad refers to the center of the quad. Only the front of the layer is visible.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRQuadLayer)
 */
interface XRQuadLayer extends XRCompositionLayer {
    /**
     * The **`height`** property of the XRQuadLayer interface represents the height of the layer in meters.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRQuadLayer/height)
     */
    height: number;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRQuadLayer/redraw_event) */
    onredraw: ((this: XRQuadLayer, ev: XRLayerEvent) => any) | null;
    /**
     * The **`space`** property of the XRQuadLayer interface represents the layer's spatial relationship with the user's physical environment.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRQuadLayer/space)
     */
    space: XRSpace;
    /**
     * The **`transform`** property of the XRQuadLayer interface represents the offset and orientation relative to the layer's space.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRQuadLayer/transform)
     */
    transform: XRRigidTransform;
    /**
     * The **`width`** property of the XRQuadLayer interface represents the width of the layer in meters.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRQuadLayer/width)
     */
    width: number;
    addEventListener<K extends keyof XRQuadLayerEventMap>(type: K, listener: (this: XRQuadLayer, ev: XRQuadLayerEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof XRQuadLayerEventMap>(type: K, listener: (this: XRQuadLayer, ev: XRQuadLayerEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var XRQuadLayer: {
    prototype: XRQuadLayer;
    new(): XRQuadLayer;
};

/**
 * The **`XRSubImage`** interface of the WebXR Device API represents what viewport of the GPU texture to use for rendering.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSubImage)
 */
interface XRSubImage {
    /**
     * The read-only **`viewport`** property of the XRSubImage interface represents the XRViewport that is used when rendering the sub image.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRSubImage/viewport)
     */
    readonly viewport: XRViewport;
}

declare var XRSubImage: {
    prototype: XRSubImage;
    new(): XRSubImage;
};

/**
 * The **`XRWebGLBinding`** interface is used to create layers that have a GPU backend.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRWebGLBinding)
 */
interface XRWebGLBinding {
    /**
     * The read-only **`nativeProjectionScaleFactor`** property of the XRWebGLBinding interface represents the scaling factor by which the projection layer's resolution is multiplied by to get the native resolution of the WebXR device's frame buffer.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRWebGLBinding/nativeProjectionScaleFactor)
     */
    readonly nativeProjectionScaleFactor: number;
    readonly usesDepthValues: boolean;
    /**
     * The **`createCubeLayer()`** method of the XRWebGLBinding interface returns an XRCubeLayer object, which is a layer that renders directly from a cubemap, and projects it onto the inside faces of a cube.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRWebGLBinding/createCubeLayer)
     */
    createCubeLayer(init?: XRCubeLayerInit): XRCubeLayer;
    /**
     * The **`createCylinderLayer()`** method of the XRWebGLBinding interface returns an XRCylinderLayer object, which is a layer that takes up a curved rectangular space in the virtual environment.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRWebGLBinding/createCylinderLayer)
     */
    createCylinderLayer(init?: XRCylinderLayerInit): XRCylinderLayer;
    /**
     * The **`createEquirectLayer()`** method of the XRWebGLBinding interface returns an XREquirectLayer object, which is a layer that maps equirectangular coded data onto the inside of a sphere.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRWebGLBinding/createEquirectLayer)
     */
    createEquirectLayer(init?: XREquirectLayerInit): XREquirectLayer;
    /**
     * The **`createProjectionLayer()`** method of the XRWebGLBinding interface returns an XRProjectionLayer object which is a layer that fills the entire view of the observer and is refreshed close to the device's native frame rate.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRWebGLBinding/createProjectionLayer)
     */
    createProjectionLayer(init?: XRProjectionLayerInit): XRProjectionLayer;
    /**
     * The **`createQuadLayer()`** method of the XRWebGLBinding interface returns an XRQuadLayer object which is a layer that takes up a flat rectangular space in the virtual environment.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRWebGLBinding/createQuadLayer)
     */
    createQuadLayer(init?: XRQuadLayerInit): XRQuadLayer;
    getCameraImage(camera: XRCamera): WebGLTexture | null;
    /**
     * The **`getDepthInformation()`** method of the XRWebGLBinding interface returns an XRWebGLDepthInformation object containing WebGL depth information.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRWebGLBinding/getDepthInformation)
     */
    getDepthInformation(view: XRView): XRWebGLDepthInformation | null;
    /**
     * The **`getReflectionCubeMap()`** method of the XRWebGLBinding interface returns a WebGLTexture object containing a reflection cube map texture.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRWebGLBinding/getReflectionCubeMap)
     */
    getReflectionCubeMap(lightProbe: XRLightProbe): WebGLTexture | null;
    /**
     * The **`getSubImage()`** method of the XRWebGLBinding interface returns a XRWebGLSubImage object representing the WebGL texture to render.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRWebGLBinding/getSubImage)
     */
    getSubImage(layer: XRCompositionLayer, frame: XRFrame, eye?: XREye): XRWebGLSubImage;
    /**
     * The **`getViewSubImage()`** method of the XRWebGLBinding interface returns a XRWebGLSubImage object representing the WebGL texture to render for a view.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRWebGLBinding/getViewSubImage)
     */
    getViewSubImage(layer: XRProjectionLayer, view: XRView): XRWebGLSubImage;
}

declare var XRWebGLBinding: {
    prototype: XRWebGLBinding;
    new(session: XRSession, context: XRWebGLRenderingContext): XRWebGLBinding;
};

/**
 * The **`XRWebGLSubImage`** interface is used during rendering of WebGL layers.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRWebGLSubImage)
 */
interface XRWebGLSubImage extends XRSubImage {
    /**
     * The read-only **`colorTexture`** property of the XRWebGLSubImage interface represents the color WebGLTexture object for the XRCompositionLayer to render.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRWebGLSubImage/colorTexture)
     */
    readonly colorTexture: WebGLTexture;
    /**
     * The read-only **`colorTextureHeight`** property of the XRWebGLSubImage interface is a number representing the height in pixels of the GL attachment.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRWebGLSubImage/colorTextureHeight)
     */
    readonly colorTextureHeight: number;
    /**
     * The read-only **`colorTextureWidth`** property of the XRWebGLSubImage interface is a number representing the width in pixels of the GL attachment.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRWebGLSubImage/colorTextureWidth)
     */
    readonly colorTextureWidth: number;
    /**
     * The read-only **`depthStencilTexture`** property of the XRWebGLSubImage interface represents the depth/stencil WebGLTexture object for the XRCompositionLayer to render.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRWebGLSubImage/depthStencilTexture)
     */
    readonly depthStencilTexture: WebGLTexture | null;
    readonly depthStencilTextureHeight: number | null;
    readonly depthStencilTextureWidth: number | null;
    /**
     * The read-only **`imageIndex`** property of the XRWebGLSubImage interface is a number representing the offset into the texture array if the layer was requested with texture-array; null otherwise.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/XRWebGLSubImage/imageIndex)
     */
    readonly imageIndex: number | null;
    readonly motionVectorTexture: WebGLTexture | null;
    readonly motionVectorTextureHeight: number | null;
    readonly motionVectorTextureWidth: number | null;
}

declare var XRWebGLSubImage: {
    prototype: XRWebGLSubImage;
    new(): XRWebGLSubImage;
};

type XRLayerLayout = "default" | "mono" | "stereo" | "stereo-left-right" | "stereo-top-bottom";

type XRTextureType = "texture" | "texture-array";
