// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream 245655f1e887) — do not edit.
// Scope: dom. Spec: webxr-ar-module

type XREnvironmentBlendMode = "additive" | "alpha-blend" | "opaque";

type XRInteractionMode = "screen-space" | "world-space";
