// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Spec: window-management

interface FullscreenOptions {
    screen?: ScreenDetailed;
}

interface Screen {
    /**
     * The **`isExtended`** read-only property of the Screen interface returns true if the user's device has multiple screens, and false if not.
     * Available only in secure contexts.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Screen/isExtended)
     */
    readonly isExtended: boolean;
    /**
     * Available only in secure contexts.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Screen/change_event)
     */
    onchange: ((this: Screen, ev: Event) => any) | null;
}

/**
 * The **`ScreenDetailed`** interface of the Window Management API represents detailed information about one specific screen available to the user's device.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ScreenDetailed)
 */
interface ScreenDetailed extends Screen {
    /**
     * The **`availLeft`** read-only property of the ScreenDetailed interface is a number representing the x-coordinate (left-hand edge) of the available screen area inside the OS virtual screen arrangement, relative to the multi-screen origin.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ScreenDetailed/availLeft)
     */
    readonly availLeft: number;
    /**
     * The **`availTop`** read-only property of the ScreenDetailed interface is a number representing the y-coordinate (top edge) of the available screen area inside the OS virtual screen arrangement, relative to the multi-screen origin.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ScreenDetailed/availTop)
     */
    readonly availTop: number;
    /**
     * The **`devicePixelRatio`** read-only property of the ScreenDetailed interface is a number representing the screen's device pixel ratio.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ScreenDetailed/devicePixelRatio)
     */
    readonly devicePixelRatio: number;
    /**
     * The **`isInternal`** read-only property of the ScreenDetailed interface is a boolean indicating whether the screen is internal to the device or external. External devices are generally manufactured separately from the device they are attached to and can be connected and disconnected as needed, whereas internal screens are part of the device and not intended to be disconnected.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ScreenDetailed/isInternal)
     */
    readonly isInternal: boolean;
    /**
     * The **`isPrimary`** read-only property of the ScreenDetailed interface is a boolean indicating whether the screen is set as the operating system (OS) primary screen or not.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ScreenDetailed/isPrimary)
     */
    readonly isPrimary: boolean;
    /**
     * The **`label`** read-only property of the ScreenDetailed interface is a string providing a descriptive label for the screen, for example "Built-in Retina Display".
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ScreenDetailed/label)
     */
    readonly label: string;
    /**
     * The **`left`** read-only property of the ScreenDetailed interface is a number representing the x-coordinate (left-hand edge) of the total screen area inside the OS virtual screen arrangement, relative to the multi-screen origin.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ScreenDetailed/left)
     */
    readonly left: number;
    /**
     * The **`top`** read-only property of the ScreenDetailed interface is a number representing the y-coordinate (top edge) of the total screen area inside the OS virtual screen arrangement, relative to the multi-screen origin.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ScreenDetailed/top)
     */
    readonly top: number;
    addEventListener<K extends keyof ScreenEventMap>(type: K, listener: (this: ScreenDetailed, ev: ScreenEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof ScreenEventMap>(type: K, listener: (this: ScreenDetailed, ev: ScreenEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var ScreenDetailed: {
    prototype: ScreenDetailed;
    new(): ScreenDetailed;
};

interface ScreenDetailsEventMap {
    "currentscreenchange": Event;
    "screenschange": Event;
}

/**
 * The **`ScreenDetails`** interface of the Window Management API represents the details of all the screens available to the user's device.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ScreenDetails)
 */
interface ScreenDetails extends EventTarget {
    /**
     * The **`currentScreen`** read-only property of the ScreenDetails interface contains a single ScreenDetailed object representing detailed information about the screen that the current browser window is displayed in.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ScreenDetails/currentScreen)
     */
    readonly currentScreen: ScreenDetailed;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/ScreenDetails/currentscreenchange_event) */
    oncurrentscreenchange: ((this: ScreenDetails, ev: Event) => any) | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/ScreenDetails/screenschange_event) */
    onscreenschange: ((this: ScreenDetails, ev: Event) => any) | null;
    /**
     * The **`screens`** read-only property of the ScreenDetails interface contains an array of ScreenDetailed objects, each one representing detailed information about one specific screen available to the user's device.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/ScreenDetails/screens)
     */
    readonly screens: ReadonlyArray<ScreenDetailed>;
    addEventListener<K extends keyof ScreenDetailsEventMap>(type: K, listener: (this: ScreenDetails, ev: ScreenDetailsEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof ScreenDetailsEventMap>(type: K, listener: (this: ScreenDetails, ev: ScreenDetailsEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var ScreenDetails: {
    prototype: ScreenDetails;
    new(): ScreenDetails;
};

interface Window {
    /**
     * The **`getScreenDetails()`** method of the Window interface returns a Promise that fulfills with a ScreenDetails object instance representing the details of all the screens available to the user's device.
     * Available only in secure contexts.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Window/getScreenDetails)
     */
    getScreenDetails(): Promise<ScreenDetails>;
}

/**
 * The **`getScreenDetails()`** method of the Window interface returns a Promise that fulfills with a ScreenDetails object instance representing the details of all the screens available to the user's device.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Window/getScreenDetails)
 */
declare function getScreenDetails(): Promise<ScreenDetails>;
