// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Spec: window-controls-overlay

interface WindowControlsOverlayGeometryChangeEventInit extends EventInit {
    titlebarAreaRect: DOMRect;
    visible?: boolean;
}

interface Navigator {
    /**
     * The **`windowControlsOverlay`** read-only property of the Navigator interface returns the WindowControlsOverlay interface, which exposes information about the title bar geometry in desktop Progressive Web Apps that use the Window Controls Overlay API.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Navigator/windowControlsOverlay)
     */
    readonly windowControlsOverlay: WindowControlsOverlay;
}

interface WindowControlsOverlayEventMap {
    "geometrychange": WindowControlsOverlayGeometryChangeEvent;
}

/**
 * The **`WindowControlsOverlay`** interface of the Window Controls Overlay API exposes information about the geometry of the title bar area in desktop Progressive Web Apps, and an event to know whenever it changes. This interface is accessible from Navigator.windowControlsOverlay.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/WindowControlsOverlay)
 */
interface WindowControlsOverlay extends EventTarget {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/WindowControlsOverlay/geometrychange_event) */
    ongeometrychange: ((this: WindowControlsOverlay, ev: WindowControlsOverlayGeometryChangeEvent) => any) | null;
    /**
     * The **`visible`** read-only property of the WindowControlsOverlay interface returns a Boolean that indicates whether the window controls overlay is visible or not.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/WindowControlsOverlay/visible)
     */
    readonly visible: boolean;
    /**
     * The **`getTitlebarAreaRect()`** method of the WindowControlsOverlay interface queries the current geometry of the title bar area of the Progressive Web App window.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/WindowControlsOverlay/getTitlebarAreaRect)
     */
    getTitlebarAreaRect(): DOMRect;
    addEventListener<K extends keyof WindowControlsOverlayEventMap>(type: K, listener: (this: WindowControlsOverlay, ev: WindowControlsOverlayEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof WindowControlsOverlayEventMap>(type: K, listener: (this: WindowControlsOverlay, ev: WindowControlsOverlayEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var WindowControlsOverlay: {
    prototype: WindowControlsOverlay;
    new(): WindowControlsOverlay;
};

/**
 * The **`WindowControlsOverlayGeometryChangeEvent`** interface of the Window Controls Overlay API is passed to geometrychange when the size or visibility of a desktop Progress Web App's title bar region changes.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/WindowControlsOverlayGeometryChangeEvent)
 */
interface WindowControlsOverlayGeometryChangeEvent extends Event {
    /**
     * The **`titlebarAreaRect`** read-only property of the WindowControlsOverlayGeometryChangeEvent interface is a DOMRect representing the position and size of the area occupied by the title bar in a desktop-installed Progressive Web App.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/WindowControlsOverlayGeometryChangeEvent/titlebarAreaRect)
     */
    readonly titlebarAreaRect: DOMRect;
    /**
     * The **`visible`** read-only property of the WindowControlsOverlayGeometryChangeEvent interface is a boolean flag that indicates whether the window controls overlay is visible or not in a desktop-installed Progressive Web App.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/WindowControlsOverlayGeometryChangeEvent/visible)
     */
    readonly visible: boolean;
}

declare var WindowControlsOverlayGeometryChangeEvent: {
    prototype: WindowControlsOverlayGeometryChangeEvent;
    new(type: string, eventInitDict: WindowControlsOverlayGeometryChangeEventInit): WindowControlsOverlayGeometryChangeEvent;
};
