// Generated by modern-web-types from TypeScript-DOM-lib-generator
// (upstream a193ecb2b75a) — do not edit.
// Scope: dom. Spec: writing-assistance-apis

interface SummarizerCreateCoreOptions {
    expectedContextLanguages?: string[];
    expectedInputLanguages?: string[];
    format?: SummarizerFormat;
    length?: SummarizerLength;
    outputLanguage?: string;
    preference?: PerformancePreference;
    type?: SummarizerType;
}

interface SummarizerCreateOptions extends SummarizerCreateCoreOptions {
    monitor?: CreateMonitorCallback;
    sharedContext?: string;
    signal?: AbortSignal;
}

interface SummarizerSummarizeOptions {
    context?: string;
    signal?: AbortSignal;
}

interface CreateMonitorEventMap {
    "downloadprogress": ProgressEvent<CreateMonitor>;
}

/**
 * The **`CreateMonitor`** interface provides information on the progress of an AI model download or some fine-tuning data for the model.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/CreateMonitor)
 */
interface CreateMonitor extends EventTarget {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/CreateMonitor/downloadprogress_event) */
    ondownloadprogress: ((this: CreateMonitor, ev: ProgressEvent<CreateMonitor>) => any) | null;
    addEventListener<K extends keyof CreateMonitorEventMap>(type: K, listener: (this: CreateMonitor, ev: CreateMonitorEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof CreateMonitorEventMap>(type: K, listener: (this: CreateMonitor, ev: CreateMonitorEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}

declare var CreateMonitor: {
    prototype: CreateMonitor;
    new(): CreateMonitor;
};

interface DestroyableModel {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/LanguageDetector/destroy) */
    destroy(): void;
}

/**
 * The **`Summarizer`** interface of the Summarizer API contains all the functionality for this API, including checking AI model availability, creating a new Summarizer instance, using it to generate a new summary, and more.
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Summarizer)
 */
interface Summarizer extends DestroyableModel {
    /**
     * The **`expectedContextLanguages`** read-only property of the Summarizer interface returns the languages the context strings should be written in.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Summarizer/expectedContextLanguages)
     */
    readonly expectedContextLanguages: ReadonlyArray<string> | null;
    /**
     * The **`expectedInputLanguages`** read-only property of the Summarizer interface returns the languages the Summarizer should support.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Summarizer/expectedInputLanguages)
     */
    readonly expectedInputLanguages: ReadonlyArray<string> | null;
    /**
     * The **`format`** read-only property of the Summarizer interface returns the text format summaries will be returned in.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Summarizer/format)
     */
    readonly format: SummarizerFormat;
    /**
     * The **`inputQuota`** read-only property of the Summarizer interface returns the input quota available to the browser for generating summaries.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Summarizer/inputQuota)
     */
    readonly inputQuota: number;
    /**
     * The **`length`** read-only property of the Summarizer interface returns the relative length of the generated summaries.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Summarizer/length)
     */
    readonly length: SummarizerLength;
    /**
     * The **`outputLanguage`** read-only property of the Summarizer interface returns the language the summary should be generated in.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Summarizer/outputLanguage)
     */
    readonly outputLanguage: string | null;
    /**
     * The **`sharedContext`** read-only property of the Summarizer interface returns a string describing the context the pieces of text to summarize are being used in. This helps the Summarizer to generate more suitable summaries.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Summarizer/sharedContext)
     */
    readonly sharedContext: string;
    /**
     * The **`type`** read-only property of the Summarizer interface returns the type of summary that will generated by the Summarizer.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Summarizer/type)
     */
    readonly type: SummarizerType;
    /**
     * The **`measureInputUsage()`** method of the Summarizer interface reports how much inputQuota would be used by a summarize operation for a given text input.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Summarizer/measureInputUsage)
     */
    measureInputUsage(input: string, options?: SummarizerSummarizeOptions): Promise<number>;
    /**
     * The **`summarize()`** method of the Summarizer interface generates a new summary string.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Summarizer/summarize)
     */
    summarize(input: string, options?: SummarizerSummarizeOptions): Promise<string>;
    /**
     * The **`summarizeStreaming()`** method of the Summarizer interface generates a new summary as a ReadableStream.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Summarizer/summarizeStreaming)
     */
    summarizeStreaming(input: string, options?: SummarizerSummarizeOptions): ReadableStream;
}

declare var Summarizer: {
    prototype: Summarizer;
    new(): Summarizer;
    /**
     * The **`availability()`** static method of the Summarizer interface returns an enumerated value that indicates whether the browser AI model supports (or will support) a given Summarizer configuration.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Summarizer/availability_static)
     */
    availability(options?: SummarizerCreateCoreOptions): Promise<Availability>;
    /**
     * The **`create()`** static method of the Summarizer interface creates a new Summarizer instance from which to generate summaries.
     *
     * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Summarizer/create_static)
     */
    create(options?: SummarizerCreateOptions): Promise<Summarizer>;
};

interface CreateMonitorCallback {
    (monitor: CreateMonitor): void;
}

type Availability = "available" | "downloadable" | "downloading" | "unavailable";

type PerformancePreference = "auto" | "capability" | "speed";

type SummarizerFormat = "markdown" | "plain-text";

type SummarizerLength = "long" | "medium" | "short";

type SummarizerType = "headline" | "key-points" | "teaser" | "tldr";
